package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.widget.*;
import androidx.media3.common.*;import androidx.media3.common.audio.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.audio.*;import java.nio.*;

/** PCM delay: positive values postpone sound, negative values advance it. */
final class AudioDelay extends BaseAudioProcessor {
 static final int STEP_MS=50,MAX_MS=2000;
 private volatile int milliseconds;private long pendingFrames;private int frameSize;
 AudioDelay(int value){set(value);}void set(int value){milliseconds=Math.max(-MAX_MS,Math.min(MAX_MS,value));}int get(){return milliseconds;}
 @Override protected AudioFormat onConfigure(AudioFormat format)throws UnhandledAudioFormatException {if(format.encoding!=C.ENCODING_PCM_16BIT&&format.encoding!=C.ENCODING_PCM_FLOAT&&format.encoding!=C.ENCODING_PCM_32BIT&&format.encoding!=C.ENCODING_PCM_24BIT)throw new UnhandledAudioFormatException(format);frameSize=format.bytesPerFrame;return format;}
 @Override protected void onFlush(){pendingFrames=(long)inputAudioFormat.sampleRate*milliseconds/1000;}
 @Override public void queueInput(ByteBuffer input){int available=input.remaining();if(frameSize<=0||available==0)return;if(pendingFrames<0){int skip=(int)Math.min((long)available/frameSize,-pendingFrames)*frameSize;input.position(input.position()+skip);pendingFrames+=skip/frameSize;available=input.remaining();if(pendingFrames<0)return;}int silence=pendingFrames>0?(int)pendingFrames*frameSize:0;pendingFrames=0;ByteBuffer out=replaceOutputBuffer(silence+available);for(int i=0;i<silence;i++)out.put((byte)0);out.put(input);out.flip();}
 static AudioDelay create(Context c,String key){return new AudioDelay(c.getSharedPreferences("audioDelay",0).getInt(key,0));}
 static DefaultRenderersFactory renderers(Context c,AudioDelay delay){return new DefaultRenderersFactory(c){@Override protected AudioSink buildAudioSink(Context context,boolean floating,boolean parameters){AudioSink sink=new DefaultAudioSink.Builder(context).setEnableFloatOutput(false).setAudioProcessors(new AudioProcessor[]{delay}).build();return new ForwardingAudioSink(sink){@Override public boolean supportsFormat(Format format){return MimeTypes.AUDIO_RAW.equals(format.sampleMimeType)&&super.supportsFormat(format);}@Override public int getFormatSupport(Format format){return MimeTypes.AUDIO_RAW.equals(format.sampleMimeType)?super.getFormatSupport(format):AudioSink.SINK_FORMAT_UNSUPPORTED;}};}};}
 static void menu(Activity a,String key,AudioDelay delay,Player player){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(24,16,24,16);TextView value=new TextView(a);value.setTextColor(UiTheme.TEXT);value.setTextSize(20);value.setText(label(delay.get()));box.addView(value);TextView help=new TextView(a);help.setText("+ ritarda il suono · − anticipa il suono\nPasso 50 ms · salvato per questo contenuto");help.setTextColor(UiTheme.TEXT);box.addView(help);LinearLayout row=new LinearLayout(a);box.addView(row);int[] steps={-STEP_MS,0,STEP_MS};String[] labels={"− 50 ms","Azzera","+ 50 ms"};for(int i=0;i<steps.length;i++){final int step=steps[i];Button b=new Button(a);b.setAllCaps(false);b.setText(labels[i]);UiTheme.navigation(b);row.addView(b,new LinearLayout.LayoutParams(0,56,1));b.setOnClickListener(v->{int next=step==0?0:delay.get()+step;delay.set(next);a.getSharedPreferences("audioDelay",0).edit().putInt(key,delay.get()).apply();value.setText(label(delay.get()));if(player!=null&&player.getCurrentMediaItem()!=null){boolean playing=player.getPlayWhenReady();long pos=player.getCurrentPosition();player.stop();if(player.isCurrentMediaItemSeekable())player.seekTo(pos);else player.seekToDefaultPosition();player.prepare();player.setPlayWhenReady(playing);}});}new AlertDialog.Builder(a).setTitle("Sincronizzazione audio").setView(box).setPositiveButton("Chiudi",null).show();}
 private static String label(int n){return "Audio: "+(n>0?"+":"")+n+" ms";}
}
