package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.text.InputType;import android.widget.*;import android.view.*;import android.view.inputmethod.EditorInfo;import java.io.*;
public class CloudActivity extends Activity {
 private final Handler ui=new Handler(Looper.getMainLooper());private boolean busy;private final Runnable refresh=new Runnable(){public void run(){if(!busy&&!isFinishing())status.setText(CloudSync.status(CloudActivity.this));ui.postDelayed(this,2000);}};private TextView status;private EditText email,password;private CheckBox merge;
 @Override public void onCreate(Bundle state){super.onCreate(state);CloudSync.initialize(this);ScrollView scroll=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(24,18,24,18);box.setBackgroundColor(0xff151619);scroll.addView(box);setContentView(scroll);Button back=add(box,"‹ VOD",this::finish);status=new TextView(this);status.setTextColor(UiTheme.TEXT);status.setTextSize(18);box.addView(status);email=VodSettings.input(this,"","Email del tuo account");email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);password=VodSettings.input(this,"","Password");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);password.setSaveEnabled(false);email.setId(View.generateViewId());password.setId(View.generateViewId());email.setImeOptions(EditorInfo.IME_ACTION_NEXT);password.setImeOptions(EditorInfo.IME_ACTION_DONE);box.addView(email);box.addView(password);merge=new CheckBox(this);merge.setText("Unisci i preferiti e la cronologia locali al mio account");merge.setTextColor(UiTheme.TEXT);merge.setChecked(true);merge.setFocusable(true);merge.setId(View.generateViewId());
  Button login=add(box,"Accedi",()->{com.google.firebase.auth.FirebaseAuth auth=CloudSync.auth(this);if(auth==null){status.setText("Configura prima il tuo progetto cloud");return;}String mail=email.getText().toString().trim(),pass=password.getText().toString();if(mail.isEmpty()||pass.isEmpty()){status.setText("Inserisci email e password");return;}busy=true;status.setText("Accesso…");auth.signInWithEmailAndPassword(mail,pass).addOnCompleteListener(this,task->{password.setText("");if(!task.isSuccessful()){busy=false;}if(!task.isSuccessful()){status.setText("Accesso non riuscito · controlla credenziali e rete");return;}CloudSync.authorize(this,merge.isChecked(),()->{busy=false;status.setText(CloudSync.status(this));Toast.makeText(this,"Dispositivo collegato",Toast.LENGTH_SHORT).show();},message->{busy=false;status.setText(message);});});});box.addView(merge,new LinearLayout.LayoutParams(-1,Math.round(52*getResources().getDisplayMetrics().density)));
  Button forgot=add(box,"Password dimenticata",()->{if(CloudSync.auth(this)==null){status.setText("Cloud non configurato");return;}String mail=email.getText().toString().trim();if(mail.isEmpty()){email.setError("Inserisci la tua email");return;}CloudSync.auth(this).sendPasswordResetEmail(mail).addOnCompleteListener(this,t->status.setText(t.isSuccessful()?"Controlla la tua email per recuperare la password":"Invio non riuscito · controlla email e rete"));});Button sync=add(box,"Sincronizza ora",()->{CloudSync.flush(this,true);status.setText(CloudSync.status(this));});Button devices=add(box,"Dispositivi collegati",()->CloudSync.devices(this,rows->{if(!isFinishing())new AlertDialog.Builder(this).setTitle("I tuoi dispositivi").setItems(rows.toArray(new String[0]),null).setPositiveButton("Chiudi",null).show();}));Button deviceName=add(box,"Nome di questo dispositivo",()->{EditText name=VodSettings.input(this,CloudSync.config(this).getString("deviceName",Build.MODEL),"Nome");new AlertDialog.Builder(this).setTitle("Nome del dispositivo").setView(name).setPositiveButton("Salva",(d,n)->{String value=name.getText().toString().trim();if(!value.isEmpty()&&value.length()<=80){CloudSync.config(this).edit().putString("deviceName",value).apply();CloudSync.updateDevice(this);}}).setNegativeButton("Annulla",null).show();});Button logout=add(box,"Esci dall’account su questo dispositivo",()->{CloudSync.flush(this,true);CloudSync.logout(this);password.setText("");status.setText(CloudSync.status(this));});Button importFile=add(box,"Configura cloud · importa file",()->{try{startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),10);}catch(ActivityNotFoundException e){pasteConfig();}});Button paste=add(box,"Configura cloud · incolla configurazione",this::pasteConfig);wire(back,email,password,login,merge,forgot,sync,devices,deviceName,logout,importFile,paste);email.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_NEXT){password.requestFocus();return true;}return false;});email.post(email::requestFocus);status.setText(CloudSync.status(this));}
 @Override protected void onResume(){super.onResume();ui.postDelayed(refresh,2000);}
 @Override protected void onPause(){ui.removeCallbacks(refresh);super.onPause();}
 private boolean move(KeyEvent e,int key,int up,View upView,int down,View downView){if(e.getAction()!=KeyEvent.ACTION_DOWN)return key==up||key==down;if(key==up){upView.requestFocus();return true;}if(key==down){downView.requestFocus();return true;}return false;}
 private void wire(View... views){for(int i=0;i<views.length;i++){View current=views[i],up=views[Math.max(0,i-1)],down=views[Math.min(views.length-1,i+1)];current.setNextFocusUpId(up.getId());current.setNextFocusDownId(down.getId());current.setOnKeyListener((v,key,e)->move(e,key,KeyEvent.KEYCODE_DPAD_UP,up,KeyEvent.KEYCODE_DPAD_DOWN,down));}}
 private Button add(LinearLayout box,String label,Runnable action){Button b=new Button(this);b.setId(View.generateViewId());b.setAllCaps(false);b.setText(label);UiTheme.navigation(b);box.addView(b,new LinearLayout.LayoutParams(-1,Math.round(52*getResources().getDisplayMetrics().density)));b.setOnClickListener(v->action.run());return b;}
 private void pasteConfig(){EditText value=new EditText(this);value.setTextColor(UiTheme.TEXT);value.setHint("Configurazione del progetto Firebase");new AlertDialog.Builder(this).setTitle("Collega il tuo progetto").setView(value).setPositiveButton("Salva",(d,n)->save(value.getText().toString())).setNegativeButton("Annulla",null).show();}
 private void save(String text){try{CloudSync.configure(this,text);status.setText("Cloud configurato · inserisci email e password");}catch(Exception e){status.setText(e.getMessage());}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==10&&result==RESULT_OK&&data!=null&&data.getData()!=null)try(InputStream in=getContentResolver().openInputStream(data.getData())){ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1){if(out.size()+n>256000)throw new IOException("File troppo grande");out.write(b,0,n);}save(out.toString("UTF-8"));}catch(Exception e){status.setText("Impossibile leggere la configurazione");}}
}
