package it.carmine.streamplayer;
import org.junit.*;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.annotation.Config;
import java.util.*;
import java.nio.file.*;
import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=35)
public class EventSourceTest {
    static final String FEED="\ufeffLAST UPDATE: 03-10-26\nSATURDAY\nHD1 ENGLISH\nHD6 SPANISH\nHD7 ITALIAN\n19:45 Spain x Czech Republic | https://test.example/hd/hd1.php\n19:45 Spain x Czech Republic | https://test.example/hd/hd6.php\n19:45 Spain x Czech Republic | https://test.example/hd/hd1.php\n19:45 Spain x Czech Republic | https://test.example/hd/hd7.php\n23:00 Late event | https://test.example/hd/hd1.php\n01:00 Roma x Milan | https://test.example/pt/sporttv1.php\nSUNDAY\nHD6 ARABIC\n19:45 Spain x Czech Republic | https://test.example/hd/hd6.php";
    @Test public void duplicatesGroupAndLanguagesFollowDayHeaders()throws Exception{EventSource.Snapshot data=EventSource.parse(FEED,EventSource.HOME,1791053100000L);assertEquals(4,data.events.size());assertEquals(3,data.events.get(0).sources.size());assertEquals("Spagnolo",data.events.get(0).sources.get(1).language);assertEquals("Arabo",data.events.get(3).sources.get(0).language);assertEquals("Portoghese",data.events.get(2).sources.get(0).language);}
    @Test public void lisbonScheduleConvertsAndOvernightRollsToNextDate()throws Exception{EventSource.Snapshot data=EventSource.parse(FEED,EventSource.HOME,1791053100000L);assertEquals(1791053100000L,data.events.get(0).start);Calendar calendar=Calendar.getInstance(TimeZone.getTimeZone("Europe/Rome"));calendar.setTimeInMillis(data.events.get(2).start);assertEquals(4,calendar.get(Calendar.DAY_OF_MONTH));assertEquals(2,calendar.get(Calendar.HOUR_OF_DAY));assertEquals(86400000L,data.events.get(3).start-data.events.get(0).start);}
    @Test public void filterSearchStateAndSportCombine()throws Exception{EventSource.Snapshot data=EventSource.parse(FEED,EventSource.HOME,1791053100000L);assertEquals(1,EventSource.filter(data,"Soccer","In diretta","SPAIN").size());assertEquals(1,EventSource.filter(data,"Soccer","Prossimi","ROMA").size());assertEquals(4,data.events.size());}
    @Test public void invalidFeedCannotReplaceCacheAndUnsafeUrlsRejected()throws Exception{for(String text:new String[]{"<html>Offline</html>","LAST UPDATE: 03-10-26\nSATURDAY"}){try{EventSource.parse(text,EventSource.HOME,0);fail();}catch(java.io.IOException expected){}}assertEquals("",EventSource.safeUrl("https://name:secret@test.example",EventSource.HOME));assertEquals("",EventSource.safeUrl("javascript:alert(1)",EventSource.HOME));}
    @Test public void actualScheduleHasGroupedSpainAndDailyLanguageAndBadges()throws Exception{String text=new String(Files.readAllBytes(Paths.get("tests/sports-schedule.txt")),"UTF-8");Map<String,String> logos=new HashMap<>();logos.put(EventSource.key("Spain"),"https://test.example/spain.png");EventSource.Snapshot snapshot=EventSource.parse(text,EventSource.HOME,0,TimeZone.getTimeZone("Europe/Lisbon"),logos);assertTrue(snapshot.events.size()>30);EventSource.Event spain=null;for(EventSource.Event e:snapshot.events)if(e.title.equals("Spain x Czech Republic")){spain=e;break;}assertNotNull(spain);assertEquals(3,spain.sources.size());assertEquals("https://test.example/spain.png",spain.homeBadge);assertEquals("Spagnolo",spain.sources.get(1).language);}
    @Test public void displayUsesItalianTimezoneEvenWhenDeviceIsOnUtc()throws Exception{TimeZone original=TimeZone.getDefault();try{TimeZone.setDefault(TimeZone.getTimeZone("UTC"));EventSource.Snapshot data=EventSource.parse(FEED,EventSource.HOME,1791053100000L);assertEquals("03/10 · 20:45",EventsActivity.italianTime(data.events.get(0).start,"dd/MM · HH:mm"));assertEquals("04/10 · 02:00",EventsActivity.italianTime(data.events.get(2).start,"dd/MM · HH:mm"));}finally{TimeZone.setDefault(original);}}
    @Test public void italianTimezoneAppliesWinterAndSummerOffsets(){assertEquals("15/01 13:00",EventsActivity.italianTime(java.time.Instant.parse("2026-01-15T12:00:00Z").toEpochMilli(),"dd/MM HH:mm"));assertEquals("15/07 14:00",EventsActivity.italianTime(java.time.Instant.parse("2026-07-15T12:00:00Z").toEpochMilli(),"dd/MM HH:mm"));}
}
