package it.carmine.streamplayer;
import android.app.*;import android.content.*;import java.util.concurrent.TimeUnit;import okhttp3.*;
/** Optional encrypted DNS, preserving TLS and normal access errors. */
final class LiveNetwork {
 private static OkHttpClient client;private static boolean configured;
 static boolean enabled(Context c){return c.getSharedPreferences("player",0).getBoolean("liveCloudflareDns",false);}
 static synchronized OkHttpClient client(Context c){boolean wanted=enabled(c);if(client==null||wanted!=configured){configured=wanted;client=VodNetwork.build(wanted,VodNetwork.television(c)).newBuilder().cookieJar(CookieJar.NO_COOKIES).followSslRedirects(true).callTimeout(0,TimeUnit.SECONDS).readTimeout(30,TimeUnit.SECONDS).build();}return client;}
 static GomstreamSource.Transport gom(Context context){Context app=context.getApplicationContext();return url->{String valid=GomstreamSource.https(url);Request request=new Request.Builder().url(valid).header("User-Agent","R-ITA-TV/1.25").header("Accept","*/*").build();try(Response response=client(app).newBuilder().callTimeout(30,TimeUnit.SECONDS).build().newCall(request).execute()){if(response.code()!=200)throw new java.io.IOException("HTTP "+response.code());if(response.body()==null)throw new java.io.IOException("Risposta vuota");try(java.io.InputStream in=response.body().byteStream();java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream()){byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(Thread.currentThread().isInterrupted())throw new java.io.InterruptedIOException();if(out.size()+n>8*1024*1024)throw new java.io.IOException("Pagina troppo grande");out.write(buffer,0,n);}return new GomstreamSource.Page(GomstreamSource.https(response.request().url().toString()),out.toString("UTF-8"));}}};}
 static void settings(Activity a,Runnable changed){new AlertDialog.Builder(a).setTitle("DNS dei canali Live").setSingleChoiceItems(new String[]{"DNS del dispositivo","Cloudflare HTTPS · ripiego sul DNS del dispositivo"},enabled(a)?1:0,(d,n)->{a.getSharedPreferences("player",0).edit().putBoolean("liveCloudflareDns",n==1).apply();d.dismiss();changed.run();}).setNegativeButton("Chiudi",null).show();}
}
