const fs=require('node:fs');const assert=require('node:assert/strict');
const {initializeTestEnvironment,assertSucceeds,assertFails}=require('@firebase/rules-unit-testing');
const {doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp}=require('firebase/firestore');
(async()=>{const env=await initializeTestEnvironment({projectId:'demo-rita-tv',firestore:{host:'127.0.0.1',port:8089,rules:fs.readFileSync('firestore.rules','utf8')}});let passed=0;const test=async(name,fn)=>{await fn();console.log('PASS '+name);passed++;};
try{await env.withSecurityRulesDisabled(async ctx=>{await setDoc(doc(ctx.firestore(),'owners/owner'),{enabled:true});await setDoc(doc(ctx.firestore(),'owners/disabled'),{enabled:false});});
const owner=env.authenticatedContext('owner').firestore(),stranger=env.authenticatedContext('stranger').firestore(),disabled=env.authenticatedContext('disabled').firestore(),anonymous=env.unauthenticatedContext().firestore();
const record=(revision=1,extra={})=>({key:'history:tmdb:84:s1e2',payload:JSON.stringify({title:{id:84},position:42000}),deleted:false,revision,device:'box-one',updatedAt:serverTimestamp(),...extra});
await test('owner creates progress',()=>assertSucceeds(setDoc(doc(owner,'users/owner/records/movie'),record())));
await test('anonymous cannot read',()=>assertFails(getDoc(doc(anonymous,'users/owner/records/movie'))));
await test('other account cannot read owner profile',()=>assertFails(getDoc(doc(stranger,'users/owner/records/movie'))));
await test('owner cannot write other UID',()=>assertFails(setDoc(doc(owner,'users/stranger/records/movie'),record())));
await test('non-whitelisted UID cannot create own records',()=>assertFails(setDoc(doc(stranger,'users/stranger/records/movie'),record())));
await test('disabled owner cannot write',()=>assertFails(setDoc(doc(disabled,'users/disabled/records/movie'),record())));
await test('owner document readable only by matching UID',async()=>{await assertSucceeds(getDoc(doc(owner,'owners/owner')));await assertFails(getDoc(doc(stranger,'owners/owner')));});
await test('client cannot grant owner privilege',()=>assertFails(setDoc(doc(stranger,'owners/stranger'),{enabled:true})));
await test('client cannot modify own privilege',()=>assertFails(updateDoc(doc(owner,'owners/owner'),{enabled:false})));
await test('new revision must be one',()=>assertFails(setDoc(doc(owner,'users/owner/records/new'),record(5))));
await test('stale revision cannot overwrite newer state',()=>assertFails(setDoc(doc(owner,'users/owner/records/movie'),record(1,{payload:'older-offline-state'}))));
await test('explicit reset to zero works with next revision',()=>assertSucceeds(setDoc(doc(owner,'users/owner/records/movie'),record(2,{payload:JSON.stringify({title:{id:84},position:0})}))));
await test('delete preserves tombstone',()=>assertSucceeds(setDoc(doc(owner,'users/owner/records/movie'),record(3,{deleted:true,payload:''}))));
await test('physical deletion forbidden',()=>assertFails(deleteDoc(doc(owner,'users/owner/records/movie'))));
await test('stale offline checkpoint cannot resurrect deletion',()=>assertFails(setDoc(doc(owner,'users/owner/records/movie'),record(2))));
await test('record identity cannot change',()=>assertFails(setDoc(doc(owner,'users/owner/records/movie'),record(4,{key:'fav:tmdb:100'}))));
await test('oversized payload rejected',()=>assertFails(setDoc(doc(owner,'users/owner/records/big'),record(1,{payload:'x'.repeat(200001)}))));
await test('unexpected fields rejected',()=>assertFails(setDoc(doc(owner,'users/owner/records/extra'),record(1,{password:'no'}))));
await test('invalid key rejected',()=>assertFails(setDoc(doc(owner,'users/owner/records/invalid'),record(1,{key:'owners/owner'}))));
await test('owner lists device metadata',()=>assertSucceeds(setDoc(doc(owner,'users/owner/devices/box-one'),{name:'TIM Box salotto',updatedAt:serverTimestamp()})));
await test('other UID cannot read device metadata',()=>assertFails(getDoc(doc(stranger,'users/owner/devices/box-one'))));
await test('device cannot include secret fields',()=>assertFails(setDoc(doc(owner,'users/owner/devices/box-two'),{name:'Tablet',updatedAt:serverTimestamp(),password:'no'})));
await env.withSecurityRulesDisabled(async ctx=>updateDoc(doc(ctx.firestore(),'owners/owner'),{enabled:false}));
await test('server disable blocks existing user reads',()=>assertFails(getDoc(doc(owner,'users/owner/records/movie'))));
console.log(passed+' security rule tests passed');assert.equal(passed,23);
}finally{await env.cleanup();}})().catch(err=>{console.error(err);process.exitCode=1;});
