package it.carmine.streamplayer;
import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import static org.junit.Assert.*;import org.json.*;import java.util.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class TmdbTest {
 JSONObject movie(long id,String name)throws Exception{return new JSONObject().put("id",id).put("media_type","movie").put("title",name).put("original_title",name).put("overview","Trama italiana").put("poster_path","/poster.jpg").put("release_date","2024-10-01");}
 @Test public void metadataMappingSeparatesMovieAndSeriesAndSkipsPeople()throws Exception{JSONObject m=movie(42,"Titolo"),tv=new JSONObject().put("id",42).put("media_type","tv").put("name","Serie");JSONObject p=new JSONObject().put("results",new JSONArray().put(m).put(tv).put(new JSONObject().put("id",1).put("media_type","person")));List<VodSource.Title> list=TmdbClient.parse(p,"");assertEquals(2,list.size());assertNotEquals(list.get(0).id,list.get(1).id);assertEquals("https://image.tmdb.org/t/p/w500/poster.jpg",list.get(0).poster);assertEquals("Trama italiana",list.get(0).plot);assertEquals("tmdb",TmdbClient.scope(list.get(0),new VodSettings.Source("one","one",VodSettings.DEFAULT)));}
 @Test public void tmdbUsesItalianLanguageAndCorrectPaginationAndSearchEndpoint()throws Exception{List<String> calls=new ArrayList<>();TmdbClient.catalog(0,"Titolo & altro",2,"test-key",(u,r)->{calls.add(u);return "{\"results\":[]}";});assertTrue(calls.get(0).startsWith("https://api.themoviedb.org/3/search/multi?"));assertTrue(calls.get(0).contains("query=Titolo+%26+altro"));assertTrue(calls.get(0).contains("language=it-IT"));assertTrue(calls.get(0).contains("page=2"));TmdbClient.catalog(1,"",3,"test-key",(u,r)->{calls.add(u);return "{\"results\":[]}";});assertTrue(calls.get(1).contains("/movie/popular?"));assertTrue(calls.get(1).contains("page=3"));}
 @Test public void providersRejectRemakesAndDifferentTypes()throws Exception{VodSource.Title wanted=TmdbClient.convert(movie(42,"Dune"),"movie");VodSource.Title remake=new VodSource.Title(new JSONObject().put("id",1).put("slug","dune").put("name","Dune").put("type","movie").put("tmdb_id",99),"");assertFalse(VodProviders.matches(wanted,remake));VodSource.Title correct=new VodSource.Title(new JSONObject().put("id",1).put("slug","dune").put("name","Dune").put("type","movie").put("tmdb_id",42),"");assertTrue(VodProviders.matches(wanted,correct));VodSource.Title series=new VodSource.Title(new JSONObject().put("id",1).put("slug","dune").put("name","Dune").put("type","tv").put("tmdb_id",42),"");assertFalse(VodProviders.matches(wanted,series));}
 @Test public void enrichmentKeepsProviderCatalogueIdentityAndAddsOnlyMetadata()throws Exception{VodSource.Title source=new VodSource.Title(new JSONObject().put("id",700).put("slug","titolo").put("name","Titolo").put("type","movie").put("release_date","2024-01-01").put("_poster_url","https://source/poster.jpg"),"");List<String> calls=new ArrayList<>();VodSource.Title enriched=TmdbClient.enrich(source,"key",(u,r)->{calls.add(u);return new JSONObject().put("results",new JSONArray().put(movie(42,"Titolo"))).toString();});assertEquals("700",enriched.id);assertEquals("/it/titles/700-titolo",enriched.path());assertEquals("Trama italiana",enriched.plot);assertEquals("https://image.tmdb.org/t/p/w500/poster.jpg",enriched.poster);assertEquals("tmdb",""+TmdbClient.scope(enriched,new VodSettings.Source("sc","SC",VodSettings.DEFAULT)));assertEquals("84",TmdbClient.identity(enriched));assertTrue(calls.get(0).contains("/search/movie?"));}
 @Test public void providerResultsKeepTheirPlaybackIdsAndMetadataSeparate()throws Exception{VodSource.Title wanted=TmdbClient.convert(movie(42,"Titolo"),"movie");VodSettings.Source source=new VodSettings.Source("primary","SC",VodSettings.DEFAULT);JSONObject actual=new JSONObject().put("id",700).put("slug","titolo").put("name","Titolo").put("type","movie").put("tmdb_id",42);VodProviders.Match match=VodProviders.search(source,wanted,(u,r)->u.contains("/search")?new JSONObject().put("titles",new JSONArray().put(actual)).toString():new JSONObject().put("title",actual).toString());assertNotNull(match.title);assertEquals("700",match.title.id);assertEquals(wanted.id,match.title.json.getJSONObject("_metadata").getString("id"));assertEquals(source.url,match.source.url);}
 @Test public void linkedHistoryKeepsProviderForResumeFromTmdbCatalogue()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();VodLibrary.prefs(c).edit().clear().commit();VodSource.Title wanted=TmdbClient.convert(movie(42,"Titolo"),"movie");VodSource.Title actual=new VodSource.Title(new JSONObject().put("id",700).put("slug","titolo").put("name","Titolo").put("_metadata",wanted.json),"");VodSettings.Source source=new VodSettings.Source("primary","SC",VodSettings.DEFAULT);VodLibrary.linkedProgress(c,source,actual,"","Titolo",120000,600000);JSONObject h=VodLibrary.latest(c,"tmdb",wanted.id);assertNotNull(h);assertEquals("primary",h.getJSONObject("provider").getString("id"));assertEquals("700",h.getJSONObject("providerTitle").getString("id"));assertEquals(120000,h.getLong("position"));}
}
