package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;
public class TvSearchActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private boolean destroyed;private EditText query;private TextView status;private ListView results;private JSONArray channels=new JSONArray();private EventSource.Snapshot events;private final List<Object> entries=new ArrayList<>();
 protected EventSource.Snapshot fetchEvents()throws Exception{return new EventSource(this).fetch();}
 @Override public void onCreate(Bundle state){super.onCreate(state);try{channels=new JSONArray(getIntent().getStringExtra("channels"));}catch(Exception ignored){}LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,16,24,12);root.setBackgroundColor(0xff151619);setContentView(root);Button back=new Button(this);back.setAllCaps(false);back.setText("‹ TV · Ricerca canali ed eventi");UiTheme.navigation(back);root.addView(back);back.setOnClickListener(v->finish());query=VodSettings.input(this,getIntent().getStringExtra("query"),"Cerca canali o eventi");query.setTag("tvSearchQuery");root.addView(query);status=new TextView(this);status.setTextColor(UiTheme.TEXT);root.addView(status);results=new ListView(this);results.setTag("tvSearchResults");root.addView(results,new LinearLayout.LayoutParams(-1,0,1));events=new EventSource(this).cached();query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int n,int after){}public void onTextChanged(CharSequence s,int st,int before,int n){filter();}public void afterTextChanged(Editable e){}});query.setOnEditorActionListener((v,a,e)->{results.requestFocus();return true;});results.setOnItemClickListener((p,v,n,id)->{Object entry=entries.get(n);if(entry instanceof JSONObject){setResult(RESULT_OK,new Intent().putExtra("channelKey",((JSONObject)entry).optString("key")));finish();}else{EventSource.Event event=(EventSource.Event)entry;String[] names=new String[event.sources.size()];for(int i=0;i<names.length;i++)names[i]=event.sources.get(i).description();new AlertDialog.Builder(this).setTitle(event.title).setItems(names,(d,index)->startActivity(new Intent(this,GeckoEventActivity.class).putExtra("url",event.sources.get(index).url).putExtra("title",event.title))).setNegativeButton("Chiudi",null).show();}});filter();worker.submit(()->{try{EventSource.Snapshot fetched=fetchEvents();runOnUiThread(()->{if(!destroyed){events=fetched;filter();}});}catch(Exception e){runOnUiThread(()->{if(!destroyed)status.setText(entries.size()+" risultati · eventi "+(events==null?"non disponibili":"salvati"));});}});}
 static boolean matches(String name,String needle){return EventSource.key(name).contains(EventSource.key(needle));}
 private void filter(){entries.clear();List<String> labels=new ArrayList<>();String needle=query.getText().toString().trim();for(int i=0;i<channels.length();i++){JSONObject c=channels.optJSONObject(i);if(c!=null&&matches(c.optString("name"),needle)){entries.add(c);labels.add("CANALE · "+DisplayNames.channel(c.optString("name")));}}if(events!=null)for(EventSource.Event event:EventSource.filter(events,"Tutti","Tutti",needle)){entries.add(event);java.text.SimpleDateFormat f=new java.text.SimpleDateFormat("dd/MM HH:mm",Locale.ITALIAN);f.setTimeZone(TimeZone.getTimeZone("Europe/Rome"));labels.add("EVENTO · "+event.title+" · "+f.format(new Date(event.start)));}results.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,labels){@Override public View getView(int n,View old,ViewGroup parent){TextView row=(TextView)super.getView(n,old,parent);row.setTextColor(UiTheme.TEXT);row.setTypeface(getResources().getFont(R.font.inter));row.setTextSize(17);return row;}});status.setText(entries.size()+" risultati · canali della fonte selezionata · "+(events==null?"aggiornamento eventi…":"eventi disponibili"));}
 @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}
