package it.carmine.streamplayer;
import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import androidx.media3.common.C;import androidx.media3.common.audio.AudioProcessor.AudioFormat;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import org.robolectric.android.controller.ActivityController;import java.nio.*;import java.util.*;import java.util.concurrent.atomic.*;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=31)
public class Version125Test {
 @Test public void vavooRenewsAtEightMinutesWithoutResolvingPlayingStream()throws Exception{AtomicInteger ping=new AtomicInteger(),resolve=new AtomicInteger();VavooClient client=new VavooClient("test",(url,data,sig)->{if(url.contains("/ping"))return new JSONObject().put("addonSig","session-"+ping.incrementAndGet());resolve.incrementAndGet();return new JSONObject().put("url","https://example.org/live.m3u8");});assertEquals(480000,VavooClient.RENEW_INTERVAL_MS);VavooClient.Channel channel=new VavooClient.Channel("Rai 1","Italy","123");client.resolve(channel);client.resolve(channel);assertEquals(1,ping.get());client.renewSession();assertEquals(2,ping.get());assertEquals(2,resolve.get());client.resolve(channel);assertEquals(2,ping.get());}
 public static class Live extends MainActivity {final AtomicInteger renewals=new AtomicInteger();protected boolean imagesEnabled(){return false;}protected void load(){}protected void loadEpg(boolean force){}protected VavooClient createClient(String id){return new VavooClient(id,(url,data,sig)->new JSONObject().put("addonSig","session-"+renewals.incrementAndGet()));}}
 @Test public void liveTimerRunsEveryEightMinutesAndStopsWhenPaused()throws Exception{RuntimeEnvironment.getApplication().getSharedPreferences("player",0).edit().clear().commit();try(ActivityController<Live> ctl=Robolectric.buildActivity(Live.class).setup()){Live a=ctl.get();Shadows.shadowOf(Looper.getMainLooper()).idleFor(java.time.Duration.ofMillis(479999));assertEquals(0,a.renewals.get());Shadows.shadowOf(Looper.getMainLooper()).idleFor(java.time.Duration.ofMillis(1));long deadline=System.currentTimeMillis()+1000;while(a.renewals.get()==0&&System.currentTimeMillis()<deadline)Thread.sleep(5);assertEquals(1,a.renewals.get());Shadows.shadowOf(Looper.getMainLooper()).idleFor(java.time.Duration.ofMinutes(8));deadline=System.currentTimeMillis()+1000;while(a.renewals.get()==1&&System.currentTimeMillis()<deadline)Thread.sleep(5);assertEquals(2,a.renewals.get());ctl.pause();Shadows.shadowOf(Looper.getMainLooper()).idleFor(java.time.Duration.ofMinutes(8));assertEquals(2,a.renewals.get());}}
 @Test public void audioDelayAddsSilenceAndNegativeDelaySkipsWholeFrames()throws Exception{AudioDelay delay=new AudioDelay(50);delay.configure(new AudioFormat(1000,2,C.ENCODING_PCM_16BIT));delay.flush();ByteBuffer input=ByteBuffer.allocateDirect(8).order(ByteOrder.nativeOrder());input.putLong(0x0102030405060708L).flip();delay.queueInput(input);ByteBuffer out=delay.getOutput();assertEquals(208,out.remaining());for(int i=0;i<200;i++)assertEquals(0,out.get());assertEquals(8,out.remaining());delay.set(-50);delay.flush();ByteBuffer first=ByteBuffer.allocateDirect(80);first.limit(80);delay.queueInput(first);assertEquals(0,delay.getOutput().remaining());ByteBuffer second=ByteBuffer.allocateDirect(160);second.limit(160);delay.queueInput(second);assertEquals(40,delay.getOutput().remaining());delay.set(10000);assertEquals(2000,delay.get());}
 @Test public void filtersOnlyUseProviderTitlesAndPaginationStaysOnSource()throws Exception{List<VodSource.Title> list=new ArrayList<>();list.add(new VodSource.Title(new JSONObject().put("id",1).put("name","One").put("release_date","2024-01-01").put("genre_ids",new JSONArray().put(28)),""));list.add(new VodSource.Title(new JSONObject().put("id",2).put("name","Two").put("release_date","2025-01-01").put("genre_ids",new JSONArray().put(35)),""));assertEquals("1",VodCatalogue.filter(list,"Azione","2024").get(0).id);assertTrue(VodCatalogue.filter(list,"Azione","2025").isEmpty());JSONObject props=new JSONObject().put("titles",new JSONObject().put("next_page_url","https://provider.example/it/movies?page=2"));assertEquals("/it/movies?page=2",VodCatalogue.next(props,"https://provider.example","/it/movies"));props.getJSONObject("titles").put("next_page_url","https://elsewhere.example/page");assertEquals("",VodCatalogue.next(props,"https://provider.example","/it/movies"));}
 @Test public void alternativesKeepManualSourcesButNeverTorrent()throws Exception{Context c=RuntimeEnvironment.getApplication();VodSettings.prefs(c).edit().clear().commit();List<VodSettings.Source> feed=VodSettings.parse("https://example.org\nhttps://1337x.to\nhttps://mytorrent.example\nhttps://streamingcommunityz.academy");assertEquals(2,feed.size());VodSettings.refresh(c,(u,r)->"https://example.org\nhttps://streamingunity.new");assertEquals(VodSettings.DEFAULT,VodSettings.sources(c).get(0).url);assertEquals(5,VodSettings.sources(c).size());assertEquals("vixsrc",VodSettings.sources(c).get(1).id);assertEquals("scuapi",VodSettings.sources(c).get(2).id);}
 @Test public void sourceFeedStopsAtLimitWithoutLosingMainSource()throws Exception{Context c=RuntimeEnvironment.getApplication();VodSettings.prefs(c).edit().clear().commit();StringBuilder feed=new StringBuilder();for(int i=0;i<40;i++)feed.append("https://provider-").append(i).append(".example\n");assertTrue(VodSettings.refresh(c,(u,r)->feed.toString()));assertEquals(40,VodSettings.sources(c).size());assertEquals(VodSettings.DEFAULT,VodSettings.sources(c).get(0).url);}
 @Test public void episodeBadgeNeedsProviderAvailabilityAndCompletedPreviousEpisode()throws Exception{Context c=RuntimeEnvironment.getApplication();c.getSharedPreferences("cloudConfig",0).edit().clear().commit();VodLibrary.prefs(c).edit().clear().commit();VodSettings.Source source=new VodSettings.Source("streamingcommunity","Community",VodSettings.DEFAULT);VodSource.Title meta=TmdbClient.convert(new JSONObject().put("id",99).put("name","Serie"),"tv");VodSource.Title title=new VodSource.Title(new JSONObject().put("id",700).put("name","Serie").put("type","tv").put("_metadata",meta.json).put("_seasonNumber",1).put("_episodeNumber",1),"");VodLibrary.linkedProgress(c,source,title,"1","S1 E1",590000,600000);assertFalse(VodCatalogue.newEpisode(c,title,source));title.json.put("_availableSeason",1).put("_availableEpisodes",new JSONArray().put(new JSONObject().put("id",2).put("number",2)));assertTrue(VodCatalogue.newEpisode(c,title,source));VodLibrary.linkedProgress(c,source,title,"1","S1 E1",42000,600000);assertFalse(VodCatalogue.newEpisode(c,title,source));}
 public static class Catalog extends VodCatalogueActivity {protected void load(boolean r){}protected boolean imagesEnabled(){return false;}}
 @Test public void backOpensAndClosesVodDrawer(){try(ActivityController<Catalog> ctl=Robolectric.buildActivity(Catalog.class).setup()){Catalog a=ctl.get();View drawer=a.getWindow().getDecorView().findViewWithTag("vodSidebar");assertEquals(View.GONE,drawer.getVisibility());a.onBackPressed();assertEquals(View.VISIBLE,drawer.getVisibility());assertFalse(a.isFinishing());a.onBackPressed();assertEquals(View.GONE,drawer.getVisibility());assertFalse(a.isFinishing());}}
 @Test public void loginRemoteMovesBetweenFields(){try(ActivityController<CloudActivity> ctl=Robolectric.buildActivity(CloudActivity.class).setup()){CloudActivity a=ctl.get();List<EditText> fields=new ArrayList<>();collect(a.getWindow().getDecorView(),fields);assertEquals(2,fields.size());EditText email=fields.get(0),password=fields.get(1);email.requestFocus();email.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_DOWN));assertTrue(password.hasFocus());password.dispatchKeyEvent(new KeyEvent(KeyEvent.ACTION_DOWN,KeyEvent.KEYCODE_DPAD_UP));assertTrue(email.hasFocus());}}
 private static void collect(View v,List<EditText> list){if(v instanceof EditText)list.add((EditText)v);if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)collect(((ViewGroup)v).getChildAt(i),list);}
}
