package it.carmine.streamplayer;

import org.json.*;import java.util.*;import java.util.concurrent.*;

/** VixSrc publishes availability as TMDB identifiers; TMDB supplies the visible metadata. */
final class VixCatalog {
 static final class Entry {final long id;final String type;Entry(long i,String t){id=i;type=t;}}
 static final class Page {final List<VodSource.Title> titles;final boolean more;Page(List<VodSource.Title> t,boolean m){titles=t;more=m;}}
 private static List<Entry> cached=new ArrayList<>();private static long cachedAt;private static String cachedHome="";
 static synchronized List<Entry> entries(String home,int mode,VodSource.Fetcher fetch)throws Exception{long now=System.currentTimeMillis();if(cached.isEmpty()||!home.equals(cachedHome)||now-cachedAt>10*60*1000){List<Entry> all=new ArrayList<>(),movies=parse(fetch.get(home+"/api/list/movie/?lang=it",home+"/"),"movie"),shows=parse(fetch.get(home+"/api/list/tv/?lang=it",home+"/"),"tv");int max=Math.max(movies.size(),shows.size());for(int i=0;i<max;i++){if(i<movies.size())all.add(movies.get(i));if(i<shows.size())all.add(shows.get(i));}cached=all;cachedAt=now;cachedHome=home;}List<Entry> out=new ArrayList<>();for(Entry e:cached)if(mode==0||mode==1&&e.type.equals("movie")||mode==2&&e.type.equals("tv"))out.add(e);return out;}
 static List<Entry> parse(String raw,String type)throws Exception{JSONArray a=new JSONArray(raw);LinkedHashSet<Long> ids=new LinkedHashSet<>();for(int i=0;i<a.length();i++){long id=a.optJSONObject(i)==null?0:a.optJSONObject(i).optLong("tmdb_id");if(id>0)ids.add(id);}List<Entry> out=new ArrayList<>();for(long id:ids)out.add(new Entry(id,type));return out;}
 static Page catalog(String home,int mode,String query,int page,String key,VodSource.Fetcher fetch)throws Exception{if(key==null||key.isEmpty())throw new IllegalStateException("Chiave TMDB non disponibile");List<Entry> available=entries(home,mode,fetch),selected=new ArrayList<>();boolean more=false;if(query!=null&&!query.isEmpty()){Set<String> allowed=new HashSet<>();for(Entry e:available)allowed.add(e.type+":"+e.id);int scan=Math.max(1,page);while(selected.size()<20&&scan<page+8){List<VodSource.Title> candidates=TmdbClient.catalog(mode,query,scan++,key,fetch);if(candidates.isEmpty())break;for(VodSource.Title t:candidates)if(allowed.contains((t.series()?"tv":"movie")+":"+VixSrc.tmdbId(t)))selected.add(new Entry(VixSrc.tmdbId(t),t.series()?"tv":"movie"));if(candidates.size()>=20)more=true;}}else{int from=Math.max(0,(Math.max(1,page)-1)*20),to=Math.min(available.size(),from+20);if(from<available.size())selected.addAll(available.subList(from,to));more=to<available.size();}return new Page(details(selected,key,fetch),more);}
 private static List<VodSource.Title> details(List<Entry> entries,String key,VodSource.Fetcher fetch)throws Exception{ExecutorService pool=Executors.newFixedThreadPool(4);try{List<Future<VodSource.Title>> jobs=new ArrayList<>();for(Entry e:entries)jobs.add(pool.submit(()->TmdbClient.details(e.id,e.type,key,fetch)));List<VodSource.Title> out=new ArrayList<>();for(Future<VodSource.Title> job:jobs)try{VodSource.Title title=job.get(12,TimeUnit.SECONDS);if(title!=null)out.add(title);}catch(Exception ignored){}return out;}finally{pool.shutdownNow();}}
}
