package it.carmine.streamplayer;
import android.content.Context;import org.json.*;import java.net.URI;import java.util.*;

/** Provider-only filtering, pagination and conservative episode availability. */
final class VodCatalogue {
 static String next(JSONObject props,String home,String current){JSONObject titles=props.optJSONObject("titles");if(titles==null)return "";String raw=titles.optString("next_page_url","");if(raw.equals("null")||raw.isEmpty())return "";try{URI uri=new URI(home+current).resolve(raw),base=new URI(home);if(!"https".equals(uri.getScheme())||!Objects.equals(base.getHost(),uri.getHost())||uri.getUserInfo()!=null)return "";String path=uri.getRawPath()+(uri.getRawQuery()==null?"":"?"+uri.getRawQuery());return path.equals(current)?"":path;}catch(Exception e){return "";}}
 static final Map<Integer,String> GENRES=new LinkedHashMap<>();static{GENRES.put(28,"Azione");GENRES.put(12,"Avventura");GENRES.put(16,"Animazione");GENRES.put(35,"Commedia");GENRES.put(80,"Crime");GENRES.put(99,"Documentario");GENRES.put(18,"Drammatico");GENRES.put(10751,"Famiglia");GENRES.put(14,"Fantasy");GENRES.put(36,"Storia");GENRES.put(27,"Horror");GENRES.put(10402,"Musica");GENRES.put(9648,"Mistero");GENRES.put(10749,"Romantico");GENRES.put(878,"Fantascienza");GENRES.put(53,"Thriller");GENRES.put(10752,"Guerra");GENRES.put(37,"Western");GENRES.put(10759,"Azione e avventura");GENRES.put(10765,"Fantascienza e fantasy");GENRES.put(10762,"Bambini");GENRES.put(10764,"Reality");GENRES.put(10767,"Talk show");}
 static Set<String> genres(VodSource.Title title){Set<String> names=new TreeSet<>();JSONObject j=title.json;JSONArray list=j.optJSONArray("genres");for(int i=0;list!=null&&i<list.length();i++){Object entry=list.opt(i);if(entry instanceof JSONObject){String n=((JSONObject)entry).optString("name");if(!n.isEmpty())names.add(n);}else if(entry instanceof String)names.add((String)entry);}JSONArray ids=j.optJSONArray("genre_ids");if(ids==null&&TmdbClient.metadata(title)!=null)ids=TmdbClient.metadata(title).optJSONArray("genre_ids");for(int i=0;ids!=null&&i<ids.length();i++){String n=GENRES.get(ids.optInt(i));if(n!=null)names.add(n);}return names;}
 static Set<String> genres(List<VodSource.Title> titles){Set<String> result=new TreeSet<>();for(VodSource.Title title:titles)result.addAll(genres(title));return result;}
 static List<VodSource.Title> filter(List<VodSource.Title> source,String genre,String year){List<VodSource.Title> result=new ArrayList<>();for(VodSource.Title title:source){String y=title.year;if(y.isEmpty()&&TmdbClient.metadata(title)!=null){String date=TmdbClient.metadata(title).optString("release_date");if(date.length()>=4)y=date.substring(0,4);}if((year.isEmpty()||year.equals(y))&&(genre.isEmpty()||genres(title).contains(genre)))result.add(title);}return result;}
 static List<VodSource.Title> filter(List<VodSource.Title> source,String genre,String year,boolean recent){List<VodSource.Title> result=filter(source,genre,year);if(!recent)result.sort((a,b)->a.name.compareToIgnoreCase(b.name));return result;}
 static boolean newEpisode(Context c,VodSource.Title title,VodSettings.Source source){if(!title.series()||source==null)return false;JSONObject history=VodLibrary.latest(c,TmdbClient.scope(title,source),TmdbClient.identity(title));if(history==null||!history.optBoolean("completed"))return false;JSONArray available=title.json.optJSONArray("_availableEpisodes");int season=title.json.optInt("_availableSeason");if(available==null||season!=history.optInt("seasonNumber"))return false;for(int i=0;i<available.length();i++){JSONObject episode=available.optJSONObject(i);if(episode!=null&&episode.optInt("number")>history.optInt("episodeNumber")&&!episode.optString("id").isEmpty())return true;}return false;}
}
