package it.carmine.streamplayer;
import android.content.Context;import android.util.AtomicFile;import org.json.*;import java.io.*;import java.security.*;import java.util.*;
final class VodCache {
 static String digest(String key){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(key.getBytes("UTF-8"));StringBuilder s=new StringBuilder();for(byte n:b)s.append(String.format(Locale.ROOT,"%02x",n&255));return s.toString();}catch(Exception e){throw new IllegalStateException(e);}}
 static String key(boolean tmdb,VodSettings.Source s,int mode,String query,int page){return (tmdb?"tmdb":s.id+"|"+s.url)+"|"+mode+"|"+query+"|"+page;}
 static AtomicFile file(Context c,String key){File dir=new File(c.getCacheDir(),"vodCatalog");dir.mkdirs();return new AtomicFile(new File(dir,digest(key)+".json"));}
 static List<VodSource.Title> read(Context c,String key){List<VodSource.Title> out=new ArrayList<>();try(InputStream in=file(c,key).openRead()){ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] buffer=new byte[8192];int n;while((n=in.read(buffer))!=-1){if(b.size()+n>2*1024*1024)return out;b.write(buffer,0,n);}JSONArray a=new JSONArray(b.toString("UTF-8"));for(int i=0;i<a.length();i++)out.add(new VodSource.Title(a.getJSONObject(i),""));}catch(Exception ignored){}return out;}
 static void save(Context c,String key,List<VodSource.Title> titles){try{JSONArray a=new JSONArray();for(VodSource.Title t:titles){JSONObject j=new JSONObject(t.json.toString());j.put("_poster_url",t.poster);a.put(j);}byte[] bytes=a.toString().getBytes("UTF-8");if(bytes.length>2*1024*1024)return;AtomicFile file=file(c,key);FileOutputStream output=null;try{output=file.startWrite();output.write(bytes);file.finishWrite(output);}catch(Exception e){if(output!=null)file.failWrite(output);}File[] files=file.getBaseFile().getParentFile().listFiles();if(files!=null&&files.length>32){Arrays.sort(files,Comparator.comparingLong(File::lastModified));for(int i=0;i<files.length-32;i++)files[i].delete();}}catch(Exception ignored){}}
}
