package it.carmine.streamplayer;
import android.view.*;import android.widget.*;import android.content.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import org.robolectric.android.controller.ActivityController;import static org.junit.Assert.*;import org.json.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35},qualifiers="w1280dp-h720dp-land-mdpi")
public class VodNavigationTest {
 public static class Home extends MainActivity {protected void load(){}protected void loadEpg(boolean f){}protected boolean imagesEnabled(){return false;}}
 public static class Catalog extends VodCatalogueActivity {protected void load(boolean refresh){}protected boolean imagesEnabled(){return false;}}
 public static class Player extends VodPlayerActivity {protected boolean engineEnabled(){return false;}}
 @Test public void homeVodIsAfterGuideAndOpensDedicatedSection(){try(ActivityController<Home> c=Robolectric.buildActivity(Home.class).setup()){ViewGroup nav=c.get().getWindow().getDecorView().findViewWithTag("homeNavigation");assertEquals(8,nav.getChildCount());assertEquals("navVod",nav.getChildAt(6).getTag());nav.getChildAt(6).performClick();Intent i=Shadows.shadowOf(c.get()).getNextStartedActivity();assertEquals(VodActivity.class.getName(),i.getComponent().getClassName());assertTrue(nav.getChildAt(6).isLongClickable());}}
 @Test public void catalogueHasNativePlayerActionAndVisibleGridSelector(){try(ActivityController<Catalog> c=Robolectric.buildActivity(Catalog.class).setup()){GridView grid=c.get().getWindow().getDecorView().findViewWithTag("vodGrid");Button play=c.get().getWindow().getDecorView().findViewWithTag("vodPlay");assertEquals(3,grid.getNumColumns());assertTrue(grid.isDrawSelectorOnTop());assertEquals(play.getId(),grid.getNextFocusRightId());assertEquals(grid.getId(),play.getNextFocusLeftId());assertFalse(play.isEnabled());}}
 @Test public void playerBackTogglesMenuWithoutLeavingPlayback()throws Exception{Intent i=new Intent().putExtra("source",new VodSettings.Source("streamingcommunity","Streaming Community",VodSettings.DEFAULT).json().toString()).putExtra("titleJson",new JSONObject().put("id",42).put("slug","movie").put("name","Movie").toString()).putExtra("episode","").putExtra("label","Movie").putExtra("episodes","[]");try(ActivityController<Player> c=Robolectric.buildActivity(Player.class,i).setup()){Player a=c.get();View menu=a.getWindow().getDecorView().findViewWithTag("vodPlayerMenu");assertEquals(View.GONE,menu.getVisibility());a.onBackPressed();assertEquals(View.VISIBLE,menu.getVisibility());assertFalse(a.isFinishing());a.onBackPressed();assertEquals(View.GONE,menu.getVisibility());assertFalse(a.isFinishing());}}
}
