package it.carmine.streamplayer;
import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import static org.junit.Assert.*;import java.net.*;import java.util.*;import java.util.concurrent.atomic.AtomicInteger;import javax.net.ssl.SSLHandshakeException;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class VodNetworkTest {
 @Test public void cloudflareDefaultAndSwitchPersists(){android.content.Context c=RuntimeEnvironment.getApplication();VodSettings.prefs(c).edit().clear().commit();assertTrue(VodNetwork.enabled(c));VodNetwork.initialize(c);assertTrue(VodNetwork.client().dns() instanceof VodNetwork.ShortCache);VodSettings.prefs(c).edit().putBoolean("cloudflareDns",false).commit();VodNetwork.initialize(c);assertSame(okhttp3.Dns.SYSTEM,VodNetwork.client().dns());VodSettings.prefs(c).edit().clear().commit();VodNetwork.initialize(c);}
 @Test public void cachesSuccessfulPublicLookupsAndDoesNotMaskFailure()throws Exception{AtomicInteger calls=new AtomicInteger();InetAddress address=InetAddress.getByAddress(new byte[]{10,2,3,4});VodNetwork.ShortCache dns=new VodNetwork.ShortCache(host->{calls.incrementAndGet();if(host.equals("bad.example"))throw new UnknownHostException(host);return Arrays.asList(address);});assertEquals(address,dns.lookup("video.example").get(0));dns.lookup("video.example");assertEquals(1,calls.get());for(int i=0;i<2;i++)try{dns.lookup("bad.example");fail();}catch(UnknownHostException expected){}assertEquals(3,calls.get());assertEquals("127.0.0.1",dns.lookup("127.0.0.1").get(0).getHostAddress());assertEquals(3,calls.get());}
 @Test public void errorLabelsDistinguishDnsHttpTlsTimeoutAndUnsupported(){assertEquals("DNS: dominio non risolto",VodNetwork.error(new java.io.IOException(new UnknownHostException())));assertEquals("Accesso rifiutato dal sito (HTTP 403)",VodNetwork.error(new VodNetwork.HttpError(403)));assertEquals("Il sito richiede accesso",VodNetwork.error(new VodNetwork.HttpError(401)));assertEquals("Connessione scaduta",VodNetwork.error(new SocketTimeoutException()));assertEquals("Errore connessione HTTPS",VodNetwork.error(new SSLHandshakeException("cert")));assertEquals("Formato del sito non compatibile",VodNetwork.error(new org.json.JSONException("missing")));}
 @Test public void providerErrorsPreserveHttpStatusAndDnsCause()throws Exception{VodSource.Title title=new VodSource.Title(new org.json.JSONObject().put("id",1).put("name","Film"),"");for(String type:new String[]{"web","streamingcommunity"}){VodSettings.Source source=new VodSettings.Source("s","Source","https://site.example",type);assertEquals("Sito risponde HTTP 404",VodProviders.search(source,title,(u,r)->{throw new VodNetwork.HttpError(404);}).note);assertEquals("Accesso rifiutato dal sito (HTTP 403)",VodProviders.search(source,title,(u,r)->{throw new VodNetwork.HttpError(403);}).note);assertEquals("DNS: dominio non risolto",VodProviders.search(source,title,(u,r)->{throw new UnknownHostException();}).note);}}
 @Test public void geckoUsesSameProviderAndExplicitSystemMode(){Map<String,Object> p=GeckoDns.prefs(true);assertEquals(VodNetwork.ENDPOINT,p.get("network.trr.uri"));assertEquals("1.1.1.1",p.get("network.trr.bootstrapAddr"));assertEquals(3,p.get("network.trr.mode"));assertEquals(5,GeckoDns.prefs(false).get("network.trr.mode"));}
 @Test public void tvTransportPrefersIpv4AndMetadataDoesNotWaitForCloudflare()throws Exception{InetAddress v6=InetAddress.getByAddress(new byte[16]),v4=InetAddress.getByAddress(new byte[]{1,2,3,4});VodNetwork.PreferIpv4 dns=new VodNetwork.PreferIpv4(h->Arrays.asList(v6,v4));assertEquals(v4,dns.lookup("example.org").get(0));assertEquals(v6,dns.lookup("example.org").get(1));VodNetwork.initialize(RuntimeEnvironment.getApplication());assertSame(okhttp3.Dns.SYSTEM,VodNetwork.transport(okhttp3.HttpUrl.get("https://api.themoviedb.org/3/trending/all/week")).dns());assertEquals(20000,VodNetwork.transport(okhttp3.HttpUrl.get("https://api.themoviedb.org/")).callTimeoutMillis());}
 @Test public void dnsResolutionHasDeadlineAndInterruptsBlockedWorker()throws Exception{java.util.concurrent.CountDownLatch interrupted=new java.util.concurrent.CountDownLatch(1);VodNetwork.BoundedDns dns=new VodNetwork.BoundedDns(h->{try{new java.util.concurrent.CountDownLatch(1).await();throw new AssertionError();}catch(InterruptedException e){interrupted.countDown();throw new UnknownHostException(h);}},50);long begin=System.nanoTime();try{dns.lookup("blocked.example");fail();}catch(UnknownHostException e){assertTrue(e.getCause() instanceof SocketTimeoutException);}assertTrue(java.util.concurrent.TimeUnit.NANOSECONDS.toMillis(System.nanoTime()-begin)<2000);assertTrue(interrupted.await(1,java.util.concurrent.TimeUnit.SECONDS));}
 @Test public void catalogueUserAgentLooksLikeAndroidChrome(){assertTrue(VodSource.USER_AGENT.contains("Mobile Safari"));assertFalse(VodSource.USER_AGENT.contains("; TV)"));}
}
