package it.carmine.streamplayer;
import java.util.*;import java.text.Normalizer;import org.json.*;

final class VodProviders {
 static final class Match {final VodSettings.Source source;final VodSource.Title title;final String note,page;final boolean nativeVideo;Match(VodSettings.Source s,VodSource.Title t,String n){this(s,t,n,"",s.nativeCatalog());}Match(VodSettings.Source s,VodSource.Title t,String n,String p,boolean v){source=s;title=t;note=n;page=p;nativeVideo=v;}}
 static String normal(String s){return Normalizer.normalize(s,Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]","");}
 static boolean matches(VodSource.Title wanted,VodSource.Title found){if(wanted.series()!=found.series())return false;JSONObject metadata=TmdbClient.metadata(wanted);long id=metadata==null?wanted.json.optLong("tmdb_id"):metadata.optLong("tmdb_id"),candidate=found.json.optLong("tmdb_id");if(id>0&&candidate>0)return id==candidate;String a=normal(wanted.name),b=normal(found.name),original=normal(metadata==null?wanted.json.optString("original_name"):metadata.optString("original_name"));return (a.equals(b)||(!original.isEmpty()&&original.equals(b)))&&(wanted.year.isEmpty()||found.year.isEmpty()||wanted.year.equals(found.year));}
 static Match search(VodSettings.Source s,VodSource.Title wanted,VodSource.Fetcher f){if(s.vixsrc())return VixSrc.match(s,wanted,f);if(s.scuapi())return ScuApi.search(s,wanted,f);if(!s.nativeCatalog())return VodWebSource.search(s,wanted,f);try{List<String> queries=new ArrayList<>();queries.add(wanted.name);JSONObject metadata=TmdbClient.metadata(wanted);String original=metadata==null?wanted.json.optString("original_name",""):metadata.optString("original_name","");if(!original.isEmpty()&&!normal(original).equals(normal(wanted.name)))queries.add(original);for(String q:queries){List<VodSource.Title> list=VodSource.catalog(VodSource.page(s.url,"/it/search?q="+VodSource.encode(q),f),s.url);int checked=0;for(VodSource.Title t:list){if(t.series()!=wanted.series())continue;if(!normal(t.name).equals(normal(wanted.name))&&!normal(t.name).equals(normal(original)))continue;if(++checked>4)break;VodSource.Title full=VodSource.title(VodSource.page(s.url,t.path(),f),s.url);if(matches(wanted,full)){JSONObject j=new JSONObject(full.json.toString());if(metadata!=null)j.put("_metadata",metadata);return new Match(s,new VodSource.Title(j,s.url.replace("https://","https://cdn.")),"Disponibile · "+full.json.optString("quality","player interno"));}}}return new Match(s,null,"Titolo non trovato");}catch(Exception e){return new Match(s,null,VodNetwork.error(e));}}
}
