package it.carmine.streamplayer;

import android.content.*;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import java.util.*;import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class) @Config(sdk=31)
public class Version129Test {
 @Before public void reset(){VodSettings.prefs(RuntimeEnvironment.getApplication()).edit().clear().commit();}
 @Test public void vixMovieResolvesShortLivedHlsForInternalPlayer()throws Exception{VodSettings.Source source=new VodSettings.Source("vixsrc","VixSrc","https://vixsrc.example","vixsrc");VodSource.Title title=new VodSource.Title(new JSONObject().put("id",84).put("slug","film").put("name","Film").put("tmdb_id",42).put("_tmdb",true),"");List<String> urls=new ArrayList<>();VodSource.Stream stream=VixSrc.resolve(source,title,"",(url,referer)->{urls.add(url);if(url.contains("/api/movie/42"))return "{\"src\":\"/embed/token\"}";if(url.endsWith("/embed/token"))return "window.masterPlaylist = { params: {'token':'abc','expires':'99','asn':''}, url:'https://vixsrc.example/playlist/42',\n }\n";return "#EXTM3U\n#EXT-X-VERSION:3";});assertTrue(urls.get(0).contains("/api/movie/42"));assertTrue(stream.url.contains("token=abc"));assertTrue(stream.url.contains("expires=99"));assertTrue(stream.url.contains("h=1"));assertTrue(stream.url.contains("lang=it"));}
 @Test public void vixEpisodeUsesTmdbSeasonAndEpisode()throws Exception{VodSettings.Source source=new VodSettings.Source("vixsrc","VixSrc","https://vixsrc.example","vixsrc");VodSource.Title title=new VodSource.Title(new JSONObject().put("id",85).put("slug","serie").put("name","Serie").put("type","tv").put("tmdb_id",7).put("_tmdb",true).put("_seasonNumber",3).put("_episodeNumber",4),"");List<String> urls=new ArrayList<>();VixSrc.resolve(source,title,"4",(url,referer)->{urls.add(url);if(url.contains("/api/tv/"))return "{\"src\":\"/embed/tv\"}";if(url.endsWith("/embed/tv"))return "window.masterPlaylist = { params: {'token':'t','expires':'e','asn':''}, url:'https://vixsrc.example/playlist/tv',\n }\n";return "#EXTM3U";});assertTrue(urls.get(0).contains("/api/tv/7/3/4"));}
 @Test public void scuApiReadsJsonDataSearch()throws Exception{String raw="{\"data\":[{\"id\":\"12\",\"slug\":\"film\",\"name\":\"Film\",\"type\":\"movie\"}]}";List<VodSource.Title> titles=ScuApi.results(raw,"https://streaming.example");assertEquals(1,titles.size());assertEquals("Film",titles.get(0).name);}
 @Test public void defaultsKeepCommunityThenVixThenScApi(){List<VodSettings.Source> list=VodSettings.sources(RuntimeEnvironment.getApplication());assertEquals("streamingcommunity",list.get(0).id);assertEquals("vixsrc",list.get(1).id);assertEquals("scuapi",list.get(2).id);assertEquals(list.get(0).url,list.get(2).url);}
 @Test public void cinesearchParsesMovieAndTvArrays()throws Exception{List<VodSource.Title> movie=CineSearch.parse("[{\"id\":10,\"title\":\"Movie\",\"media_type\":\"movie\",\"release_date\":\"2024-01-01\"}]","movie"),tv=CineSearch.parse("[{\"id\":11,\"name\":\"Show\",\"media_type\":\"tv\",\"first_air_date\":\"2023-01-01\"}]","tv");assertEquals("Movie",movie.get(0).name);assertFalse(movie.get(0).series());assertEquals("Show",tv.get(0).name);assertTrue(tv.get(0).series());}
 @Test public void cinesearchIsCatalogueNotPlaybackSource(){Context c=RuntimeEnvironment.getApplication();assertFalse(VodSettings.sources(c).stream().anyMatch(VodSettings.Source::cinesearch));assertTrue(VodSettings.catalogues(c).stream().anyMatch(VodSettings.Source::cinesearch));}
}
