package it.carmine.streamplayer;

import android.content.*;import android.view.*;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import java.io.*;import java.util.*;import static org.junit.Assert.*;

@RunWith(RobolectricTestRunner.class) @Config(sdk=31)
public class Version130Test {
 @Before public void reset(){VodSettings.prefs(RuntimeEnvironment.getApplication()).edit().clear().commit();VodSession.reset();}
 @Test public void definitiveDefaultsAreTmdbAndVixSrc(){Context c=RuntimeEnvironment.getApplication();assertEquals("tmdb",VodSettings.catalogue(c).id);assertEquals("vixsrc",VodSettings.primary(c).id);}
 @Test public void italianPlatformsAreAvailable(){assertEquals("Netflix",TmdbClient.PROVIDERS.get(8));assertEquals("Prime Video",TmdbClient.PROVIDERS.get(119));assertEquals("Disney+",TmdbClient.PROVIDERS.get(337));assertEquals("Apple TV+",TmdbClient.PROVIDERS.get(350));assertEquals("NOW",TmdbClient.PROVIDERS.get(39));}
 @Test public void providerDiscoveryUsesItalianRegion()throws Exception{List<String> urls=new ArrayList<>();TmdbClient.catalog(1,"",1,"key",(url,ref)->{urls.add(url);return "{\"results\":[]}";},8);assertTrue(urls.get(0).contains("watch_region=IT"));assertTrue(urls.get(0).contains("with_watch_providers=8"));}
 @Test public void platformViewCombinesMoviesAndSeries()throws Exception{List<String> urls=new ArrayList<>();List<VodSource.Title> titles=TmdbClient.catalog(0,"",1,"key",(url,ref)->{urls.add(url);return url.contains("/movie")?"{\"results\":[{\"id\":1,\"title\":\"Film\"}]}":"{\"results\":[{\"id\":2,\"name\":\"Serie\"}]}";},8);assertEquals(2,titles.size());assertTrue(urls.stream().anyMatch(u->u.contains("/discover/movie")));assertTrue(urls.stream().anyMatch(u->u.contains("/discover/tv")));}
 @Test public void tmdbKeepsBackdropForHero()throws Exception{VodSource.Title t=TmdbClient.convert(new JSONObject().put("id",7).put("media_type","movie").put("title","Film").put("backdrop_path","/wide.jpg"),"movie");assertTrue(t.json.getString("_backdrop_url").endsWith("/wide.jpg"));}
 @Test public void vodHomeHasHiddenSidebarAndCleanHero(){try(org.robolectric.android.controller.ActivityController<VodActivity> c=Robolectric.buildActivity(VodActivity.class).create()){View root=c.get().getWindow().getDecorView(),drawer=root.findViewWithTag("vodSidebar");assertNotNull(drawer);assertEquals(View.GONE,drawer.getVisibility());assertNotNull(root.findViewWithTag("vodHero"));assertNull(root.findViewWithTag("vodHeroWatch"));assertNull(root.findViewWithTag("vodHeroTrailer"));}}
 @Test public void vixRejectsExplicitNonItalianAudio()throws Exception{VodSettings.Source source=new VodSettings.Source("vixsrc","VixSrc","https://vixsrc.example","vixsrc");VodSource.Title title=new VodSource.Title(new JSONObject().put("id",84).put("name","Film").put("tmdb_id",42).put("_tmdb",true),"");try{VixSrc.resolve(source,title,"",(url,ref)->{if(url.contains("/api/movie/"))return "{\"src\":\"/embed/token\"}";if(url.endsWith("/embed/token"))return "window.masterPlaylist = { params: {'token':'abc','expires':'99','asn':''}, url:'https://vixsrc.example/playlist/42',\n }\n";return "#EXTM3U\n#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID=\"audio\",LANGUAGE=\"en\",NAME=\"English\"";});fail();}catch(IOException expected){assertTrue(expected.getMessage().contains("italiano"));}}
}
