package it.carmine.streamplayer;
import android.content.*;import android.widget.*;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import org.robolectric.android.controller.ActivityController;import java.util.*;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class VodEnhancementsTest {
 Context c;VodSource.Title title;
 @Before public void setup()throws Exception{c=RuntimeEnvironment.getApplication();c.getSharedPreferences("cloudConfig",0).edit().clear().commit();c.getSharedPreferences("vodLibrary",0).edit().clear().commit();title=TmdbClient.convert(new JSONObject().put("id",42).put("media_type","movie").put("title","Film"),"movie");}
 @Test public void watchlistIsSeparateAndRemovable(){VodLibrary.watchlist(c,"tmdb",title);assertTrue(VodLibrary.watchlisted(c,"tmdb",title.id));assertFalse(VodLibrary.favorite(c,"tmdb",title.id));assertEquals(1,VodLibrary.watchlistTitles(c,new VodSettings.Source("tmdb","TMDB","")).size());VodLibrary.watchlist(c,"tmdb",title);assertFalse(VodLibrary.watchlisted(c,"tmdb",title.id));}
 @Test public void historyShowsDurationCompletionAndExplicitRestart()throws Exception{VodLibrary.progress(c,"source",title,"","Film",120000,600000);JSONObject h=VodLibrary.latest(c,"source",title.id);assertEquals(20,VodLibrary.percent(h));assertEquals("2:00",VodLibrary.clock(h.getLong("position")));assertFalse(h.getBoolean("completed"));VodLibrary.progress(c,"source",title,"","Film",590000,600000);assertTrue(VodLibrary.latest(c,"source",title.id).getBoolean("completed"));VodLibrary.restart(c,"source",title,"");assertEquals(0,VodLibrary.position(c,"source",title.id,""));assertFalse(VodLibrary.latest(c,"source",title.id).getBoolean("completed"));VodLibrary.removeHistory(c,"source",title.id);assertNull(VodLibrary.latest(c,"source",title.id));}
 @Test public void differentProviderEpisodeIdsUseSameMetadataEpisode()throws Exception{VodSettings.Source s=new VodSettings.Source("streamingcommunity","Community",VodSettings.DEFAULT);VodSource.Title provider=new VodSource.Title(new JSONObject().put("id",700).put("name","Film").put("_metadata",title.json).put("_seasonNumber",2).put("_episodeNumber",3),"");VodLibrary.linkedProgress(c,s,provider,"local-id-a","S2 E3",42000,600000);assertTrue(VodLibrary.prefs(c).contains("history:tmdb:"+title.id+":s2e3"));VodLibrary.linkedProgress(c,s,provider,"local-id-b","S2 E3",55000,600000);assertEquals(55000,VodLibrary.latest(c,"tmdb",title.id).getLong("position"));assertEquals(1,VodLibrary.prefs(c).getAll().size());}
 @Test public void legacyEpisodeLabelMigratesToSeasonAndEpisodeIdentity()throws Exception{VodSource.Title provider=new VodSource.Title(new JSONObject().put("id",700).put("name","Film").put("_metadata",title.json),"");VodLibrary.linkedProgress(c,new VodSettings.Source("streamingcommunity","Community",VodSettings.DEFAULT),provider,"old-provider-id","S2 · E3 · Episodio",42000,600000);assertTrue(VodLibrary.prefs(c).contains("history:tmdb:"+title.id+":s2e3"));}
 @Test public void cachePreservesArtworkAndSeparatesQueriesAndProviders()throws Exception{VodSettings.Source s=new VodSettings.Source("community","Community",VodSettings.DEFAULT);String k=VodCache.key(true,s,0,"",1);title.json.put("_poster_url","https://image.example/poster.jpg");VodSource.Title image=new VodSource.Title(title.json,"");VodCache.save(c,k,Arrays.asList(image));List<VodSource.Title> cached=VodCache.read(c,k);assertEquals("https://image.example/poster.jpg",cached.get(0).poster);assertEquals(title.id,cached.get(0).id);assertNotEquals(k,VodCache.key(true,s,1,"",1));assertNotEquals(VodCache.key(false,s,0,"",1),VodCache.key(false,new VodSettings.Source("community","Community","https://changed.example"),0,"",1));}
 @Test public void staleOfflineRevisionCannotOverwriteRestartOrDeletion(){assertTrue(CloudRecords.canCommit(3,3));assertFalse(CloudRecords.canCommit(2,3));assertFalse(CloudRecords.canCommit(0,4));assertEquals("s2e3",CloudRecords.episodeKey(2,3,"different-id"));assertFalse(CloudRecords.payloadAllowed("history:tmdb:42:","{\"title\":{\"id\":42},\"position\":-1}"));assertFalse(CloudRecords.keyAllowed("../../owners/user"));}
 @Test public void cloudConfigurationRejectsWrongAndroidPackage()throws Exception{String raw="{\"project_info\":{\"project_id\":\"test-project\"},\"client\":[{\"client_info\":{\"mobilesdk_app_id\":\"1:42:android:abc\",\"android_client_info\":{\"package_name\":\"it.carmine.streamplayer\"}},\"api_key\":[{\"current_key\":\"public-config-key\"}]}]}";assertEquals("test-project",CloudSync.parseConfig(raw).getString("projectId"));try{CloudSync.parseConfig(raw.replace("it.carmine.streamplayer","wrong.package"));fail();}catch(Exception expected){}assertEquals("",CloudSync.uid(c));}
 @Test public void backupExcludesSecretsAndRestoresSettingsAndLibrary()throws Exception{c.getSharedPreferences("player",0).edit().putStringSet("favorites",new HashSet<>(Arrays.asList("Italy|Rai1"))).putInt("resize",4).putString("device_id","secret-id").commit();VodSettings.prefs(c).edit().putString("tmdbKey","secret-key").putBoolean("cloudflareDns",true).commit();c.getSharedPreferences("cloudConfig",0).edit().putString("device","secret-device").commit();VodLibrary.watchlist(c,"tmdb",title);String backup=SettingsBackup.export(c).toString();assertFalse(backup.contains("secret-"));assertFalse(backup.contains("cloudConfig"));assertFalse(backup.contains("tmdbKey"));c.getSharedPreferences("player",0).edit().remove("favorites").commit();VodLibrary.prefs(c).edit().clear().commit();SettingsBackup.restore(c,backup);assertTrue(c.getSharedPreferences("player",0).getStringSet("favorites",Collections.emptySet()).contains("Italy|Rai1"));assertTrue(VodLibrary.watchlisted(c,"tmdb",title.id));}
 @Test public void invalidBackupIsValidatedBeforeAnyMutation()throws Exception{JSONObject backup=SettingsBackup.export(c);backup.getJSONObject("settings").getJSONObject("player").put("category",new JSONObject().put("type","string").put("value","Cinema"));backup.getJSONObject("settings").getJSONObject("vod").put("tmdbKey",new JSONObject().put("type","string").put("value","illegal"));c.getSharedPreferences("player",0).edit().putString("category","Tutti").commit();try{SettingsBackup.restore(c,backup.toString());fail();}catch(Exception expected){}assertEquals("Tutti",c.getSharedPreferences("player",0).getString("category",""));}
 @Test public void fixedTmdbKeyIgnoresPreviousOverride(){String original=TmdbClient.key(c);VodSettings.prefs(c).edit().putString("tmdbKey","invalid-override").commit();assertEquals(original,TmdbClient.key(c));assertFalse(original.isEmpty());}
 public static class Catalog extends VodCatalogueActivity {int loads;protected void load(boolean refresh){loads++;}protected boolean imagesEnabled(){return false;}}
 @Test public void oldTopOptionsAreRemovedButWatchlistAndDrawerRemain(){try(ActivityController<Catalog> ctl=Robolectric.buildActivity(Catalog.class).setup()){assertNull(ctl.get().getWindow().getDecorView().findViewWithTag("vodTmdb"));assertNull(ctl.get().getWindow().getDecorView().findViewWithTag("vodOptions"));assertNotNull(ctl.get().getWindow().getDecorView().findViewWithTag("vodWatchlist"));assertEquals(android.view.View.GONE,ctl.get().getWindow().getDecorView().findViewWithTag("vodSidebar").getVisibility());}}
 @Test public void returningFromPlayerKeepsCatalogAndDoesNotFetchAgain()throws Exception{try(ActivityController<Catalog> ctl=Robolectric.buildActivity(Catalog.class).setup()){Catalog a=ctl.get();java.lang.reflect.Field source=VodCatalogueActivity.class.getDeclaredField("source"),items=VodCatalogueActivity.class.getDeclaredField("items");source.setAccessible(true);items.setAccessible(true);source.set(a,VodSettings.active(a));items.set(a,new ArrayList<>(Arrays.asList(title)));java.lang.reflect.Method render=VodCatalogueActivity.class.getDeclaredMethod("render"),show=VodCatalogueActivity.class.getDeclaredMethod("show",VodSource.Title.class);render.setAccessible(true);show.setAccessible(true);render.invoke(a);show.invoke(a,title);ctl.pause().resume();Shadows.shadowOf(android.os.Looper.getMainLooper()).idle();assertEquals(1,a.loads);GridView grid=a.getWindow().getDecorView().findViewWithTag("vodGrid");assertEquals(title.id,((VodSource.Title)grid.getAdapter().getItem(0)).id);}}
 public static class Search extends TvSearchActivity {}
 @Test public void televisionSearchReturnsOnlyChannels()throws Exception{Intent i=new Intent().putExtra("channels","[{\"name\":\"Rai Sport\",\"key\":\"Italy|Rai Sport\"}]").putExtra("query","Rai");try(ActivityController<Search> ctl=Robolectric.buildActivity(Search.class,i).setup()){ListView list=ctl.get().getWindow().getDecorView().findViewWithTag("tvSearchResults");assertEquals(1,list.getAdapter().getCount());list.performItemClick(null,0,0);assertEquals("Italy|Rai Sport",Shadows.shadowOf(ctl.get()).getResultIntent().getStringExtra("channelKey"));}}
 @Test public void televisionSearchNormalizesCaseAccentsAndPunctuation(){assertTrue(TvSearchActivity.matches("Rai Sport HD","RAI sport"));assertTrue(TvSearchActivity.matches("Milàn vs Roma","milan"));assertFalse(TvSearchActivity.matches("Rai 1","Roma"));}
}
