package it.carmine.streamplayer;
import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import org.robolectric.android.controller.ActivityController;import static org.junit.Assert.*;import android.os.Looper;import android.widget.*;import java.util.concurrent.*;import java.time.Duration;import java.lang.reflect.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class VodLoadingTest {
 static CountDownLatch feedEntered,feedRelease,catalogEntered,catalogRelease;static boolean holdCatalog,breakCompatibility;
 public static class Catalog extends VodCatalogueActivity {
  protected boolean imagesEnabled(){return false;}
  protected VodSource.Fetcher fetcher(){return (u,r)->{if(u.contains("pastebin.com")){feedEntered.countDown();feedRelease.await();return "https://streamingunity.fun";}if(u.contains("api.themoviedb.org"))return "{\"results\":[{\"id\":99,\"media_type\":\"movie\",\"title\":\"Film di prova\",\"overview\":\"Trama\",\"poster_path\":\"/poster.jpg\"}]}";catalogEntered.countDown();if(breakCompatibility)throw new NoSuchMethodError("API non disponibile");if(holdCatalog)catalogRelease.await();return "{\"titles\":[{\"id\":42,\"slug\":\"film-di-prova\",\"type\":\"movie\",\"name\":\"Film di prova\"}]}";};}
 }
 @Before public void reset(){VodSettings.prefs(RuntimeEnvironment.getApplication()).edit().clear().putString("catalogSource","streamingcommunity").commit();feedEntered=new CountDownLatch(1);feedRelease=new CountDownLatch(1);catalogEntered=new CountDownLatch(1);catalogRelease=new CountDownLatch(1);holdCatalog=false;breakCompatibility=false;}
 TextView status(Catalog a){return a.getWindow().getDecorView().findViewWithTag("vodStatus");}
 void waitLoaded(Catalog a)throws Exception{long end=System.currentTimeMillis()+3000;while(System.currentTimeMillis()<end){Shadows.shadowOf(Looper.getMainLooper()).idle();if(status(a).getText().toString().contains("1 titoli"))return;Thread.sleep(10);}fail(status(a).getText().toString());}
 @Test public void unreachableSourceListDoesNotBlockCommunityCatalog()throws Exception{try(ActivityController<Catalog> controller=Robolectric.buildActivity(Catalog.class).setup()){Catalog a=controller.get();assertTrue(feedEntered.await(2,TimeUnit.SECONDS));assertTrue(catalogEntered.await(2,TimeUnit.SECONDS));waitLoaded(a);assertEquals(1,feedRelease.getCount());GridView grid=a.getWindow().getDecorView().findViewWithTag("vodGrid");assertEquals(1,grid.getAdapter().getCount());}finally{feedRelease.countDown();catalogRelease.countDown();}}
 @Test public void deadlineEndsLoadingDiscardsLateResponseAndAllowsRetry()throws Exception{holdCatalog=true;try(ActivityController<Catalog> controller=Robolectric.buildActivity(Catalog.class).setup()){Catalog a=controller.get();assertTrue(catalogEntered.await(2,TimeUnit.SECONDS));Shadows.shadowOf(Looper.getMainLooper()).idleFor(Duration.ofSeconds(26));assertTrue(status(a).getText().toString().contains("tempo di attesa scaduto"));holdCatalog=false;catalogRelease.countDown();Thread.sleep(20);Shadows.shadowOf(Looper.getMainLooper()).idle();assertTrue(status(a).getText().toString().contains("tempo di attesa scaduto"));a.load(false);waitLoaded(a);}finally{feedRelease.countDown();catalogRelease.countDown();}}
 @Test public void compatibilityErrorDoesNotLeaveCatalogLoading()throws Exception{breakCompatibility=true;try(ActivityController<Catalog> controller=Robolectric.buildActivity(Catalog.class).setup()){Catalog a=controller.get();assertTrue(catalogEntered.await(2,TimeUnit.SECONDS));long end=System.currentTimeMillis()+2000;while(System.currentTimeMillis()<end){Shadows.shadowOf(Looper.getMainLooper()).idle();if(status(a).getText().toString().contains("compatibilità Android"))break;Thread.sleep(10);}assertTrue(status(a).getText().toString().contains("compatibilità Android"));}finally{feedRelease.countDown();catalogRelease.countDown();}}
 public static class OfflineCatalog extends VodCatalogueActivity {protected boolean imagesEnabled(){return false;}protected VodSource.Fetcher fetcher(){return (u,r)->{throw new java.io.IOException("Offline");};}}
 @Test public void savedCatalogAppearsImmediatelyAndSurvivesNetworkFailure()throws Exception{android.content.Context context=RuntimeEnvironment.getApplication();VodSettings.Source source=VodSettings.active(context);VodSource.Title title=new VodSource.Title(new org.json.JSONObject().put("id",999).put("slug","film-salvato").put("type","movie").put("name","Film salvato"),"");VodCache.save(context,VodCache.key(false,source,0,"",1),java.util.Arrays.asList(title));try(ActivityController<OfflineCatalog> ctl=Robolectric.buildActivity(OfflineCatalog.class).setup()){GridView grid=ctl.get().getWindow().getDecorView().findViewWithTag("vodGrid");assertEquals(1,grid.getAdapter().getCount());assertEquals("Film salvato",((VodSource.Title)grid.getAdapter().getItem(0)).name);Thread.sleep(30);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals(1,grid.getAdapter().getCount());}}
}
