package it.carmine.streamplayer;
import android.app.*;import android.view.*;import android.widget.*;import android.os.*;import android.graphics.*;import java.lang.reflect.*;import java.util.*;import java.util.concurrent.*;import java.io.*;import org.json.*;import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.*;import org.robolectric.android.controller.ActivityController;import static org.junit.Assert.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk=35,qualifiers="w1280dp-h720dp-land-mdpi") @GraphicsMode(GraphicsMode.Mode.NATIVE)
public class VodProvidersNavigationTest {
 static CountDownLatch started,release;
 public static class Catalog extends VodCatalogueActivity {
  protected void load(boolean refresh){}protected boolean imagesEnabled(){return false;}
  protected VodSource.Fetcher fetcher(){return (u,r)->{if(u.contains("/search")){started.countDown();if(!release.await(4,TimeUnit.SECONDS))throw new Exception("Timeout");return "{\"titles\":[{\"id\":700,\"slug\":\"titolo\",\"name\":\"Titolo\",\"type\":\"movie\"}]}";}return "{\"title\":{\"id\":700,\"slug\":\"titolo\",\"name\":\"Titolo\",\"type\":\"movie\",\"tmdb_id\":42}}";};}
 }
 void field(Object a,String n,Object v)throws Exception{Field f=VodCatalogueActivity.class.getDeclaredField(n);f.setAccessible(true);f.set(a,v);}
 @Test public void bothSourcesSearchAtOnceAndAvailableChoiceOpensNativePlayer()throws Exception{
  started=new CountDownLatch(2);release=new CountDownLatch(1);new android.app.Instrumentation().setInTouchMode(false);
  try(ActivityController<Catalog> c=Robolectric.buildActivity(Catalog.class).setup()){
   Catalog a=c.get();VodSettings.Source first=new VodSettings.Source("primary","Streaming Community · principale",VodSettings.DEFAULT),second=new VodSettings.Source("secondary","Streaming Community · alternativo","https://streamingcommunityz.academy");VodSettings.save(a,new ArrayList<>(Arrays.asList(first,second)));VodSettings.choose(a,first);field(a,"source",first);VodSource.Title wanted=TmdbClient.convert(new JSONObject().put("id",42).put("media_type","movie").put("title","Titolo").put("overview","Trama italiana"),"movie");Method find=VodCatalogueActivity.class.getDeclaredMethod("findSources",VodSource.Title.class,boolean.class);find.setAccessible(true);find.invoke(a,wanted,false);assertTrue("Entrambe le fonti devono iniziare senza aspettare l’altra",started.await(3,TimeUnit.SECONDS));release.countDown();AlertDialog d=org.robolectric.shadows.ShadowAlertDialog.getLatestAlertDialog();ListView list=d.getListView();long until=System.currentTimeMillis()+4000;while(System.currentTimeMillis()<until){Shadows.shadowOf(Looper.getMainLooper()).idle();if(list.getAdapter().getItem(0).toString().contains("Disponibile")&&list.getAdapter().getItem(1).toString().contains("Disponibile"))break;Thread.sleep(10);}assertTrue(list.getAdapter().getItem(0).toString().contains("Disponibile"));assertTrue(list.getAdapter().getItem(1).toString().contains("Disponibile"));list.performItemClick(list.getChildAt(0),0,0);android.content.Intent intent=Shadows.shadowOf(a).getNextStartedActivity();assertEquals(VodPlayerActivity.class.getName(),intent.getComponent().getClassName());assertEquals("700",new JSONObject(intent.getStringExtra("titleJson")).getString("id"));
  }finally{release.countDown();}
 }
 @Test public void gridAndProgrammeCardRenderWithinTvScreen()throws Exception{
  new android.app.Instrumentation().setInTouchMode(false);
  try(ActivityController<Catalog> c=Robolectric.buildActivity(Catalog.class).setup()){
   Catalog a=c.get();field(a,"source",new VodSettings.Source("primary","Streaming Community",VodSettings.DEFAULT));List<VodSource.Title> items=new ArrayList<>();for(int i=0;i<9;i++)items.add(new VodSource.Title(new JSONObject().put("id",100+i).put("slug","titolo-"+i).put("name",i==0?"Jurassic World":"Titolo "+i).put("plot","La scheda del film mostra la trama completa e permette di scegliere la fonte."),""));field(a,"items",items);Method render=VodCatalogueActivity.class.getDeclaredMethod("render");render.setAccessible(true);render.invoke(a);Method show=VodCatalogueActivity.class.getDeclaredMethod("show",VodSource.Title.class);show.setAccessible(true);show.invoke(a,items.get(0));View root=((ViewGroup)a.findViewById(android.R.id.content)).getChildAt(0);root.measure(View.MeasureSpec.makeMeasureSpec(1280,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(720,View.MeasureSpec.EXACTLY));root.layout(0,0,1280,720);GridView grid=root.findViewWithTag("vodGrid");assertTrue("Grid height="+grid.getHeight(),grid.getHeight()>400);Button play=root.findViewWithTag("vodPlay");assertTrue("Play enabled",play.isEnabled());assertTrue("Play focus",play.requestFocus());Bitmap bitmap=Bitmap.createBitmap(1280,720,Bitmap.Config.ARGB_8888);root.draw(new Canvas(bitmap));new File("build/previews").mkdirs();try(OutputStream out=new FileOutputStream("build/previews/vod-tv.png")){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();
  }
 }
}
