package it.carmine.streamplayer;
import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import static org.junit.Assert.*;import org.json.*;import java.nio.file.*;import java.util.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class VodSourceTest {
 String fixture(String name)throws Exception{return new String(Files.readAllBytes(Paths.get("tests/fixtures/vod-"+name+".json")),java.nio.charset.StandardCharsets.UTF_8);}
 @Before public void clear(){VodSettings.prefs(RuntimeEnvironment.getApplication()).edit().clear().commit();VodLibrary.prefs(RuntimeEnvironment.getApplication()).edit().clear().commit();}
 @Test public void currentHomeAndSearchProduceDistinctTitlesAndPosters()throws Exception{List<VodSource.Title> home=VodSource.catalog(new JSONObject(fixture("home")),VodSettings.DEFAULT);assertTrue(home.size()>10);Set<String> ids=new HashSet<>();for(VodSource.Title t:home){assertTrue(ids.add(t.id));assertTrue(t.poster.startsWith("https://cdn."));}List<VodSource.Title> search=VodSource.catalog(new JSONObject(fixture("search")),VodSettings.DEFAULT);assertTrue(search.stream().anyMatch(t->t.name.equals("Avatar")));}
 @Test public void htmlEntitiesAndCurrentSeasonDataAreParsed()throws Exception{JSONObject p=new JSONObject(fixture("series"));String escaped=new JSONObject().put("props",p).toString().replace("&","&amp;").replace("\"","&quot;");JSONObject decoded=VodSource.props("<div data-page=\""+escaped+"\"></div>");VodSource.Title t=VodSource.title(decoded,VodSettings.DEFAULT);assertTrue(t.series());assertTrue(t.json.getJSONArray("seasons").length()>=2);assertTrue(decoded.getJSONObject("loadedSeason").getJSONArray("episodes").length()>0);}
 String embed(){return "window.masterPlaylist = {\n params: {\n 'token': 'fresh-token',\n 'expires': '12345',\n 'asn': '',\n },\n url: 'https://video.example/playlist/42?b=1',\n }\n window.canPlayFHD = false";}
 @Test public void playlistReadsOuterObjectAndKeepsExistingParameters()throws Exception{String u=VodSource.playlist(embed());assertEquals("https://video.example/playlist/42?b=1&token=fresh-token&expires=12345",u);}
 @Test public void resolverUsesWatchPageWithoutUnknownCacheBusters()throws Exception{List<String> calls=new ArrayList<>();VodSource.Stream stream=VodSource.resolve(VodSettings.DEFAULT,"42","123",(u,r)->{calls.add(u);if(u.contains("/watch/"))return new JSONObject().put("props",new JSONObject().put("embedUrl",VodSettings.DEFAULT+"/it/iframe/42?e=123")).toString();if(u.contains("/iframe/"))return "<iframe src=\"https://video.example/embed/42?token=current&amp;e=123\"></iframe>";if(u.contains("/embed/"))return embed();return "#EXTM3U\n";});assertEquals(4,calls.size());assertEquals(VodSettings.DEFAULT+"/it/watch/42?e=123",calls.get(0));assertEquals(VodSettings.DEFAULT+"/it/iframe/42?e=123",calls.get(1));assertFalse(calls.get(0).contains("_rita"));assertEquals("https://video.example/embed/42?token=current&e=123",calls.get(2));assertTrue(stream.url.contains("fresh-token"));}
 @Test public void plainListAddsBackupsAndPreservesUsersPrimaryLink()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();VodSettings.refresh(c,(u,r)->"https://streamingcommunityz.academy\nhttps://example.org\nhttps://streamingunity.fun\n");assertEquals(VodSettings.DEFAULT,VodSettings.active(c).url);assertEquals(5,VodSettings.sources(c).size());VodSettings.refresh(c,(u,r)->"https://streamingunity.new\nhttps://other.example\n");assertEquals(6,VodSettings.sources(c).size());assertEquals(VodSettings.DEFAULT,VodSettings.active(c).url);VodSettings.Source unity=VodSettings.sources(c).stream().filter(x->VodSettings.unity(x.url)).findFirst().get();assertEquals("https://streamingunity.new",unity.url);assertTrue(unity.nativeCatalog());}
 @Test public void savedBackupSourcesAndUnityProgressIdentifierArePreserved()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();VodSettings.prefs(c).edit().putString("sources",VodSettings.serialized(Arrays.asList(new VodSettings.Source("streamingcommunity","Streaming Community",VodSettings.DEFAULT),new VodSettings.Source("list_streamingunity_fun","streamingunity.fun","https://streamingunity.fun"),new VodSettings.Source("example_org","Other","https://example.org","web"),new VodSettings.Source("list_streamingcommunity","SC alternative","https://streamingcommunityz.academy")))).putString("active","example_org").commit();List<VodSettings.Source> list=VodSettings.sources(c);assertEquals(6,list.size());assertEquals("vixsrc",list.get(1).id);assertEquals("scuapi",list.get(2).id);assertTrue(list.stream().anyMatch(x->x.id.equals("list_streamingunity_fun")));assertEquals(VodSettings.DEFAULT,list.get(0).url);assertTrue(VodSettings.prefs(c).getString("sources","").contains("example.org"));assertEquals("example_org",VodSettings.active(c).id);}
 @Test public void manualUnityUrlAndEmptyFeedAreRespected()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();List<VodSettings.Source> list=VodSettings.sources(c);int unity=-1;for(int i=0;i<list.size();i++)if(VodSettings.unity(list.get(i).url))unity=i;assertTrue(unity>=0);VodSettings.Source old=list.get(unity);list.set(unity,new VodSettings.Source(old.id,"StreamingUnity","https://manual.example"));VodSettings.save(c,list);VodSettings.prefs(c).edit().putBoolean("unityManual",true).commit();VodSettings.refresh(c,(u,r)->"https://streamingunity.new\nhttps://example.org");assertTrue(VodSettings.sources(c).stream().anyMatch(x->x.url.equals("https://manual.example")));VodSettings.prefs(c).edit().putString("feed","").commit();assertFalse(VodSettings.refresh(c,(u,r)->{throw new AssertionError("Feed disabled");}));assertEquals(5,VodSettings.sources(c).size());}
 @Test public void unsupportedSourcesRemainExplicitWebEntriesAndInvalidListsDoNotReplaceSources()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();List<VodSettings.Source> s=VodSettings.parse("https://example.org\nhttps://streamingcommunityz.promo");assertFalse(s.get(0).nativeCatalog());assertTrue(s.get(1).nativeCatalog());try{VodSettings.refresh(c,(u,r)->"not-a-url");fail();}catch(Exception expected){}assertEquals(VodSettings.DEFAULT,VodSettings.active(c).url);}
 @Test public void progressIsPerSourceAndEpisodeAndSurvivesDomainChanges()throws Exception{android.content.Context c=RuntimeEnvironment.getApplication();VodSource.Title t=new VodSource.Title(new JSONObject().put("id",42).put("slug","movie").put("name","Movie"),"https://cdn.example");VodLibrary.progress(c,"first",t,"1","E1",120000,600000);VodLibrary.progress(c,"first",t,"2","E2",250000,600000);assertEquals(120000,VodLibrary.position(c,"first","42","1"));assertEquals(250000,VodLibrary.position(c,"first","42","2"));assertEquals(0,VodLibrary.position(c,"second","42","1"));VodLibrary.favorite(c,"first",t);assertTrue(VodLibrary.favorite(c,"first","42"));VodLibrary.favorite(c,"first",t);assertFalse(VodLibrary.favorite(c,"first","42"));}
}
