package it.carmine.streamplayer;
import org.junit.*;import org.junit.runner.RunWith;import org.robolectric.*;import org.robolectric.annotation.Config;import static org.junit.Assert.*;import org.json.*;import java.util.*;
@RunWith(RobolectricTestRunner.class) @Config(sdk={31,35})
public class VodWebSourceTest {
 VodSource.Title wanted()throws Exception{return new VodSource.Title(new JSONObject().put("id",42).put("name","Titolo del film").put("type","movie"),"");}
 @Test public void formSearchSupportsWordpressDleAndAnimeFields()throws Exception{assertEquals("https://new.example/?s=Titolo+del+film",VodWebSource.searchUrl("https://old.example","<form action='https://new.example/'><input name='s' type='search'></form>","Titolo del film"));assertEquals("https://site.example/index.php?do=search&subaction=search&story=Titolo",VodWebSource.searchUrl("https://site.example","<form action='/index.php'><input name='story'><input type='hidden' name='do' value='search'><input type='hidden' name='subaction' value='search'></form>","Titolo"));assertEquals("https://anime.example/search?keyword=Titolo",VodWebSource.searchUrl("https://anime.example","<form action='/search'><input name='keyword'></form>","Titolo"));}
 @Test public void titleLinksMustMatchLabelAndRemainOnTheSearchedSite()throws Exception{String html="<a href='https://ads.example/title'>Titolo del film</a><a href='/login'>Titolo del film</a><a href='/movie/42' title='Titolo del film'><img alt='Titolo del film'></a>";assertEquals("https://site.example/movie/42",VodWebSource.titlePage(html,"https://site.example/?s=Titolo",wanted()));assertEquals("",VodWebSource.titlePage("<a href='/movie/43'>Un altro film</a>","https://site.example/",wanted()));}
 @Test public void directHlsIsVerifiedAndIframeLookupIsBounded()throws Exception{VodSource.Stream stream=VodWebSource.resolve("https://site.example/movie/42",(u,r)->{if(u.contains("/movie/"))return "<iframe src='https://video.example/embed/42'></iframe>";if(u.contains("/embed/"))return "<script>file: 'https://cdn.example/video.m3u8?token=current'</script>";return "#EXTM3U\n";});assertEquals("https://cdn.example/video.m3u8?token=current",stream.url);List<String> calls=new ArrayList<>();try{VodWebSource.resolve("https://site.example/movie/42",(u,r)->{calls.add(u);return "<iframe src='/loop/"+calls.size()+"'></iframe>";});fail();}catch(Exception expected){}assertEquals(5,calls.size());}
 @Test public void plainListDropsTorrentSitesWithoutDroppingVideoSites()throws Exception{List<VodSettings.Source> list=VodSettings.parse("https://1337x.to\nhttps://rargb.to\nhttps://streamingunity.fun\nhttps://streamingcommunityz.academy\nhttps://anime.example\n");assertEquals(3,list.size());assertTrue(list.get(0).nativeCatalog());assertTrue(list.get(1).nativeCatalog());assertFalse(list.get(2).nativeCatalog());}
 @Test public void webSearchReturnsNativeSourceOnlyAfterPlaylistCheck()throws Exception{VodSettings.Source source=new VodSettings.Source("web","Site","https://site.example","web");VodProviders.Match m=VodWebSource.search(source,wanted(),(u,r)->{if(u.contains("?s="))return "<a href='/movie/42'>Titolo del film</a>";if(u.contains("/movie/42"))return "<video><source src='https://cdn.example/video.m3u8'></video>";if(u.contains(".m3u8"))return "#EXTM3U\n";return "<form action='/'><input name='s'></form>"+String.join("",Collections.nCopies(100,"padding"));});assertNotNull(m.title);assertTrue(m.nativeVideo);assertEquals("https://site.example/movie/42",m.page);assertTrue(m.title.json.has("_web_page"));}
 @Test public void pageWithoutDirectVideoRemainsExplicitGeckoChoice()throws Exception{VodProviders.Match m=VodWebSource.search(new VodSettings.Source("web","Site","https://site.example","web"),wanted(),(u,r)->{if(u.contains("?s="))return "<a href='/movie/42'>Titolo del film</a>";if(u.contains("/movie/"))return "<p>Player JavaScript</p>";return "<form action='/'><input name='s'></form>"+String.join("",Collections.nCopies(100,"padding"));});assertNotNull(m.title);assertFalse(m.nativeVideo);assertTrue(m.note.contains("Gecko"));}
}
