package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.widget.*;import java.io.*;
public class BackupActivity extends Activity {
 private TextView status;
 @Override public void onCreate(Bundle state){super.onCreate(state);LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(24,18,24,18);box.setBackgroundColor(0xff151619);setContentView(box);add(box,"‹ Torna",this::finish);status=new TextView(this);status.setTextColor(UiTheme.TEXT);status.setTextSize(17);status.setText("Salva URL, preferiti, Da vedere, cronologia e preferenze del player. Password e accesso cloud non vengono esportati.");box.addView(status);add(box,"Esporta backup",()->picker(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"R-ITA-TV-backup.json"),10));add(box,"Importa backup",()->picker(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),11));TextView abi=new TextView(this);abi.setTextColor(UiTheme.TEXT);abi.setText("Architetture compatibili: "+android.text.TextUtils.join(", ",Build.SUPPORTED_ABIS));box.addView(abi);}
 private void add(LinearLayout box,String label,Runnable action){Button b=new Button(this);b.setAllCaps(false);b.setText(label);UiTheme.navigation(b);box.addView(b,new LinearLayout.LayoutParams(-1,Math.round(52*getResources().getDisplayMetrics().density)));b.setOnClickListener(v->action.run());}
 private void picker(Intent intent,int code){try{startActivityForResult(intent,code);}catch(ActivityNotFoundException e){status.setText("Su questo dispositivo manca un selettore file. Installa un gestore file compatibile per esportare o importare.");}}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{if(request==10){byte[] bytes=SettingsBackup.export(this).toString(2).getBytes("UTF-8");try(OutputStream out=getContentResolver().openOutputStream(data.getData())){if(out==null)throw new IOException();out.write(bytes);}status.setText("Backup esportato");}else if(request==11){try(InputStream in=getContentResolver().openInputStream(data.getData())){if(in==null)throw new IOException();ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>2*1024*1024)throw new IOException("Backup troppo grande");out.write(b,0,n);}SettingsBackup.restore(this,out.toString("UTF-8"));}status.setText("Backup ripristinato · le impostazioni saranno ricaricate tornando alla TV");}}catch(Exception e){status.setText("Operazione non riuscita · "+e.getMessage());}}
}
