package it.carmine.streamplayer;
import android.app.Activity;import android.os.*;import android.webkit.*;import android.widget.FrameLayout;import java.util.*;import org.json.*;
/** Reads film and series entry points without replacing the native catalogue UI. */
final class CbCatalogLoader {
 interface Callback {void done(List<VodSource.Title> titles,String error);}
 private final Activity activity;private final WebView web;private final Handler ui=new Handler(Looper.getMainLooper());private boolean closed;private String script;private Callback callback;private String query="";private final LinkedHashMap<String,VodSource.Title> titles=new LinkedHashMap<>();private final ArrayDeque<String> pages=new ArrayDeque<>();private final Set<String> visited=new HashSet<>();private int scans;private String forcedType="";
 CbCatalogLoader(Activity a,FrameLayout root){activity=a;web=new WebView(a);web.setAlpha(0);web.setFocusable(false);root.addView(web,new FrameLayout.LayoutParams(1,1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setUserAgentString(CbMixdropResolver.USER_AGENT);s.setSupportMultipleWindows(false);s.setJavaScriptCanOpenWindowsAutomatically(false);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !supported(r.getUrl().toString());}});try(java.io.InputStream in=a.getAssets().open("cb01-catalog.js")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[4096];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);script=out.toString("UTF-8");}catch(Exception e){script="(function(){return '[]'})";}}
 void load(VodSettings.Source source,String q,Callback cb){callback=cb;query=q.startsWith("@@")?"":q;pages.add(source.url.replaceAll("/+$","")+"/"+(query.isEmpty()?"":"?s="+VodSource.encode(query)));next();}
 private void next(){if(closed)return;String page=pages.poll();if(page==null||scans>=4){callback.done(new ArrayList<>(titles.values()),titles.isEmpty()?"CB01 · nessun titolo trovato o sito non raggiungibile":"");close();return;}if(!visited.add(page)){next();return;}scans++;forcedType=page.toLowerCase(Locale.ROOT).matches(".*(?:serie|serial).*" )?"tv":"";web.loadUrl(page);ui.postDelayed(()->{if(query.isEmpty())poll(0);else submit(0);},1300);}
 private void submit(int attempt){if(closed)return;web.evaluateJavascript(VodWebSearchScript.submit(JSONObject.quote(query)),raw->{if(closed)return;if("true".equals(raw))ui.postDelayed(()->poll(0),1700);else if(attempt<5)ui.postDelayed(()->submit(attempt+1),700);else poll(0);});}
 private void poll(int attempt){if(closed)return;web.evaluateJavascript(script+"("+JSONObject.quote(query)+")",raw->{if(closed)return;int count=0;try{JSONArray cards=new JSONArray(new JSONArray("["+raw+"]").getString(0));count=cards.length();for(int i=0;i<count;i++){JSONObject c=cards.getJSONObject(i);String url=c.getString("url");JSONObject j=new JSONObject().put("id",String.valueOf(Integer.toUnsignedLong(url.hashCode()))).put("slug","cb01").put("name",c.getString("title")).put("type",forcedType.isEmpty()?c.optString("type","movie"):forcedType).put("_poster_url",c.optString("image")).put("_web_page",url);titles.putIfAbsent(url,new VodSource.Title(j,""));}}catch(Exception ignored){}if(count==0&&attempt<15){ui.postDelayed(()->poll(attempt+1),800);return;}web.evaluateJavascript("JSON.stringify(Array.from(document.querySelectorAll('a[href]')).filter(a=>/serie[ -]?tv|serial/i.test(a.textContent+' '+a.href)&&!a.querySelector('img')).map(a=>a.href))",links->{if(closed)return;try{JSONArray found=new JSONArray(new JSONArray("["+links+"]").getString(0));for(int i=0;i<found.length();i++){String url=found.getString(i);if(!supported(url)||visited.contains(url))continue;String base=url.split("[?#]")[0];if(!query.isEmpty())base=base.replaceAll("/+$","")+"/?s="+VodSource.encode(query);if(!pages.contains(base))pages.add(base);if(pages.size()>=3)break;}}catch(Exception ignored){}next();});});}
 private static boolean supported(String url){try{String h=new java.net.URI(url).getHost();return h!=null&&WebMovieLinks.supported("https://"+h.replaceFirst("^(?:www|serie|serietv|series)\\.",""));}catch(Exception e){return false;}}
 void close(){if(closed)return;closed=true;ui.removeCallbacksAndMessages(null);web.stopLoading();if(web.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)web.getParent()).removeView(web);web.destroy();}
}
