package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.graphics.Color;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;
import java.net.URI;import java.util.*;import java.util.concurrent.*;import java.util.regex.*;import org.json.*;import okhttp3.*;

public final class CbCatalogueActivity extends Activity {
 private JSONObject movieJson;private VodSettings.Source cbSource;private String catalogAtOpen;
 private volatile String resolverTarget="";private String mixdropScript;private Button activeSource;private String activeName="";private boolean listing;private JSONArray cachedCards;private final LinkedHashMap<String,Button> sourceRows=new LinkedHashMap<>();private final ExecutorService images=Executors.newFixedThreadPool(3);private String redirectScript,catalogScript,playScript,lastStage="";private long playerSince;private boolean touched;private final ArrayDeque<String> alternatives=new ArrayDeque<>();private LinearLayout results;private boolean searching;private int playerHops;private final Set<String> visited=new HashSet<>();private WebView web;private EditText domain,query;private TextView status;private Spinner site;
 private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService worker=Executors.newFixedThreadPool(2);
 private final Set<String> seen=Collections.synchronizedSet(new HashSet<>());
 private volatile boolean probing,destroyed,opening;private boolean pageError;private volatile int generation;private String filmPage="",lastOutcome="Pronto",userAgent=CbTransport.UA;
 private final String[] homes={"https://cb01uno.wiki/"};
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private Button button(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);b.setTextSize(13);UiTheme.navigation(b);return b;}
 private EditText field(String hint){EditText e=new EditText(this);e.setSingleLine(true);e.setTextColor(Color.WHITE);e.setTextSize(14);e.setHintTextColor(0xff999999);e.setHint(hint);return e;}
 private void note(String text){lastOutcome=text;runOnUiThread(()->{if(!destroyed)status.setText(text);});}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);VodNetwork.initialize(this);catalogAtOpen=VodSession.catalogue(this).id;cbSource=VodSettings.cb01(this);getWindow().setStatusBarColor(0xff151619);getWindow().setNavigationBarColor(0xff151619);
  LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xff151619);setContentView(root);catalogScript=asset("cb01-catalog.js");
  LinearLayout first=new LinearLayout(this);first.setPadding(dp(6),0,dp(6),0);root.addView(first,new LinearLayout.LayoutParams(-1,dp(50)));
  site=new Spinner(this);site.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"CB01"}));first.addView(site,new LinearLayout.LayoutParams(dp(170),-1));domain=field("URL sito");first.addView(domain,new LinearLayout.LayoutParams(0,-1,1));Button load=button("Salva URL");first.addView(load);
  LinearLayout second=new LinearLayout(this);second.setPadding(dp(6),0,dp(6),0);root.addView(second,new LinearLayout.LayoutParams(-1,dp(50)));query=field("Titolo da cercare");second.addView(query,new LinearLayout.LayoutParams(0,-1,1));Button search=button("Cerca");second.addView(search);Button catalogue=button("Catalogo");second.addView(catalogue);Button settingsButton=button("Impostazioni");second.addView(settingsButton);settingsButton.setOnClickListener(v->startActivity(new Intent(this,VodSettingsActivity.class)));catalogue.setOnClickListener(v->catalogue());
  status=new TextView(this);status.setTextColor(0xffd4a84b);status.setTextSize(12);status.setPadding(dp(10),dp(3),dp(10),dp(3));status.setMaxLines(2);root.addView(status,new LinearLayout.LayoutParams(-1,dp(40)));
  status.setOnLongClickListener(v->{android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Esito prova",site.getSelectedItem()+" · "+query.getText()+"\n"+lastOutcome));Toast.makeText(this,"Esito copiato",Toast.LENGTH_SHORT).show();return true;});
  ScrollView scroll=new ScrollView(this);results=new LinearLayout(this);results.setOrientation(1);scroll.addView(results);FrameLayout content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));web=new WebView(this);content.addView(web,new FrameLayout.LayoutParams(-1,-1));web.setAlpha(0f);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));scroll.setBackgroundColor(0xff151619);web.setBackgroundColor(Color.BLACK);WebSettings settings=web.getSettings();web.setFocusable(false);settings.setUserAgentString(CbMixdropResolver.USER_AGENT);settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setMediaPlaybackRequiresUserGesture(false);userAgent=settings.getUserAgentString();settings.setSupportMultipleWindows(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
  web.setWebChromeClient(new WebChromeClient(){public boolean onCreateWindow(WebView v,boolean d,boolean g,Message m){return false;}public boolean onJsAlert(WebView v,String url,String message,JsResult result){if(probing&&CbLinkTargets.navigation(resolverTarget,url)){lastStage="Fonte · "+message.replaceAll("https?://[^ ]+","[link]").substring(0,Math.min(message.replaceAll("https?://[^ ]+","[link]").length(),160));note(lastStage);}result.confirm();return true;}});
  web.setWebViewClient(new WebViewClient(){
   public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){try{URI u=new URI(r.getUrl().toString());return !"https".equals(u.getScheme())||u.getHost()==null||blocked(u.getHost())||(probing&&r.isForMainFrame()&&!resolverTarget.isEmpty()&&!CbLinkTargets.navigation(resolverTarget,r.getUrl().toString()));}catch(Exception e){return true;}}
   public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){if(blocked(r.getUrl().getHost()))return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));return null;}
   public void onPageStarted(WebView v,String url,android.graphics.Bitmap icon){pageError=false;if(probing){if(CbLinkTargets.mixdrop(url))resolverTarget=CbLinkTargets.embed(url);playerSince=System.currentTimeMillis();touched=false;try{lastStage="Player · "+new URI(url).getHost();note(lastStage);}catch(Exception ignored){}}}
   public void onPageFinished(WebView v,String url){}
   public void onReceivedHttpError(WebView v,WebResourceRequest r,WebResourceResponse e){if(r.isForMainFrame()){pageError=true;lastStage="Player HTTP "+e.getStatusCode()+" · "+r.getUrl().getHost();note(lastStage);}}
   public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()){pageError=true;note("Pagina non caricata · "+e.getDescription());}}
  });
  site.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onItemSelected(AdapterView<?> a,View v,int n,long id){siteIndex=n;reset();results.removeAllViews();domain.setText(cbSource.url);String title=getIntent().getStringExtra("titleJson");if(title!=null)try{movieJson=new JSONObject(title);}catch(Exception ignored){}String page=getIntent().getStringExtra("moviePage");if(page!=null&&!page.isEmpty())openMovie(movieJson==null?"Film CB01":movieJson.optString("name"),page);else if(movieJson!=null){query.setText(movieJson.optString("name"));search();}else catalogue();}public void onNothingSelected(AdapterView<?> a){}});
  query.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);query.setOnEditorActionListener((v,action,event)->{if(action==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){search();return true;}return false;});load.setOnClickListener(v->loadSite());search.setOnClickListener(v->search());note("Pronto");
 }
 private static boolean blocked(String host){if(host==null)return false;for(String bad:new String[]{"doubleclick.net","googlesyndication.com","popads.net","popcash.net","googleadservices.com","adsco.re"})if(host.equals(bad)||host.endsWith("."+bad))return true;return false;}
 private void reset(){++generation;probing=false;listing=false;searching=false;opening=false;resolverTarget="";seen.clear();visited.clear();alternatives.clear();playerHops=0;lastStage="";web.stopLoading();ui.removeCallbacksAndMessages(null);}
 private void loadSite(){try{String raw=domain.getText().toString().trim();URI u=new URI(raw);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null)throw new Exception();reset();saveDomain(raw);note("URL salvato · inserisci il titolo e premi Cerca");}catch(Exception e){note("Inserisci un URL HTTPS valido");}}
 private String searchTerm="";
 private void search(){String q=query.getText().toString().trim();if(q.isEmpty()){catalogue();return;}try{URI u=new URI(domain.getText().toString().trim());if(!"https".equals(u.getScheme())||u.getHost()==null)throw new Exception();reset();sourceRows.clear();searchTerm=q;results.removeAllViews();searching=true;int request=generation;saveDomain(u.toString());note("Ricerca dei film…");if(siteIndex==1){web.loadUrl(u.resolve("/").toString());ui.postDelayed(()->submitNativeSearch(q,request,0),1800);}else{web.loadUrl(u.resolve("/").toString()+"?s="+java.net.URLEncoder.encode(q,"UTF-8"));ui.postDelayed(()->collectResults(request,0),1500);}}catch(Exception e){note("Inserisci un URL HTTPS valido");}}
 private void submitNativeSearch(String q,int request,int attempt){if(destroyed||request!=generation||!searching)return;web.evaluateJavascript(VodWebSearchScript.submit(JSONObject.quote(q)),value->{if(request!=generation||destroyed)return;if("true".equals(value))ui.postDelayed(()->collectResults(request,0),1800);else if(attempt<10)ui.postDelayed(()->submitNativeSearch(q,request,attempt+1),700);else note("Ricerca della fonte non disponibile · prova Catalogo");});}
 private void collectResults(int request,int attempt){if(destroyed||request!=generation||!searching)return;
  String script=catalogScript+"("+JSONObject.quote(searchTerm)+")";
  web.evaluateJavascript(script,raw->{if(destroyed||request!=generation||!searching)return;try{JSONArray found=new JSONArray(new JSONArray("["+raw+"]").getString(0));if(found.length()>0){searching=false;note("Seleziona un film · "+found.length()+" risultati");cachedCards=found;showCards(found,request);if(results.getChildCount()>0&&results.getChildAt(0) instanceof LinearLayout){ViewGroup cards=(ViewGroup)results.getChildAt(0);if(cards.getChildCount()>0)cards.getChildAt(0).requestFocus();}return;}}catch(Exception ignored){}if(attempt<16)ui.postDelayed(()->collectResults(request,attempt+1),1000);else{searching=false;if(!pageError)note("Nessun titolo trovato · verifica il titolo o l’URL della fonte");}});
 }
 private String asset(String name){try(java.io.InputStream in=getAssets().open(name);java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream()){byte[] b=new byte[4096];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8");}catch(Exception e){return "(function(){return '[]'})";}}
 private void catalogue(){try{URI u=new URI(domain.getText().toString().trim());if(!"https".equals(u.getScheme())||u.getHost()==null)throw new Exception();reset();sourceRows.clear();searchTerm="";results.removeAllViews();searching=true;note("Caricamento catalogo…");int request=generation;web.loadUrl(u.resolve("/").toString());ui.postDelayed(()->collectResults(request,0),1800);}catch(Exception e){note("Inserisci un URL HTTPS valido");}}
 private void showCards(JSONArray found,int request)throws Exception{int cols=Math.max(2,Math.min(6,(int)(getResources().getDisplayMetrics().widthPixels/getResources().getDisplayMetrics().density)/155));LinearLayout row=null;
  for(int i=0;i<found.length();i++){if(i%cols==0){row=new LinearLayout(this);results.addView(row);}JSONObject item=found.getJSONObject(i);String title=item.getString("title"),url=item.getString("url"),image=item.optString("image");LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(5),dp(5),dp(5),dp(8));row.addView(card,new LinearLayout.LayoutParams(0,dp(275),1));ImageView poster=new ImageView(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);poster.setBackgroundColor(0xff292b31);poster.setContentDescription(title);card.addView(poster,new LinearLayout.LayoutParams(-1,dp(215)));TextView label=new TextView(this);label.setText(title);label.setTextColor(Color.WHITE);label.setTextSize(13);label.setMaxLines(3);card.addView(label);card.setFocusable(true);card.setClickable(true);card.setBackground(cardFocus());card.setOnClickListener(v->openMovie(title,url));poster.setFocusable(false);label.setFocusable(false);if(image.startsWith("https://"))images.submit(()->{try(Response r=CbTransport.HTTP.newCall(new Request.Builder().url(image).header("User-Agent",userAgent).header("Referer",domainText()).build()).execute()){if(r.isSuccessful()&&r.body()!=null){android.graphics.Bitmap bitmap=android.graphics.BitmapFactory.decodeStream(r.body().byteStream());runOnUiThread(()->{if(!destroyed&&request==generation&&bitmap!=null)poster.setImageBitmap(bitmap);});}}catch(Exception ignored){}});
  }if(row!=null)for(int n=found.length()%cols;n>0&&n<cols;n++)row.addView(new View(this),new LinearLayout.LayoutParams(0,1,1));
 }
 private String domainText(){try{return new URI(filmPage.isEmpty()?homes[siteIndex]:filmPage).resolve("/").toString();}catch(Exception e){return homes[0];}}
 private int siteIndex;
 private void openMovie(String title,String url){if(movieJson==null||!url.equals(movieJson.optString("_web_page")))try{movieJson=new JSONObject().put("id",String.valueOf(Integer.toUnsignedLong(url.hashCode()))).put("name",title).put("type","movie").put("slug","cb01").put("_web_page",url);if(cachedCards!=null)for(int i=0;i<cachedCards.length();i++){JSONObject card=cachedCards.optJSONObject(i);if(card!=null&&url.equals(card.optString("url")))movieJson.put("_poster_url",card.optString("image"));}}catch(Exception ignored){}reset();sourceRows.clear();query.setText(title);filmPage=url;listing=true;results.removeAllViews();Button back=button("‹ Catalogo R. ITA");back.setOnClickListener(v->{if(getIntent().hasExtra("moviePage"))finish();else backToCards();});results.addView(back);TextView name=new TextView(this);name.setText(title+"\nFonti video");name.setTextColor(Color.WHITE);name.setTextSize(20);name.setPadding(dp(12),dp(12),dp(12),dp(12));results.addView(name);note("Caricamento delle fonti del film…");int request=generation;web.loadUrl(url);ui.postDelayed(()->collectChoices(request,0),2000);}
 private void backToCards(){sourceRows.clear();reset();results.removeAllViews();try{if(cachedCards!=null){showCards(cachedCards,generation);note("Seleziona un film");}else catalogue();}catch(Exception e){catalogue();}}
 private void collectChoices(int request,int attempt){if(destroyed||request!=generation||!listing)return;web.evaluateJavascript(VodWebSearchScript.snapshot(),raw->{if(destroyed||request!=generation||!listing)return;try{JSONObject page=new JSONObject(new JSONArray("["+raw+"]").getString(0));for(CbStreamChoices.Choice c:CbStreamChoices.parse(page.optString("html"),page.optString("url")))addChoice(c);if(!sourceRows.isEmpty())note("Seleziona una fonte per avviare il player");}catch(Exception ignored){}if(sourceRows.isEmpty()&&attempt<12)ui.postDelayed(()->collectChoices(request,attempt+1),1000);else if(sourceRows.isEmpty()&&!pageError)note("Nessuna fonte video trovata nella scheda del film");});}
 private void addChoice(CbStreamChoices.Choice choice){if(sourceRows.containsKey(choice.url))return;String display=choice.label;int same=0;for(Button existing:sourceRows.values())if(existing.getText().toString().startsWith(choice.label+" ·")||existing.getText().toString().startsWith(choice.label+" ("))same++;if(same>0)display+=" ("+(same+1)+")";Button row=button(display+" · "+(choice.direct?"Flusso diretto":"Fonte da risolvere"));row.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);results.addView(row,new LinearLayout.LayoutParams(-1,dp(62)));sourceRows.put(choice.url,row);if(!CbLinkTargets.mixdrop(choice.url)&&!CbLinkTargets.stay(choice.url)){row.setText(display+" · estrazione non ancora supportata");row.setOnClickListener(v->note("Per ora è supportato soltanto Mixdrop"));}else row.setOnClickListener(v->resolveChoice(choice,row));row.setOnLongClickListener(v->{android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Link fonte",choice.url));Toast.makeText(this,"Link della fonte copiato",Toast.LENGTH_SHORT).show();return true;});}
 private void resolveChoice(CbStreamChoices.Choice choice,Button row){reset();resolverTarget=CbLinkTargets.embed(choice.url);activeSource=row;activeName=choice.label;probing=true;int request=generation;row.setText(choice.label+" · Estrazione…");if(CbLinkTargets.mixdrop(choice.url))openResolved(resolverTarget,origin(filmPage),request,row);else if(CbLinkTargets.stay(choice.url)){note("Risoluzione del collegamento Mixdrop…");worker.submit(()->{try{String target=CbStayResolver.resolve(choice.url,origin(filmPage),CbMixdropResolver.USER_AGENT);runOnUiThread(()->{if(destroyed||request!=generation||!probing)return;if(!CbLinkTargets.mixdrop(target)){probing=false;row.setText(choice.label+" · estrazione non ancora supportata");note("Per ora è supportato soltanto Mixdrop");return;}resolverTarget=target;openResolved(target,origin(choice.url),request,row);});}catch(Exception e){runOnUiThread(()->{if(destroyed||request!=generation)return;probing=false;row.setText(choice.label+" · Non disponibile");note(e.getMessage()==null?"Collegamento non risolto":e.getMessage());});}});}else{probing=false;note("Per ora è supportato soltanto Mixdrop");}ui.postDelayed(()->{if(request==generation&&probing&&!opening){probing=false;row.setText(choice.label+" · Tempo di attesa terminato");note("Riprova la fonte Mixdrop");}},75000);}
 private void openResolved(String target,String parent,int request,Button row){
  if(!CbLinkTargets.mixdrop(target)){probing=false;note("Per ora è supportato soltanto Mixdrop");return;}
  lastStage="Mixdrop · lettura della configurazione video";note(lastStage);
  worker.submit(()->{try{CbMixdropResolver.Result result=CbMixdropResolver.resolve(target,parent,userAgent);runOnUiThread(()->{if(destroyed||request!=generation||!probing||opening)return;resolverTarget=result.page;Map<String,String> headers=new HashMap<>();headers.put("Referer",result.page);headers.put("Origin",origin(result.page).replaceAll("/$",""));headers.put("User-Agent",CbMixdropResolver.USER_AGENT);lastStage="Mixdrop · verifica del flusso MP4";note(lastStage);detect(result.url,headers,true);});}catch(Exception e){runOnUiThread(()->{if(destroyed||request!=generation||!probing)return;probing=false;lastStage=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();row.setText(activeName+" · Non disponibile, riprova");note(lastStage);});}});
 }
 private String origin(String url){try{return new URI(url).resolve("/").toString();}catch(Exception e){return domainText();}}
 private void saveDomain(String raw){try{String base=VodSource.base(raw);java.util.List<VodSettings.Source> sources=VodSettings.sources(this);VodSettings.Source current=VodSettings.cb01(this);boolean found=false;for(int i=0;i<sources.size();i++)if(sources.get(i).id.equals(current.id)){sources.set(i,new VodSettings.Source(current.id,current.name,base,"web"));found=true;}if(!found)sources.add(new VodSettings.Source(current.id,current.name,base,"web"));VodSettings.prefs(this).edit().putBoolean("manual_"+current.id,true).apply();VodSettings.save(this,sources);cbSource=VodSettings.cb01(this);}catch(Exception ignored){}}
 private android.graphics.drawable.Drawable cardFocus(){android.graphics.drawable.StateListDrawable d=new android.graphics.drawable.StateListDrawable();android.graphics.drawable.GradientDrawable f=new android.graphics.drawable.GradientDrawable();f.setColor(UiTheme.softFocus(this));f.setStroke(dp(3),UiTheme.accent(this));d.addState(new int[]{android.R.attr.state_focused},f);d.addState(new int[]{},new android.graphics.drawable.ColorDrawable(UiTheme.panel(this)));return d;}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==142){opening=false;setResult(result,data);}}
 private static boolean validHttps(String url){try{URI u=new URI(url);return "https".equals(u.getScheme())&&u.getHost()!=null&&u.getUserInfo()==null&&!WebMovieLinks.trailer(url);}catch(Exception e){return false;}}
 private static boolean candidate(String url){if(WebMovieLinks.media(url))return true;try{URI u=new URI(url);return "https".equals(u.getScheme())&&u.getHost()!=null&&!WebMovieLinks.trailer(url)&&u.getPath().matches("(?i).*/(?:master|manifest|playlist|videoplayback)(?:[./].*)?");}catch(Exception e){return false;}}
 private void detect(String url,Map<String,String> requestHeaders){detect(url,requestHeaders,false);}
 private void detect(String url,Map<String,String> requestHeaders,boolean exposed){if(destroyed||opening||!CbLinkTargets.ownsMedia(resolverTarget,url)||!(candidate(url)||(exposed&&validHttps(url)))||seen.size()>=24||!seen.add(url))return;final int request=generation;Map<String,String> headers=new HashMap<>();
  for(Map.Entry<String,String> h:requestHeaders.entrySet())for(String key:new String[]{"Referer","Origin","User-Agent"})if(key.equalsIgnoreCase(h.getKey()))headers.put(key,h.getValue());headers.putIfAbsent("Referer",filmPage);headers.putIfAbsent("User-Agent",userAgent);String cookies=CookieManager.getInstance().getCookie(url);if(cookies!=null&&!cookies.isEmpty())headers.put("Cookie",cookies);
  worker.submit(()->{if(destroyed||request!=generation||!probing||opening)return;try{boolean mp4=new URI(url).getPath().toLowerCase(Locale.ROOT).endsWith(".mp4");Request.Builder b=new Request.Builder().url(url);for(Map.Entry<String,String> h:headers.entrySet())b.header(h.getKey(),h.getValue());if(mp4||exposed)b.header("Range","bytes=0-8191");
   try(Response r=CbTransport.HTTP.newCall(b.build()).execute()){if(destroyed||request!=generation)return;if(!r.isSuccessful()||r.body()==null){lastStage="Video HTTP "+r.code()+" · "+new URI(url).getHost();note(lastStage);return;}String type=r.header("Content-Type","");byte[] signature=r.peekBody(32).bytes();if(type.startsWith("video/")||(signature.length>=8&&signature[4]==102&&signature[5]==116&&signature[6]==121&&signature[7]==112))mp4=true;if(mp4){if(!type.startsWith("video/")&&!type.contains("octet-stream")){note("Il server non restituisce un video MP4");return;}}else{String first=r.body().source().readUtf8LineStrict(4096);if(first==null||!first.replace("\uFEFF","").trim().equals("#EXTM3U")){note("La risposta non è una playlist HLS");return;}}}
   final boolean progressive=mp4;runOnUiThread(()->{if(destroyed||request!=generation||opening)return;opening=true;probing=false;web.stopLoading();web.evaluateJavascript("document.querySelectorAll('video,audio').forEach(function(v){v.pause()})",null);note("Flusso verificato · apertura Media3");startActivityForResult(new Intent(this,VodPlayerActivity.class).putExtra("source",cbSource.json().toString()).putExtra("titleJson",movieJson.toString()).putExtra("episode","").putExtra("label",movieJson.optString("name")).putExtra("episodes","[]").putExtra("index",-1).putExtra("resolvedWebUrl",url).putExtra("resolvedWebHeaders",new JSONObject(headers).toString()).putExtra("startPosition",getIntent().getLongExtra("startPosition",-1)),142);});
  }catch(Exception e){if(!destroyed&&request==generation)note("Video non verificato · "+e.getClass().getSimpleName());}});
 }
 @Override public void onBackPressed(){if(getIntent().hasExtra("moviePage")){finish();}else if(!sourceRows.isEmpty()){sourceRows.clear();backToCards();}else{reset();super.onBackPressed();}}
 @Override protected void onPause(){super.onPause();web.onPause();CookieManager.getInstance().flush();}
 @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();opening=false;if(catalogAtOpen!=null&&!catalogAtOpen.equals(VodSession.catalogue(this).id)){startActivity(new Intent(this,VodActivity.class));finish();}}
 @Override protected void onDestroy(){destroyed=true;++generation;ui.removeCallbacksAndMessages(null);worker.shutdownNow();images.shutdownNow();web.stopLoading();web.destroy();super.onDestroy();}
}
