package it.carmine.streamplayer;
import android.app.Activity;import android.os.*;import android.webkit.*;import android.widget.FrameLayout;import java.util.*;import org.json.*;
/** Same navigation and form submission as the working VOD test; native R. ITA cards stay visible. */
final class CbCatalogLoader {
 interface Callback {void done(List<VodSource.Title> titles,String error);}
 private final WebView web;private final Handler ui=new Handler(Looper.getMainLooper());private boolean closed;private String script;private Callback callback;private String query="";private final LinkedHashMap<String,VodSource.Title> titles=new LinkedHashMap<>();private final ArrayDeque<String> pages=new ArrayDeque<>();private final Set<String> visited=new HashSet<>();private int scans,mode;private String forcedType="";
 CbCatalogLoader(Activity a,FrameLayout root){web=new WebView(a);web.setAlpha(0);web.setFocusable(false);root.addView(web,0,new FrameLayout.LayoutParams(-1,-1));WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setUserAgentString(CbMixdropResolver.USER_AGENT);settings.setSupportMultipleWindows(false);settings.setJavaScriptCanOpenWindowsAutomatically(false);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.setWebChromeClient(new WebChromeClient(){public boolean onCreateWindow(WebView w,boolean d,boolean g,Message message){return false;}});web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest request){return !CbCatalogNavigation.allowed(request.getUrl().toString());}});try(java.io.InputStream in=a.getAssets().open("cb01-catalog.js")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buffer=new byte[4096];int n;while((n=in.read(buffer))!=-1)out.write(buffer,0,n);script=out.toString("UTF-8");}catch(Exception e){script="(function(){return '[]'})";}}
 void load(VodSettings.Source source,String q,Callback cb){load(source,q,0,cb);}
 void load(VodSettings.Source source,String q,int selectedMode,Callback cb){callback=cb;query=q.startsWith("@@")?"":q;mode=selectedMode;pages.add(source.url.replaceAll("/+$","")+"/");next();}
 private void next(){if(closed)return;String page=pages.poll();if(page==null||scans>=4){callback.done(new ArrayList<>(titles.values()),titles.isEmpty()?"CB01 · nessun titolo trovato o sito non raggiungibile":"");close();return;}if(!visited.add(page)){next();return;}scans++;forcedType=CbCatalogNavigation.seriesPage(page)?"tv":"";web.loadUrl(page);ui.postDelayed(()->{web.evaluateJavascript(CbCatalogNavigation.LINKS_JS,links->{if(closed)return;try{JSONArray found=jsonArray(links);for(int i=0;i<found.length();i++)CbCatalogNavigation.enqueue(pages,visited,found.getString(i),mode);}catch(Exception ignored){}if(query.isEmpty())poll(0);else submit(0);});},1300);}
 private void submit(int attempt){if(closed)return;web.evaluateJavascript(VodWebSearchScript.submit(JSONObject.quote(query)),raw->{if(closed)return;if("true".equals(raw))ui.postDelayed(()->poll(0),1700);else if(attempt<5)ui.postDelayed(()->submit(attempt+1),700);else{String current=web.getUrl();if(!CbCatalogNavigation.allowed(current)){poll(0);return;}String base=current.split("[?#]")[0];web.loadUrl(base+"?s="+VodSource.encode(query));ui.postDelayed(()->poll(0),1300);}});}
 private void poll(int attempt){if(closed)return;web.evaluateJavascript(script+"("+JSONObject.quote(query)+",0)",raw->{if(closed)return;int count=0;try{JSONArray cards=jsonArray(raw);count=cards.length();for(int i=0;i<count;i++){JSONObject c=cards.getJSONObject(i);String url=c.getString("url");if(!CbCatalogNavigation.allowed(url))continue;String type=forcedType.isEmpty()?c.optString("type","movie"):forcedType;JSONObject j=new JSONObject().put("id",String.valueOf(Integer.toUnsignedLong(url.hashCode()))).put("slug","cb01").put("name",c.getString("title")).put("type",type).put("_poster_url",c.optString("image")).put("_web_page",url);VodSource.Title previous=titles.get(url);if(previous==null||type.equals("tv"))titles.put(url,new VodSource.Title(j,""));}}catch(Exception ignored){}if(count==0&&attempt<10){ui.postDelayed(()->poll(attempt+1),800);return;}web.evaluateJavascript(CbCatalogNavigation.LINKS_JS,links->{if(closed)return;try{JSONArray found=jsonArray(links);for(int i=0;i<found.length();i++)CbCatalogNavigation.enqueue(pages,visited,found.getString(i),mode);}catch(Exception ignored){}next();});});}
 private static JSONArray jsonArray(String raw)throws Exception{return new JSONArray(new JSONArray("["+raw+"]").getString(0));}
 void close(){if(closed)return;closed=true;ui.removeCallbacksAndMessages(null);web.stopLoading();if(web.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)web.getParent()).removeView(web);web.destroy();}
}
