package it.carmine.streamplayer;
import java.net.URI;import java.util.*;import java.util.regex.*;
/** Reads the public player configuration as data; does not execute website scripts. */
final class CbMixdropConfig {
 private static final String LITERAL="('(?:\\\\.|[^'\\\\])*'|\"(?:\\\\.|[^\"\\\\])*\")";
 static String unquote(String literal){String s=literal.substring(1,literal.length()-1);StringBuilder out=new StringBuilder();for(int i=0;i<s.length();i++){char c=s.charAt(i);if(c!='\\'||i+1==s.length()){out.append(c);continue;}char n=s.charAt(++i);if((n=='u'||n=='x')&&i+(n=='u'?4:2)<s.length()){int length=n=='u'?4:2;try{out.append((char)Integer.parseInt(s.substring(i+1,i+1+length),16));i+=length;continue;}catch(Exception ignored){}}switch(n){case 'n':out.append('\n');break;case 'r':out.append('\r');break;case 't':out.append('\t');break;case '\n':break;case '\r':if(i+1<s.length()&&s.charAt(i+1)=='\n')i++;break;default:out.append(n);}}return out.toString();}
 private static String code(int value,int base){String alphabet="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";StringBuilder out=new StringBuilder();do{out.append(alphabet.charAt(value%base));value/=base;}while(value>0);return out.reverse().toString();}
 static String unpack(String payload,int base,int count,String dict){if(base<2||base>62||count<1||count>4096)throw new IllegalArgumentException("Formato configurazione non supportato");String[] words=dict.split("\\|",-1);Map<String,String> table=new HashMap<>();for(int i=0;i<Math.min(count,words.length);i++)if(!words[i].isEmpty())table.put(code(i,base),words[i]);Matcher tokens=Pattern.compile("\\b[0-9A-Za-z]+\\b").matcher(payload);StringBuffer result=new StringBuffer();while(tokens.find())tokens.appendReplacement(result,Matcher.quoteReplacement(table.getOrDefault(tokens.group(),tokens.group())));tokens.appendTail(result);return result.toString();}
 private static String readUrl(String text,String page){Matcher m=Pattern.compile("MDCore\\s*(?:\\.\\s*wurl|\\[\\s*['\"]wurl['\"]\\s*\\])\\s*=\\s*"+LITERAL).matcher(text);while(m.find())try{String raw=unquote(m.group(1)).replace("&amp;","&");String url=new URI(page).resolve(raw).toString();if(CbLinkTargets.ownsMedia(page,url)&&WebMovieLinks.media(url))return url;}catch(Exception ignored){}return "";}
 static String extract(String html,String page){if(!CbLinkTargets.mixdrop(page)||CbLinkTargets.fileId(page).isEmpty())return "";String direct=readUrl(html,page);if(!direct.isEmpty())return direct;
  Matcher packed=Pattern.compile("\\}\\s*\\(\\s*"+LITERAL+"\\s*,\\s*(\\d+)\\s*,\\s*(\\d+)\\s*,\\s*"+LITERAL+"\\.split\\(\\s*['\"]\\|['\"]\\s*\\)",Pattern.DOTALL).matcher(html);int scanned=0;while(packed.find()&&scanned++<12){try{String config=unpack(unquote(packed.group(1)),Integer.parseInt(packed.group(2)),Integer.parseInt(packed.group(3)),unquote(packed.group(4)));String url=readUrl(config,page);if(!url.isEmpty())return url;}catch(Exception ignored){}}return "";
 }
}
