package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.webkit.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import org.json.*;import okhttp3.*;
/** Exact selected page -> native source chooser -> existing Media3 player. */
final class CbSourcesDialog {
 static CbSourcesDialog show(Activity a,FrameLayout root,VodSource.Title title,VodSettings.Source source,long position){CbSourcesDialog d=new CbSourcesDialog(a,root,title,source,position);d.start();return d;}
 private final Activity a;private final VodSource.Title title;private final VodSettings.Source source;private long position;private final WebView web;private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService worker=Executors.newSingleThreadExecutor();private final LinearLayout rows;private final TextView status;private final AlertDialog dialog;private String currentPage,episode="",episodeLabel="";private boolean closed,busy;private int generation,seriesLevel;private final Set<String> urls=new HashSet<>();
 private CbSourcesDialog(Activity activity,FrameLayout root,VodSource.Title t,VodSettings.Source s,long pos){a=activity;title=t;source=s;currentPage=t.json.optString("_web_page");episode=t.json.optString("_cb_episode");episodeLabel=t.json.optString("_cb_label",t.name);if(!episode.isEmpty()){currentPage=episode;seriesLevel=2;}position=pos>=0?pos:VodLibrary.position(a,s.id,t.id,episode);LinearLayout content=new LinearLayout(a);content.setOrientation(1);content.setPadding(20,12,20,12);content.setBackgroundColor(UiTheme.background(a));status=new TextView(a);status.setTextColor(UiTheme.TEXT);status.setText(title.series()&&episode.isEmpty()?"Caricamento stagioni…":"Caricamento fonti…");content.addView(status);ScrollView scroll=new ScrollView(a);rows=new LinearLayout(a);rows.setOrientation(1);scroll.addView(rows);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));dialog=new AlertDialog.Builder(a).setTitle(t.name+(t.series()?" · Episodi":" · Fonti video")).setView(content).setNegativeButton("Chiudi",null).create();dialog.setOnDismissListener(d->close());web=new WebView(a);web.setAlpha(0);web.setFocusable(false);root.addView(web,new FrameLayout.LayoutParams(1,1));WebSettings ws=web.getSettings();ws.setJavaScriptEnabled(true);ws.setDomStorageEnabled(true);ws.setUserAgentString(CbMixdropResolver.USER_AGENT);ws.setSupportMultipleWindows(false);ws.setJavaScriptCanOpenWindowsAutomatically(false);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){try{return !new java.net.URI(t.json.optString("_web_page")).getHost().equals(r.getUrl().getHost());}catch(Exception e){return true;}}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String h=r.getUrl().getHost();if(h!=null&&h.matches(".*(?:doubleclick|googlesyndication|popads|popcash|adsco).*"))return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));return null;}});}
 private void start(){dialog.show();dialog.getWindow().setLayout(Math.min(a.getResources().getDisplayMetrics().widthPixels-40,900),Math.min(a.getResources().getDisplayMetrics().heightPixels-40,650));web.loadUrl(currentPage);ui.postDelayed(()->poll(0),1200);}
 private void poll(int attempt){if(closed)return;web.evaluateJavascript(VodWebSearchScript.snapshot(),raw->{if(closed)return;try{JSONObject p=new JSONObject(new JSONArray("["+raw+"]").getString(0));String html=p.optString("html"),page=p.optString("url");if(title.series()&&seriesLevel<2){CbSeriesNavigation.Result navigation=CbSeriesNavigation.parse(html,page);if(seriesLevel==0&&(navigation.seasons.size()>0||navigation.episodes.size()>0)){showSeasons(navigation);return;}if(seriesLevel==1&&navigation.episodes.size()>0){showEpisodes(navigation.episodes,"Scegli un episodio");return;}}else for(CbStreamChoices.Choice c:CbStreamChoices.parse(html,page))add(c);}catch(Exception ignored){}if(urls.isEmpty()&&attempt<15)ui.postDelayed(()->poll(attempt+1),800);else if(title.series()&&seriesLevel<2)status.setText(seriesLevel==0?"Stagioni non trovate nella pagina della serie":"Episodi non trovati nella stagione selezionata");else status.setText(urls.isEmpty()?"Nessuna fonte trovata per l’episodio selezionato":"Scegli una fonte · estrazione Mixdrop disponibile");});}
 private void showSeasons(CbSeriesNavigation.Result navigation){urls.clear();rows.removeAllViews();if(!navigation.seasons.isEmpty()){status.setText("Scegli una stagione");for(CbSeriesNavigation.Link link:navigation.seasons)addSeason(link);return;}LinkedHashMap<Integer,List<CbSeriesNavigation.Link>> groups=new LinkedHashMap<>();for(CbSeriesNavigation.Link link:navigation.episodes)groups.computeIfAbsent(link.season,k->new ArrayList<>()).add(link);if(groups.size()==1&&groups.containsKey(0)){seriesLevel=1;showEpisodes(groups.get(0),"Scegli un episodio");return;}status.setText("Scegli una stagione");for(Map.Entry<Integer,List<CbSeriesNavigation.Link>> group:groups.entrySet()){int season=group.getKey();Button b=navigationButton(season>0?"Stagione "+season:"Stagione disponibile");rows.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{seriesLevel=1;showEpisodes(group.getValue(),season>0?"Stagione "+season+" · scegli un episodio":"Scegli un episodio");});}focusFirst();}
 private void addSeason(CbSeriesNavigation.Link link){if(!urls.add("season:"+link.url))return;Button b=navigationButton(link.label+" ›");rows.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(busy)return;seriesLevel=1;currentPage=link.url;urls.clear();rows.removeAllViews();status.setText(link.label+" · caricamento episodi…");web.loadUrl(link.url);ui.postDelayed(()->poll(0),1000);});focusFirst();}
 private void showEpisodes(List<CbSeriesNavigation.Link> links,String heading){urls.clear();rows.removeAllViews();status.setText(heading);for(CbSeriesNavigation.Link link:links)addEpisode(link);focusFirst();}
 private void addEpisode(CbSeriesNavigation.Link link){if(!urls.add("episode:"+link.url))return;Button b=navigationButton(link.label+" ›");rows.addView(b,new LinearLayout.LayoutParams(-1,dp(58)));b.setOnClickListener(v->{if(busy)return;seriesLevel=2;currentPage=link.url;episode=link.url;episodeLabel=link.label;try{if(link.season>0)title.json.put("_seasonNumber",link.season);if(link.episode>0)title.json.put("_episodeNumber",link.episode);}catch(Exception ignored){}position=VodLibrary.position(a,source.id,title.id,episode);urls.clear();rows.removeAllViews();status.setText("Caricamento fonti · "+link.label);web.loadUrl(link.url);ui.postDelayed(()->poll(0),1000);});}
 private Button navigationButton(String label){Button b=new Button(a);b.setAllCaps(false);b.setText(label);UiTheme.navigation(b);return b;}
 private void focusFirst(){if(rows.getChildCount()>0)rows.getChildAt(0).requestFocus();}
 private int dp(int value){return Math.round(value*a.getResources().getDisplayMetrics().density);}
 private void add(CbStreamChoices.Choice c){if(!urls.add(c.url))return;Button b=new Button(a);b.setAllCaps(false);UiTheme.navigation(b);boolean supported=CbLinkTargets.mixdrop(c.url)||CbLinkTargets.stay(c.url);b.setText(c.label+(supported?"":" · non ancora supportata"));rows.addView(b,new LinearLayout.LayoutParams(-1,Math.round(64*a.getResources().getDisplayMetrics().density)));b.setOnLongClickListener(v->{android.content.ClipboardManager clipboard=(android.content.ClipboardManager)a.getSystemService(android.content.Context.CLIPBOARD_SERVICE);clipboard.setPrimaryClip(android.content.ClipData.newPlainText("Fonte video",c.url));Toast.makeText(a,"Link copiato",Toast.LENGTH_SHORT).show();return true;});b.setOnClickListener(v->{if(!supported){status.setText("Per ora è disponibile l’estrazione Mixdrop");return;}resolve(c,b);});if(rows.getChildCount()==1)b.requestFocus();}
 private void resolve(CbStreamChoices.Choice c,Button button){if(busy||closed)return;busy=true;int request=++generation;status.setText("Estrazione Mixdrop…");worker.submit(()->{try{String link=c.url;if(CbLinkTargets.stay(link))link=CbStayResolver.resolve(link,currentPage,CbMixdropResolver.USER_AGENT);if(!CbLinkTargets.mixdrop(link))throw new Exception("Il collegamento non porta a Mixdrop");CbMixdropResolver.Result result=CbMixdropResolver.resolve(link,currentPage,CbMixdropResolver.USER_AGENT);Map<String,String> headers=new LinkedHashMap<>();headers.put("User-Agent",CbMixdropResolver.USER_AGENT);headers.put("Referer",result.page);String cookies=CookieManager.getInstance().getCookie(result.url);if(cookies!=null&&!cookies.isEmpty())headers.put("Cookie",cookies);try(Response response=CbTransport.HTTP.newCall(new Request.Builder().url(result.url).headers(Headers.of(headers)).header("Range","bytes=0-1023").build()).execute()){if(!response.isSuccessful())throw new Exception("Video HTTP "+response.code());String mime=response.header("Content-Type","").toLowerCase(Locale.ROOT);if(!mime.startsWith("video/")&&!mime.contains("octet-stream"))throw new Exception("La fonte non ha restituito un video");}final Map<String,String> playbackHeaders=headers;ui.post(()->{if(closed||request!=generation||a.isFinishing())return;a.startActivityForResult(new Intent(a,VodPlayerActivity.class).putExtra("source",source.json().toString()).putExtra("titleJson",title.json.toString()).putExtra("episode",episode).putExtra("label",episodeLabel).putExtra("episodes","[]").putExtra("index",-1).putExtra("resolvedWebUrl",result.url).putExtra("resolvedWebHeaders",new JSONObject(playbackHeaders).toString()).putExtra("startPosition",position),101);dialog.dismiss();});}catch(Exception e){ui.post(()->{if(closed||request!=generation)return;busy=false;status.setText(e.getMessage()==null?"Fonte non disponibile · riprova":e.getMessage());});}});}
 void close(){if(closed)return;closed=true;if(dialog.isShowing())dialog.dismiss();++generation;ui.removeCallbacksAndMessages(null);worker.shutdownNow();web.stopLoading();if(web.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)web.getParent()).removeView(web);web.destroy();}
}
