package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.webkit.*;import android.widget.*;import java.util.*;import java.util.concurrent.*;import org.json.*;import okhttp3.*;
/** Exact selected page -> native source chooser -> existing Media3 player. */
final class CbSourcesDialog {
 static CbSourcesDialog show(Activity a,FrameLayout root,VodSource.Title title,VodSettings.Source source,long position){CbSourcesDialog d=new CbSourcesDialog(a,root,title,source,position);d.start();return d;}
 private final Activity a;private final VodSource.Title title;private final VodSettings.Source source;private final long position;private final WebView web;private final Handler ui=new Handler(Looper.getMainLooper());private final ExecutorService worker=Executors.newSingleThreadExecutor();private final LinearLayout rows;private final TextView status;private final AlertDialog dialog;private boolean closed,busy;private int generation;private final Set<String> urls=new HashSet<>();
 private CbSourcesDialog(Activity activity,FrameLayout root,VodSource.Title t,VodSettings.Source s,long pos){a=activity;title=t;source=s;position=pos;LinearLayout content=new LinearLayout(a);content.setOrientation(1);content.setPadding(20,12,20,12);content.setBackgroundColor(UiTheme.background(a));status=new TextView(a);status.setTextColor(UiTheme.TEXT);status.setText("Caricamento fonti…");content.addView(status);ScrollView scroll=new ScrollView(a);rows=new LinearLayout(a);rows.setOrientation(1);scroll.addView(rows);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));dialog=new AlertDialog.Builder(a).setTitle(t.name+" · Fonti video").setView(content).setNegativeButton("Chiudi",null).create();dialog.setOnDismissListener(d->close());web=new WebView(a);web.setAlpha(0);web.setFocusable(false);root.addView(web,new FrameLayout.LayoutParams(1,1));WebSettings ws=web.getSettings();ws.setJavaScriptEnabled(true);ws.setDomStorageEnabled(true);ws.setUserAgentString(CbMixdropResolver.USER_AGENT);ws.setSupportMultipleWindows(false);ws.setJavaScriptCanOpenWindowsAutomatically(false);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){try{return !new java.net.URI(t.json.optString("_web_page")).getHost().equals(r.getUrl().getHost());}catch(Exception e){return true;}}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){String h=r.getUrl().getHost();if(h!=null&&h.matches(".*(?:doubleclick|googlesyndication|popads|popcash|adsco).*"))return new WebResourceResponse("text/plain","UTF-8",new java.io.ByteArrayInputStream(new byte[0]));return null;}});}
 private void start(){dialog.show();dialog.getWindow().setLayout(Math.min(a.getResources().getDisplayMetrics().widthPixels-40,900),Math.min(a.getResources().getDisplayMetrics().heightPixels-40,650));web.loadUrl(title.json.optString("_web_page"));ui.postDelayed(()->poll(0),1200);}
 private void poll(int attempt){if(closed)return;web.evaluateJavascript(VodWebSearchScript.snapshot(),raw->{if(closed)return;try{JSONObject p=new JSONObject(new JSONArray("["+raw+"]").getString(0));for(CbStreamChoices.Choice c:CbStreamChoices.parse(p.optString("html"),p.optString("url")))add(c);}catch(Exception ignored){}if(urls.isEmpty()&&attempt<15)ui.postDelayed(()->poll(attempt+1),800);else status.setText(urls.isEmpty()?"Nessuna fonte trovata nella pagina selezionata":"Scegli una fonte · estrazione Mixdrop disponibile");});}
 private void add(CbStreamChoices.Choice c){if(!urls.add(c.url))return;Button b=new Button(a);b.setAllCaps(false);UiTheme.navigation(b);boolean supported=CbLinkTargets.mixdrop(c.url)||CbLinkTargets.stay(c.url);b.setText(c.label+(supported?"":" · non ancora supportata"));rows.addView(b,new LinearLayout.LayoutParams(-1,Math.round(64*a.getResources().getDisplayMetrics().density)));b.setOnClickListener(v->{if(!supported){status.setText("Per ora è disponibile l’estrazione Mixdrop");return;}resolve(c,b);});if(rows.getChildCount()==1)b.requestFocus();}
 private void resolve(CbStreamChoices.Choice c,Button button){if(busy||closed)return;busy=true;int request=++generation;status.setText("Estrazione Mixdrop…");worker.submit(()->{try{String link=c.url;if(CbLinkTargets.stay(link))link=CbStayResolver.resolve(link,title.json.optString("_web_page"),CbMixdropResolver.USER_AGENT);if(!CbLinkTargets.mixdrop(link))throw new Exception("Il collegamento non porta a Mixdrop");CbMixdropResolver.Result result=CbMixdropResolver.resolve(link,title.json.optString("_web_page"),CbMixdropResolver.USER_AGENT);Map<String,String> headers=new LinkedHashMap<>();headers.put("User-Agent",CbMixdropResolver.USER_AGENT);headers.put("Referer",result.page);String cookies=CookieManager.getInstance().getCookie(result.url);if(cookies!=null&&!cookies.isEmpty())headers.put("Cookie",cookies);try(Response response=CbTransport.HTTP.newCall(new Request.Builder().url(result.url).headers(Headers.of(headers)).header("Range","bytes=0-1023").build()).execute()){if(!response.isSuccessful())throw new Exception("Video HTTP "+response.code());String mime=response.header("Content-Type","").toLowerCase(Locale.ROOT);if(!mime.startsWith("video/")&&!mime.contains("octet-stream"))throw new Exception("La fonte non ha restituito un video");}final Map<String,String> playbackHeaders=headers;ui.post(()->{if(closed||request!=generation||a.isFinishing())return;a.startActivity(new Intent(a,VodPlayerActivity.class).putExtra("source",source.json().toString()).putExtra("titleJson",title.json.toString()).putExtra("episode","").putExtra("label",title.name).putExtra("episodes","[]").putExtra("index",-1).putExtra("resolvedWebUrl",result.url).putExtra("resolvedWebHeaders",new JSONObject(playbackHeaders).toString()).putExtra("startPosition",position));dialog.dismiss();});}catch(Exception e){ui.post(()->{if(closed||request!=generation)return;busy=false;status.setText(e.getMessage()==null?"Fonte non disponibile · riprova":e.getMessage());});}});}
 void close(){if(closed)return;closed=true;if(dialog.isShowing())dialog.dismiss();++generation;ui.removeCallbacksAndMessages(null);worker.shutdownNow();web.stopLoading();if(web.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)web.getParent()).removeView(web);web.destroy();}
}
