package it.carmine.streamplayer;
import android.content.*;import android.os.*;import com.google.firebase.*;import com.google.firebase.auth.*;import com.google.firebase.firestore.*;import org.json.*;import java.util.*;
/** Optional authenticated sync. Passwords stay with Firebase Auth; no account is bundled. */
final class CloudSync {
 private static Context context;private static FirebaseApp app;private static FirebaseAuth auth;private static FirebaseFirestore db;private static ListenerRegistration records,owner;private static final Handler ui=new Handler(Looper.getMainLooper());private static boolean started,pushing;private static long lastPush;private static String listening="",status="Sincronizzazione non configurata";
 static SharedPreferences config(Context c){return c.getSharedPreferences("cloudConfig",0);}
 static JSONObject parseConfig(String raw)throws Exception{JSONObject input=new JSONObject(raw);JSONObject info=input.optJSONObject("project_info");if(info==null){if(input.optString("projectId").isEmpty()||input.optString("apiKey").isEmpty()||input.optString("applicationId").isEmpty())throw new Exception("Configurazione incompleta");return input;}JSONArray clients=input.getJSONArray("client");for(int i=0;i<clients.length();i++){JSONObject client=clients.getJSONObject(i),details=client.getJSONObject("client_info");if(!details.getJSONObject("android_client_info").getString("package_name").equals("it.carmine.streamplayer"))continue;return new JSONObject().put("projectId",info.getString("project_id")).put("apiKey",client.getJSONArray("api_key").getJSONObject(0).getString("current_key")).put("applicationId",details.getString("mobilesdk_app_id"));}throw new Exception("Il file appartiene a un’altra app");}
 static synchronized void initialize(Context c){context=c.getApplicationContext();if(app!=null)return;try{String raw=config(c).getString("firebase","");if(raw.isEmpty()){try(java.io.InputStream in=c.getAssets().open("firebase-config.json")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] buf=new byte[2048];int n;while((n=in.read(buf))!=-1)out.write(buf,0,n);raw=out.toString("UTF-8");}catch(Exception absent){return;}config(c).edit().putString("firebase",raw).apply();}JSONObject j=parseConfig(raw);FirebaseOptions options=new FirebaseOptions.Builder().setProjectId(j.getString("projectId")).setApiKey(j.getString("apiKey")).setApplicationId(j.getString("applicationId")).build();app=FirebaseApp.initializeApp(context,options,"rita-vod");auth=FirebaseAuth.getInstance(app);db=FirebaseFirestore.getInstance(app);auth.useAppLanguage();auth.addAuthStateListener(a->attach());status="Accedi per sincronizzare";}catch(Exception e){status="Configurazione cloud non valida";}}
 static void configure(Context c,String raw)throws Exception{JSONObject j=parseConfig(raw);if(app!=null){JSONObject current=parseConfig(config(c).getString("firebase","{}"));if(current.toString().equals(j.toString()))return;throw new Exception("Questo dispositivo è già collegato a un progetto. Mantieni la configurazione attuale.");}config(c).edit().putString("firebase",j.toString()).apply();initialize(c);}
 static FirebaseAuth auth(Context c){initialize(c);return auth;}
 static String uid(Context c){initialize(c);FirebaseUser user=auth==null?null:auth.getCurrentUser();return user!=null&&config(c).getString("authorizedUid","").equals(user.getUid())?user.getUid():"";}
 static String status(Context c){initialize(c);return status;}
 static String device(Context c){String id=config(c).getString("device","");if(id.isEmpty()){id=UUID.randomUUID().toString();config(c).edit().putString("device",id).apply();}return id;}
 static SharedPreferences queue(String uid){return context.getSharedPreferences("cloudQueue_"+VodCache.digest(uid),0);}
 static SharedPreferences versions(String uid){return context.getSharedPreferences("cloudVersions_"+VodCache.digest(uid),0);}
 static void authorize(Context c,boolean merge,Runnable done,java.util.function.Consumer<String> failed){FirebaseUser user=auth(c)==null?null:auth.getCurrentUser();if(user==null){failed.accept("Accesso non disponibile");return;}String id=user.getUid();db.document("owners/"+id).get(Source.SERVER).addOnSuccessListener(doc->{if(!doc.exists()||!Boolean.TRUE.equals(doc.getBoolean("enabled"))){logout(c);failed.accept("Questo account non è abilitato alla sincronizzazione");return;}config(c).edit().putString("authorizedUid",id).apply();if(merge){SharedPreferences local=c.getSharedPreferences("vodLibrary",0);for(Map.Entry<String,?> e:local.getAll().entrySet())if(e.getValue() instanceof String&&CloudRecords.payloadAllowed(e.getKey(),(String)e.getValue())&&!VodLibrary.prefs(c).contains(e.getKey())){VodLibrary.prefs(c).edit().putString(e.getKey(),(String)e.getValue()).apply();changed(c,e.getKey(),(String)e.getValue());}}attach();done.run();}).addOnFailureListener(e->{logout(c);failed.accept("Impossibile verificare l’account: controlla rete e configurazione cloud");});}
 static void attach(){if(context==null||auth==null)return;String id=uid(context);if(id.equals(listening))return;if(records!=null)records.remove();if(owner!=null)owner.remove();listening=id;if(id.isEmpty()){status="Salvataggi locali · accesso cloud disattivato";return;}db.enableNetwork();status="Sincronizzazione in corso…";owner=db.document("owners/"+id).addSnapshotListener((doc,error)->{if(!id.equals(uid(context)))return;if(error==null&&doc!=null&&!doc.getMetadata().isFromCache()&&(!doc.exists()||!Boolean.TRUE.equals(doc.getBoolean("enabled"))))logout(context);});
  records=db.collection("users/"+id+"/records").addSnapshotListener((snapshot,error)->{if(!id.equals(uid(context)))return;if(error!=null){status="Cloud non disponibile · dati locali conservati";return;}if(snapshot==null)return;for(DocumentSnapshot doc:snapshot.getDocuments())applyRemote(id,doc.getData(),false);status=snapshot.getMetadata().isFromCache()?"Offline · ultime informazioni disponibili":queue(id).getAll().isEmpty()?"Sincronizzato":"Modifiche in attesa di sincronizzazione";flush(context,false);});
  Map<String,Object> d=new HashMap<>();d.put("name",config(context).getString("deviceName",Build.MODEL));d.put("updatedAt",FieldValue.serverTimestamp());db.document("users/"+id+"/devices/"+device(context)).set(d);if(!started){started=true;ui.postDelayed(new Runnable(){public void run(){flush(context,false);ui.postDelayed(this,60000);}},60000);}flush(context,true);
 }
 static void logout(Context c){if(records!=null){records.remove();records=null;}if(owner!=null){owner.remove();owner=null;}listening="";config(c).edit().remove("authorizedUid").apply();if(db!=null)db.disableNetwork();if(auth!=null)auth.signOut();status="Salvataggi locali · accesso cloud disattivato";}
 static void changed(Context c,String key,String payload){String id=uid(c);if(id.isEmpty()||!CloudRecords.keyAllowed(key)||(!key.contains(":tmdb:")&&key.startsWith("history:"))||payload!=null&&!CloudRecords.payloadAllowed(key,payload))return;try{JSONObject record=new JSONObject().put("key",key).put("base",versions(id).getLong(key,0)).put("token",UUID.randomUUID().toString()).put("deleted",payload==null).put("payload",payload==null?"":payload);queue(id).edit().putString(VodCache.digest(key),record.toString()).apply();flush(c,!key.startsWith("history:"));}catch(Exception ignored){}}
 static void flush(Context c,boolean force){String id=uid(c);long now=android.os.SystemClock.elapsedRealtime();if(id.isEmpty()||db==null||pushing||!force&&now-lastPush<60000)return;List<String> pending=new ArrayList<>();for(Object value:queue(id).getAll().values())if(value instanceof String)pending.add((String)value);if(pending.isEmpty())return;lastPush=now;pushing=true;push(id,pending,0);}
 static void push(String id,List<String> list,int n){if(!id.equals(uid(context))||n>=list.size()){pushing=false;if(id.equals(uid(context))&&queue(id).getAll().isEmpty())status="Sincronizzato";return;}try{JSONObject pending=new JSONObject(list.get(n));String key=pending.getString("key"),token=pending.getString("token");long expected=pending.getLong("base");DocumentReference ref=db.document("users/"+id+"/records/"+VodCache.digest(key));db.runTransaction(tx->{DocumentSnapshot remote=tx.get(ref);long revision=remote.exists()&&remote.getLong("revision")!=null?remote.getLong("revision"):0;Map<String,Object> result=remote.exists()?new HashMap<>(remote.getData()):new HashMap<>();if(CloudRecords.canCommit(expected,revision)){result.put("key",key);result.put("payload",pending.optString("payload"));result.put("deleted",pending.optBoolean("deleted"));result.put("revision",revision+1);result.put("device",device(context));result.put("updatedAt",FieldValue.serverTimestamp());tx.set(ref,result);}return result;}).addOnSuccessListener(data->{if(!id.equals(uid(context))){pushing=false;return;}String slot=VodCache.digest(key);String current=queue(id).getString(slot,"");try{JSONObject latest=new JSONObject(current);if(latest.optString("token").equals(token)){queue(id).edit().remove(slot).apply();applyRemote(id,data,true);}else{long revision=((Number)data.get("revision")).longValue();versions(id).edit().putLong(key,revision).apply();latest.put("base",revision);queue(id).edit().putString(slot,latest.toString()).apply();}}catch(Exception ignored){}push(id,list,n+1);}).addOnFailureListener(e->{status="Offline o cloud non disponibile · modifiche da sincronizzare";pushing=false;});}catch(Exception e){pushing=false;}}
 static void applyRemote(String id,Map<String,Object> data,boolean force){if(data==null||!id.equals(uid(context)))return;try{String key=(String)data.get("key"),payload=(String)data.get("payload");long revision=((Number)data.get("revision")).longValue();boolean deleted=Boolean.TRUE.equals(data.get("deleted"));if(!CloudRecords.keyAllowed(key)||!deleted&&!CloudRecords.payloadAllowed(key,payload))return;long known=versions(id).getLong(key,0);if(revision<known||!force&&queue(id).contains(VodCache.digest(key)))return;if(!deleted&&key.startsWith("history:")&&data.get("updatedAt") instanceof com.google.firebase.Timestamp){JSONObject history=new JSONObject(payload);history.put("time",((com.google.firebase.Timestamp)data.get("updatedAt")).toDate().getTime());payload=history.toString();}SharedPreferences.Editor edit=VodLibrary.prefs(context).edit();if(deleted)edit.remove(key);else edit.putString(key,payload);edit.apply();versions(id).edit().putLong(key,revision).apply();}catch(Exception ignored){}}
 static void updateDevice(Context c){String id=uid(c);if(id.isEmpty()||db==null)return;Map<String,Object> d=new HashMap<>();d.put("name",config(c).getString("deviceName",Build.MODEL));d.put("updatedAt",FieldValue.serverTimestamp());db.document("users/"+id+"/devices/"+device(c)).set(d);}
 static void devices(Context c,java.util.function.Consumer<List<String>> result){String id=uid(c);if(id.isEmpty()){result.accept(Collections.emptyList());return;}db.collection("users/"+id+"/devices").get().addOnSuccessListener(snapshot->{List<String> rows=new ArrayList<>();for(DocumentSnapshot d:snapshot.getDocuments())rows.add(d.getString("name")+(d.getId().equals(device(c))?" · questo dispositivo":""));result.accept(rows);}).addOnFailureListener(e->result.accept(Arrays.asList("Elenco non disponibile")));}
}
