package it.carmine.streamplayer;
import android.content.*;import android.security.keystore.*;import android.util.Base64;import java.security.*;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;import org.json.*;import okhttp3.*;
final class RaiAccount {
 private static Context context;private static volatile String token="";private static volatile long expires;
 static void init(Context c){context=c.getApplicationContext();try{String raw=context.getSharedPreferences("rai_account",0).getString("session","");if(!raw.isEmpty()){String[] p=raw.split(":");Cipher cipher=Cipher.getInstance("AES/GCM/NoPadding");cipher.init(Cipher.DECRYPT_MODE,key(),new GCMParameterSpec(128,Base64.decode(p[0],Base64.NO_WRAP)));JSONObject j=new JSONObject(new String(cipher.doFinal(Base64.decode(p[1],Base64.NO_WRAP)),"UTF-8"));token=j.getString("token");expires=j.getLong("expires");}}catch(Exception e){logout();}}
 private static java.security.Key key()throws Exception{KeyStore ks=KeyStore.getInstance("AndroidKeyStore");ks.load(null);if(!ks.containsAlias("rai_session")){KeyGenerator g=KeyGenerator.getInstance("AES","AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder("rai_session",KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return ks.getKey("rai_session",null);}
 static String token(){return System.currentTimeMillis()<expires?token:"";}
 static boolean active(){return !token().isEmpty();}
 static void logout(){token="";expires=0;if(context!=null)context.getSharedPreferences("rai_account",0).edit().clear().apply();}
 static void login(String email,String password)throws Exception{RequestBody body=new FormBody.Builder().add("email",email.trim()).add("password",password).add("domainApiKey","arSgRtwasD324SaA").build();JSONObject j;try(Response r=VodNetwork.client().newCall(new Request.Builder().url("https://www.raiplay.it/raisso/login/domain/app/social").header("Referer","https://www.raiplay.it/").header("Origin","https://www.raiplay.it").header("User-Agent",CbMixdropResolver.USER_AGENT).post(body).build()).execute()){if(!r.isSuccessful()||r.body()==null)throw new Exception("Accesso RaiPlay HTTP "+r.code());j=new JSONObject(r.body().string());}if(!"OK".equals(j.optString("response"))||j.optString("ua").isEmpty())throw new Exception("Accesso RaiPlay rifiutato · controlla credenziali o metodo di accesso");String auth=j.optString("authorization");long exp=System.currentTimeMillis()+3600000;try{String[] jwt=auth.split("\\.");exp=new JSONObject(new String(Base64.decode(jwt[1],Base64.URL_SAFE|Base64.NO_WRAP|Base64.NO_PADDING),"UTF-8")).getLong("exp")*1000;}catch(Exception ignored){}String ua=j.getString("ua");JSONObject session=new JSONObject().put("token",ua).put("expires",exp);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,key());String encoded=Base64.encodeToString(c.getIV(),Base64.NO_WRAP)+":"+Base64.encodeToString(c.doFinal(session.toString().getBytes("UTF-8")),Base64.NO_WRAP);context.getSharedPreferences("rai_account",0).edit().putString("session",encoded).apply();token=ua;expires=exp;}
}
