package it.carmine.streamplayer;
import android.app.*;import android.os.*;import android.content.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.util.concurrent.*;
/** Dedicated account screen; only the encrypted session is retained. */
public class RaiAccountActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private boolean destroyed;private TextView status;private EditText email,password;private Button login;
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private Button button(String text){Button b=new Button(this);b.setText(text);b.setAllCaps(false);UiTheme.navigation(b);return b;}
 public void onCreate(Bundle state){super.onCreate(state);VodNetwork.initialize(this);RaiAccount.init(this);getWindow().getDecorView().setSystemUiVisibility(5894);ScrollView scroll=new ScrollView(this);scroll.setBackgroundColor(UiTheme.background(this));LinearLayout body=new LinearLayout(this);body.setOrientation(1);body.setPadding(dp(32),dp(24),dp(32),dp(24));scroll.addView(body);setContentView(scroll);TextView heading=new TextView(this);heading.setText("RaiPlay · Account");heading.setTextSize(28);heading.setTypeface(UiTheme.medium(this));heading.setTextColor(UiTheme.accent(this));body.addView(heading);status=new TextView(this);status.setTextColor(UiTheme.TEXT);status.setPadding(0,dp(20),0,dp(20));body.addView(status);email=VodSettings.input(this,"","Email RaiPlay");email.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS);password=VodSettings.input(this,"","Password RaiPlay");password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);body.addView(email);body.addView(password);login=button("Accedi");body.addView(login);login.setOnClickListener(v->login());Button logout=button("Esci dall’account");body.addView(logout);logout.setOnClickListener(v->{RaiAccount.logout();update();});Button back=button("‹ Torna a RaiPlay");body.addView(back);back.setOnClickListener(v->finish());update();}
 private void update(){status.setText(RaiAccount.active()?"Accesso attivo · la sessione viene ripristinata all’apertura dell’app":"Accedi con email e password RaiPlay. La sessione resta salvata finché è valida; la password non viene conservata.");email.setVisibility(RaiAccount.active()?View.GONE:View.VISIBLE);password.setVisibility(email.getVisibility());login.setVisibility(email.getVisibility());if(!RaiAccount.active())email.requestFocus();}
 private void login(){String e=email.getText().toString(),p=password.getText().toString();if(e.trim().isEmpty()||p.isEmpty()){status.setText("Inserisci email e password");return;}login.setEnabled(false);status.setText("Accesso in corso…");worker.submit(()->{String error=null;try{RaiAccount.login(e,p);}catch(Exception ex){error=ex.getMessage();}final String message=error;runOnUiThread(()->{if(destroyed)return;password.setText("");login.setEnabled(true);if(message==null){setResult(RESULT_OK);update();}else status.setText(message);});});}
 protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
}
