package it.carmine.streamplayer;
import android.app.Activity;import android.os.*;import android.webkit.*;import android.widget.FrameLayout;import java.util.*;import org.json.*;
final class RaiCatalogLoader {
 interface Callback{void done(List<VodSource.Title> titles,String error);}
 private final WebView web;private final Handler ui=new Handler(Looper.getMainLooper());private boolean closed;private String script,query;private int mode,scans;private Callback callback;private final Queue<String> pages=new ArrayDeque<>();private final Map<String,VodSource.Title> titles=new LinkedHashMap<>();
 RaiCatalogLoader(Activity a,FrameLayout root){web=new WebView(a);web.setAlpha(0);web.setFocusable(false);root.addView(web,new FrameLayout.LayoutParams(1,1));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setUserAgentString(CbMixdropResolver.USER_AGENT);web.getSettings().setSupportMultipleWindows(false);web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView w,WebResourceRequest r){return !RaiPlayAdapter.owns(r.getUrl().toString());}});try(java.io.InputStream in=a.getAssets().open("rai-catalog.js")){java.io.ByteArrayOutputStream b=new java.io.ByteArrayOutputStream();byte[] buf=new byte[4096];int n;while((n=in.read(buf))!=-1)b.write(buf,0,n);script=b.toString("UTF-8");}catch(Exception e){script="(function(){return '[]'})";}}
 void load(String q,int m,Callback cb){query=q;mode=m;callback=cb;if(!q.isEmpty())pages.add("https://www.raiplay.it/ricerca.html?q="+VodSource.encode(q));else{if(m!=2)pages.add("https://www.raiplay.it/film");if(m!=1){pages.add("https://www.raiplay.it/serieitaliane");pages.add("https://www.raiplay.it/serieinternazionali");}}next();}
 private void next(){if(closed)return;String url=pages.poll();if(url==null||scans++>=3){callback.done(new ArrayList<>(titles.values()),titles.isEmpty()?"Nessun titolo trovato o catalogo RaiPlay non disponibile":"");close();return;}web.loadUrl(url);ui.postDelayed(()->poll(0),2200);}
 private void poll(int attempt){if(closed)return;web.evaluateJavascript(script+"("+JSONObject.quote(query)+",0)",raw->{if(closed)return;int count=0;try{JSONArray entries=new JSONArray(new JSONArray("["+raw+"]").getString(0));count=entries.length();for(int i=0;i<count;i++){JSONObject x=entries.getJSONObject(i);String type=x.optString("type","movie"),url=x.getString("url");if(!RaiPlayAdapter.owns(url)||mode==1&&type.equals("tv")||mode==2&&!type.equals("tv"))continue;titles.putIfAbsent(url,RaiLibrary.title(x.getString("title"),url,x.optString("image"),type));}}catch(Exception ignored){}if(count==0&&attempt<12)ui.postDelayed(()->poll(attempt+1),800);else next();});}
 void close(){if(closed)return;closed=true;ui.removeCallbacksAndMessages(null);web.stopLoading();if(web.getParent() instanceof android.view.ViewGroup)((android.view.ViewGroup)web.getParent()).removeView(web);web.destroy();}
}
