package it.carmine.streamplayer;
import java.util.*;import java.nio.charset.StandardCharsets;import java.io.IOException;import org.json.*;
import androidx.media3.exoplayer.drm.*;import androidx.media3.datasource.*;
/** Adapts the authorized license response to Android MediaDrm. No key extraction. */
final class RaiDrmCallback implements MediaDrmCallback {
 private final HttpMediaDrmCallback delegate;volatile String state="Richiesta licenza non ancora eseguita";
 RaiDrmCallback(String license,DataSource.Factory factory,Map<String,String> provided){delegate=new HttpMediaDrmCallback(license,true,factory);delegate.setKeyRequestProperty("Referer","https://www.raiplay.it/");delegate.setKeyRequestProperty("Origin","https://www.raiplay.it");for(Map.Entry<String,String> h:provided.entrySet())delegate.setKeyRequestProperty(h.getKey(),h.getValue());}
 public Response executeProvisionRequest(UUID uuid,ExoMediaDrm.ProvisionRequest request)throws MediaDrmCallbackException{try{return delegate.executeProvisionRequest(uuid,request);}catch(MediaDrmCallbackException e){state="Provisioning · "+description(e);throw e;}}
 public Response executeKeyRequest(UUID uuid,ExoMediaDrm.KeyRequest request)throws MediaDrmCallbackException{state="Richiesta licenza inviata";Response response;try{response=delegate.executeKeyRequest(uuid,request);}catch(MediaDrmCallbackException e){state="Licenza · "+description(e);throw e;}try{byte[] decoded=unwrap(response.data);state=decoded==response.data?"Licenza ricevuta in formato binario":"Licenza ricevuta e decodificata da JSON";return decoded==response.data?response:new Response(decoded);}catch(Exception e){state="Risposta licenza JSON non valida o senza licenza";throw new MediaDrmCallbackException(new DataSpec(android.net.Uri.parse("https://www.raiplay.it/")),android.net.Uri.EMPTY,Collections.emptyMap(),response.data.length,new IOException(state));}}
 static byte[] unwrap(byte[] input)throws Exception{int i=0;while(i<input.length&&(input[i]==32||input[i]==10||input[i]==13||input[i]==9))i++;if(i>=input.length)throw new IOException("Licenza vuota");if(input[i]!='{')return input;JSONObject j=new JSONObject(new String(input,StandardCharsets.UTF_8));String encoded=j.optString("license");if(encoded.isEmpty())throw new IOException("Licenza assente nella risposta JSON");byte[] bytes=java.util.Base64.getDecoder().decode(encoded);if(bytes.length==0)throw new IOException("Licenza vuota");return bytes;}
 static String description(Throwable error){Set<Throwable> seen=Collections.newSetFromMap(new IdentityHashMap<>());for(Throwable t=error;t!=null&&seen.add(t);t=t.getCause()){if(t instanceof HttpDataSource.InvalidResponseCodeException){int code=((HttpDataSource.InvalidResponseCodeException)t).responseCode;return "HTTP "+code+(code==401||code==403?" · autorizzazione rifiutata dal servizio":"");}if(t instanceof java.net.UnknownHostException)return "DNS non disponibile";if(t instanceof java.net.SocketTimeoutException)return "Tempo di attesa scaduto";if(t instanceof javax.net.ssl.SSLException)return "Errore TLS";}return "Errore di richiesta o risposta DRM";}
}
