package it.carmine.streamplayer;
import org.json.*;import java.net.URI;import java.util.*;import java.util.regex.*;import okhttp3.*;
final class RaiPlayAdapter {
 static boolean owns(String u){try{return "www.raiplay.it".equals(URI.create(u).getHost())||"raiplay.it".equals(URI.create(u).getHost());}catch(Exception e){return false;}}
 static String absolute(String p){return URI.create("https://www.raiplay.it/").resolve(p).toString();}
 static String get(String u)throws Exception{Request.Builder request=new Request.Builder().url(u).header("User-Agent",CbMixdropResolver.USER_AGENT).header("Referer","https://www.raiplay.it/");String host=URI.create(u).getHost();if((owns(u)||"mediapolisvod.rai.it".equals(host))&&RaiAccount.active())request.header("x-ua-token",RaiAccount.token());try(Response r=VodNetwork.client().newCall(request.build()).execute()){if(!r.isSuccessful()||r.body()==null)throw new Exception("RaiPlay HTTP "+r.code()+" · possibile limite geografico o accesso richiesto");return r.body().string();}}
 static JSONObject data(String page)throws Exception{String u=page.split("[?#]")[0];if(!u.endsWith(".json"))u=u.endsWith(".html")?u.substring(0,u.length()-5)+".json":u+".json";return new JSONObject(get(u));}
 static final class Entry {final String title,url;Entry(String t,String u){title=t;url=absolute(u);}}
 static List<Entry> entries(JSONObject j)throws Exception{List<Entry> out=new ArrayList<>();String first=j.optString("first_item_path");if(!first.isEmpty())out.add(new Entry("Riproduci · "+j.optString("name"),first));JSONArray blocks=j.optJSONArray("blocks");for(int i=0;blocks!=null&&i<blocks.length();i++){JSONArray sets=blocks.getJSONObject(i).optJSONArray("sets");for(int k=0;sets!=null&&k<sets.length();k++){JSONObject s=sets.getJSONObject(k);if(!s.optString("path_id").isEmpty())out.add(new Entry(s.optString("name","Stagione"),s.getString("path_id")));}}JSONArray items=j.optJSONArray("items");for(int i=0;items!=null&&i<items.length();i++){JSONObject s=items.getJSONObject(i);String path=s.optString("path_id",s.optString("weblink"));if(!path.isEmpty())out.add(new Entry(s.optString("name",s.optString("title","Episodio")),path));}return out;}
 static final class Stream {final String url,license;final Map<String,String> licenseHeaders;Stream(String u,String l){this(u,l,new LinkedHashMap<>());}Stream(String u,String l,Map<String,String> h){url=u;license=l;licenseHeaders=h;}}
 static Stream stream(JSONObject j)throws Exception{if(j.optBoolean("login_required")&&!RaiAccount.active())throw new Exception("Apri Account RaiPlay e accedi prima di riprodurre");JSONObject video=j.optJSONObject("video");if(video==null)throw new Exception("Dati video RaiPlay assenti");String u=video.optString("content_url");if(u.isEmpty())throw new Exception("URL video RaiPlay assente");if(!u.contains("relinkerServlet"))return new Stream(u,"");okhttp3.HttpUrl relink=okhttp3.HttpUrl.get(u.replace("relinkerServlet.mp4","relinkerServlet.htm")).newBuilder().setQueryParameter("output","56").build();return parse(get(relink.toString()));}
 static Stream parse(String xml)throws Exception{org.xmlpull.v1.XmlPullParser parser=android.util.Xml.newPullParser();parser.setInput(new java.io.StringReader(xml));String url="",license="";Map<String,String> licenseHeaders=new LinkedHashMap<>();for(int e=parser.getEventType();e!=org.xmlpull.v1.XmlPullParser.END_DOCUMENT;e=parser.next()){if(e!=org.xmlpull.v1.XmlPullParser.START_TAG)continue;String name=parser.getName();if("url".equals(name)&&"content".equals(parser.getAttributeValue(null,"type")))url=parser.nextText().trim();else if("license_url".equals(name)){String value=parser.nextText().trim();if(!value.isEmpty()){JSONObject l=new JSONObject(value);JSONArray a=l.optJSONArray("drmLicenseUrlValues");for(int i=0;a!=null&&i<a.length();i++){JSONObject item=a.getJSONObject(i);if("WIDEVINE".equalsIgnoreCase(item.optString("drm"))){license=item.optString("licenceUrl",item.optString("licenseUrl"));JSONObject headers=item.optJSONObject("headers");if(headers==null)headers=item.optJSONObject("http_headers");for(java.util.Iterator<String> it=headers==null?java.util.Collections.<String>emptyIterator():headers.keys();it.hasNext();){String key=it.next();if(key.matches("(?i)(?:Nv-Authorizations|Authorization|dt-custom-data|X-[A-Za-z0-9-]+)"))licenseHeaders.put(key,headers.getString(key));}license=RaiLicenseConfig.normalize(license,item.optString("operator"),licenseHeaders);break;}}}}}if(CbLinkTargets.uri(url)==null)throw new Exception("RaiPlay non restituisce un flusso HTTPS disponibile");if(!license.isEmpty()&&CbLinkTargets.uri(license)==null)throw new Exception("Licenza RaiPlay non valida");return new Stream(url,license,licenseHeaders);}
}
