package it.carmine.streamplayer;
import android.content.*;import org.json.*;import java.util.*;
/** A whitelist keeps tokens, credentials and cloud identity out of portable backups. */
final class SettingsBackup {
 static final Map<String,Set<String>> KEYS=new LinkedHashMap<>();
 static {allow("player","favorites","category","channel_source","resize","epg_url","liveCloudflareDns");allow("daddyLive","home");allow("vavoo","home");allow("gomstream","home");allow("vod","sources","active","feed","cloudflareDns","dnsProvider","unityManual","preferredSource");allow("vodPlayback","audioLanguage","subtitleLanguage","subtitlesDisabled");}
 private static void allow(String name,String... keys){KEYS.put(name,new HashSet<>(Arrays.asList(keys)));}
 static JSONObject export(Context c)throws Exception{JSONObject result=new JSONObject().put("schema",1).put("app","it.carmine.streamplayer"),settings=new JSONObject(),library=new JSONObject();for(String name:KEYS.keySet()){JSONObject group=new JSONObject();for(Map.Entry<String,?> e:c.getSharedPreferences(name,0).getAll().entrySet())if(KEYS.get(name).contains(e.getKey())){Object v=e.getValue();String type=v instanceof Boolean?"boolean":v instanceof Integer?"integer":v instanceof Long?"long":v instanceof Set?"set":"string";group.put(e.getKey(),new JSONObject().put("type",type).put("value",v instanceof Set?new JSONArray((Set<?>)v):v));}settings.put(name,group);}for(Map.Entry<String,?> e:VodLibrary.prefs(c).getAll().entrySet())if(e.getValue() instanceof String&&CloudRecords.payloadAllowed(e.getKey(),(String)e.getValue()))library.put(e.getKey(),e.getValue());return result.put("settings",settings).put("library",library);}
 static void restore(Context c,String text)throws Exception{if(text.length()>2*1024*1024)throw new Exception("Backup troppo grande");JSONObject root=new JSONObject(text);if(root.getInt("schema")!=1||!root.getString("app").equals("it.carmine.streamplayer"))throw new Exception("Formato backup non compatibile");JSONObject groups=root.getJSONObject("settings"),library=root.getJSONObject("library");Map<String,Map<String,Object>> prepared=new LinkedHashMap<>();for(Iterator<String> names=groups.keys();names.hasNext();){String name=names.next();if("events".equals(name))continue;if(!KEYS.containsKey(name))throw new Exception("Gruppo non consentito nel backup");JSONObject group=groups.getJSONObject(name);Map<String,Object> values=new LinkedHashMap<>();for(Iterator<String> keys=group.keys();keys.hasNext();){String key=keys.next();if(!KEYS.get(name).contains(key))throw new Exception("Impostazione non consentita");JSONObject item=group.getJSONObject(key);String type=item.getString("type");Object value=item.get("value");switch(type){case "string":if(!(value instanceof String)||((String)value).length()>200000)throw new Exception("Valore non valido");break;case "boolean":if(!(value instanceof Boolean))throw new Exception("Valore non valido");break;case "integer":if(!(value instanceof Number)||((Number)value).longValue()!=((Number)value).intValue())throw new Exception("Valore non valido");value=((Number)value).intValue();break;case "long":if(!(value instanceof Number))throw new Exception("Valore non valido");value=((Number)value).longValue();break;case "set":if(!(value instanceof JSONArray)||((JSONArray)value).length()>10000)throw new Exception("Valore non valido");Set<String> set=new HashSet<>();for(int i=0;i<((JSONArray)value).length();i++)set.add(((JSONArray)value).getString(i));value=set;break;default:throw new Exception("Tipo non valido");}
  boolean flag=key.equals("liveCloudflareDns")||key.equals("cloudflareDns")||key.equals("unityManual")||key.equals("subtitlesDisabled");if(key.equals("resize")&&(!(value instanceof Integer)||!Arrays.asList(0,3,4).contains(value)))throw new Exception("Formato video non valido");if(key.equals("channel_source")&&!Arrays.asList("VAVOO","GOMSTREAM").contains(value))throw new Exception("Fonte canali non valida");if(flag&&!(value instanceof Boolean)||key.equals("favorites")&&!(value instanceof Set)||!flag&&!key.equals("favorites")&&!key.equals("resize")&&!(value instanceof String))throw new Exception("Tipo impostazione non compatibile");if(key.equals("home")||key.equals("epg_url")||key.equals("feed")){String url=(String)value;if(!url.isEmpty()){java.net.URI uri=new java.net.URI(url);if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null)throw new Exception("URL non valido");}}if(key.equals("sources"))value=VodSettings.serialized(VodSettings.retained(VodSettings.parse((String)value)));values.put(key,value);}prepared.put(name,values);}
 for(Iterator<String> keys=library.keys();keys.hasNext();){String key=keys.next();if(!CloudRecords.payloadAllowed(key,library.getString(key)))throw new Exception("Titolo del backup non valido");}
 for(Map.Entry<String,Map<String,Object>> group:prepared.entrySet()){SharedPreferences.Editor edit=c.getSharedPreferences(group.getKey(),0).edit();for(Map.Entry<String,Object> e:group.getValue().entrySet()){Object v=e.getValue();if(v instanceof Boolean)edit.putBoolean(e.getKey(),(Boolean)v);else if(v instanceof Integer)edit.putInt(e.getKey(),(Integer)v);else if(v instanceof Long)edit.putLong(e.getKey(),(Long)v);else if(v instanceof Set)edit.putStringSet(e.getKey(),(Set<String>)v);else edit.putString(e.getKey(),(String)v);}edit.apply();}for(Iterator<String> keys=library.keys();keys.hasNext();){String key=keys.next();VodLibrary.put(c,key,library.getString(key));}c.getSharedPreferences("backup",0).edit().putLong("restoredAt",System.currentTimeMillis()).apply();VodNetwork.initialize(c);
 }
}
