package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.text.InputType;import android.widget.*;import org.json.*;import java.util.*;

/** TMDB is used only for metadata; playback sources are resolved separately. */
final class TmdbClient {
 static String key(Context c){try(java.io.InputStream in=c.getAssets().open("tmdb-api-key.txt")){java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] b=new byte[256];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toString("UTF-8").trim();}catch(Exception ignored){return "";}}
 static boolean enabled(Context c){return !key(c).isEmpty();}
 static JSONObject metadata(VodSource.Title t){JSONObject linked=t.json.optJSONObject("_metadata");return linked!=null?linked:(t.json.optBoolean("_tmdb")?t.json:null);}
 static String identity(VodSource.Title t){JSONObject linked=metadata(t);return linked==null?t.id:linked.optString("id",t.id);}
 static String scope(VodSource.Title t,VodSettings.Source source){return metadata(t)!=null?"tmdb":source.id;}
 static String endpoint(String path,String key){return "https://api.themoviedb.org/3"+path+(path.contains("?")?"&":"?")+"language=it-IT&api_key="+VodSource.encode(key);}
 static JSONObject request(String path,String key,VodSource.Fetcher f)throws Exception{return new JSONObject(f.get(endpoint(path,key),""));}
 static VodSource.Title convert(JSONObject raw,String forcedType)throws Exception{
  String type=raw.optString("media_type",forcedType);if(!type.equals("movie")&&!type.equals("tv"))return null;JSONObject j=new JSONObject();long tmdb=raw.getLong("id");j.put("id",tmdb*2+(type.equals("tv")?1:0));j.put("slug","tmdb-"+tmdb);j.put("tmdb_id",tmdb);j.put("_tmdb",true);j.put("type",type);j.put("name",raw.optString(type.equals("tv")?"name":"title"));j.put("original_name",raw.optString(type.equals("tv")?"original_name":"original_title"));j.put("plot",raw.optString("overview"));j.put("release_date",raw.optString(type.equals("tv")?"first_air_date":"release_date"));j.put("score",raw.optDouble("vote_average",0));String poster=raw.optString("poster_path",""),backdrop=raw.optString("backdrop_path","");if(!poster.isEmpty()&&!poster.equals("null"))j.put("_poster_url","https://image.tmdb.org/t/p/w500"+poster);if(!backdrop.isEmpty()&&!backdrop.equals("null"))j.put("_backdrop_url","https://image.tmdb.org/t/p/w1280"+backdrop);if(raw.has("seasons"))j.put("seasons",raw.getJSONArray("seasons"));if(raw.has("genres"))j.put("genres",raw.getJSONArray("genres"));if(raw.has("genre_ids"))j.put("genre_ids",raw.getJSONArray("genre_ids"));j.put("runtime",raw.optInt("runtime"));return new VodSource.Title(j,"");
 }
 static List<VodSource.Title> parse(JSONObject p,String forcedType)throws Exception{List<VodSource.Title> list=new ArrayList<>();JSONArray a=p.optJSONArray("results");if(a!=null)for(int i=0;i<a.length();i++){VodSource.Title t=convert(a.getJSONObject(i),forcedType);if(t!=null)list.add(t);}return list;}
 static List<VodSource.Title> catalog(int mode,String query,int page,String key,VodSource.Fetcher f)throws Exception{String type=mode==1?"movie":mode==2?"tv":"";if(query.equals("@@novita")){if(mode==0)return mixed(catalog(1,query,page,key,f),catalog(2,query,page,key,f),40);return parse(request("/trending/"+type+"/week?page="+page,key,f),type);}if(query.equals("@@releases")){if(mode==0)return mixed(catalog(1,query,page,key,f),catalog(2,query,page,key,f),40);return parse(request("/"+type+"/"+(mode==2?"on_the_air":"now_playing")+"?page="+page,key,f),type);}String path=!query.isEmpty()?"/search/"+(type.isEmpty()?"multi":type)+"?query="+VodSource.encode(query)+"&include_adult=false":type.isEmpty()?"/trending/all/week?":"/"+type+"/popular?";path+=(path.endsWith("?")?"":"&")+"page="+page;return parse(request(path,key,f),type);}
 static List<VodSource.Title> catalog(int mode,String query,int page,String key,VodSource.Fetcher f,int provider)throws Exception{if(provider<=0)return catalog(mode,query,page,key,f);if(!query.trim().isEmpty()&&page>1)return new ArrayList<>();if(mode==0)return mixed(catalog(1,query,page,key,f,provider),catalog(2,query,page,key,f,provider),40);String type=mode==2?"tv":"movie",wanted=VodProviders.normal(query);List<VodSource.Title> titles=new ArrayList<>();int last=query.trim().isEmpty()?page:25;for(int current=page;current<=last&&titles.size()<20;current++){String path="/discover/"+type+"?include_adult=false&include_video=false&sort_by=popularity.desc&watch_region=IT&with_watch_providers="+provider+"&page="+current;List<VodSource.Title> batch=parse(request(path,key,f),type);if(batch.isEmpty())break;if(!wanted.isEmpty())batch.removeIf(t->!VodProviders.normal(t.name).contains(wanted)&&!VodProviders.normal(t.json.optString("original_name")).contains(wanted));titles.addAll(batch);}return titles;}
 static List<VodSource.Title> home(String path,String forcedType,String key,VodSource.Fetcher f)throws Exception{return parse(request(path,key,f),forcedType);}
 static List<VodSource.Title> mixed(List<VodSource.Title> first,List<VodSource.Title> second,int limit){List<VodSource.Title> out=new ArrayList<>();Set<String> ids=new HashSet<>();for(int i=0;i<Math.max(first.size(),second.size())&&out.size()<limit;i++){if(i<first.size()&&ids.add(first.get(i).id))out.add(first.get(i));if(i<second.size()&&out.size()<limit&&ids.add(second.get(i).id))out.add(second.get(i));}return out;}
 static List<VodSource.Title> newReleases(String key,VodSource.Fetcher f)throws Exception{return mixed(home("/movie/now_playing?page=1","movie",key,f),home("/tv/on_the_air?page=1","tv",key,f),20);}
 static List<VodSource.Title> trending(String key,VodSource.Fetcher f)throws Exception{return home("/trending/all/week?page=1","",key,f);}
 static List<VodSource.Title> popularMovies(String key,VodSource.Fetcher f)throws Exception{return home("/movie/popular?page=1","movie",key,f);}
 static List<VodSource.Title> popularShows(String key,VodSource.Fetcher f)throws Exception{return home("/tv/popular?page=1","tv",key,f);}
 static List<VodSource.Title> recommendations(VodSource.Title seed,String key,VodSource.Fetcher f)throws Exception{if(seed==null)return trending(key,f);long id=seed.json.optLong("tmdb_id");if(id<=0)return trending(key,f);List<VodSource.Title> out=home("/"+(seed.series()?"tv":"movie")+"/"+id+"/recommendations?page=1",seed.series()?"tv":"movie",key,f);return out.isEmpty()?trending(key,f):out;}
 static final LinkedHashMap<Integer,String> PROVIDERS=new LinkedHashMap<>();static{PROVIDERS.put(8,"Netflix");PROVIDERS.put(119,"Prime Video");PROVIDERS.put(337,"Disney+");PROVIDERS.put(350,"Apple TV+");PROVIDERS.put(39,"NOW");PROVIDERS.put(531,"Paramount+");PROVIDERS.put(1899,"Max");PROVIDERS.put(110,"Infinity+");}
 static VodSource.Title details(VodSource.Title t,String key,VodSource.Fetcher f)throws Exception{return convert(request("/"+(t.series()?"tv":"movie")+"/"+t.json.getLong("tmdb_id"),key,f),t.series()?"tv":"movie");}
 static VodSource.Title details(long id,String type,String key,VodSource.Fetcher f)throws Exception{return convert(request("/"+type+"/"+id,key,f),type);}
 static JSONArray episodes(VodSource.Title t,int season,String key,VodSource.Fetcher f)throws Exception{long id=t.json.optLong("tmdb_id");if(id<=0)throw new IllegalArgumentException("ID TMDB non disponibile");JSONArray raw=request("/tv/"+id+"/season/"+season,key,f).optJSONArray("episodes"),out=new JSONArray();for(int i=0;raw!=null&&i<raw.length();i++){JSONObject e=raw.optJSONObject(i);if(e!=null)out.put(new JSONObject().put("id",e.optInt("id",e.optInt("episode_number"))).put("number",e.optInt("episode_number")).put("name",e.optString("name")));}return out;}
 /** Enriches one title already present in the provider catalogue; it never creates catalogue entries. */
 static VodSource.Title enrich(VodSource.Title source,String key,VodSource.Fetcher f)throws Exception{
  if(key.isEmpty()||metadata(source)!=null)return source;String type=source.series()?"tv":"movie";String path="/search/"+type+"?query="+VodSource.encode(source.name)+"&include_adult=false"+(source.year.isEmpty()?"":"&year="+source.year);JSONArray results=request(path,key,f).optJSONArray("results");JSONObject best=null;int score=-1;String wanted=VodProviders.normal(source.name),original=VodProviders.normal(source.json.optString("original_name"));
  for(int i=0;results!=null&&i<Math.min(results.length(),8);i++){JSONObject raw=results.optJSONObject(i);if(raw==null)continue;String name=raw.optString(type.equals("tv")?"name":"title"),other=raw.optString(type.equals("tv")?"original_name":"original_title");String a=VodProviders.normal(name),b=VodProviders.normal(other);int candidate=(a.equals(wanted)||b.equals(wanted)?4:0)+(!original.isEmpty()&&(a.equals(original)||b.equals(original))?2:0);String date=raw.optString(type.equals("tv")?"first_air_date":"release_date");if(!source.year.isEmpty()&&date.startsWith(source.year))candidate+=2;if(candidate>score){score=candidate;best=raw;}}
  if(best==null||score<4)return source;VodSource.Title meta=convert(best,type);JSONObject combined=new JSONObject(source.json.toString());if(!source.poster.isEmpty())combined.put("_poster_url",source.poster);combined.put("_metadata",meta.json);combined.put("tmdb_id",meta.json.optLong("tmdb_id"));if(meta.json.has("genre_ids"))combined.put("genre_ids",meta.json.getJSONArray("genre_ids"));if(meta.json.has("genres"))combined.put("genres",meta.json.getJSONArray("genres"));if(source.json.optString("release_date").isEmpty())combined.put("release_date",meta.json.optString("release_date"));if(!meta.poster.isEmpty())combined.put("_poster_url",meta.poster);if(!meta.plot.isEmpty())combined.put("plot",meta.plot);String originalName=meta.json.optString("original_name");if(!originalName.isEmpty())combined.put("original_name",originalName);return new VodSource.Title(combined,"");
 }
 static VodSource.Title merge(VodSource.Title full,VodSource.Title enriched)throws Exception{JSONObject metadata=metadata(enriched);if(metadata==null)return full;JSONObject combined=new JSONObject(full.json.toString());combined.put("_metadata",metadata);combined.put("tmdb_id",metadata.optLong("tmdb_id"));String poster=metadata.optString("_poster_url");if(!poster.isEmpty())combined.put("_poster_url",poster);String plot=metadata.optString("plot");if(!plot.isEmpty())combined.put("plot",plot);return new VodSource.Title(combined,"");}
 static String trailer(VodSource.Title title,String key,VodSource.Fetcher fetch)throws Exception{long id=title.json.optLong("tmdb_id");if(id<=0)return "";String path="/"+(title.series()?"tv":"movie")+"/"+id+"/videos?include_video_language=it,en";JSONArray videos=request(path,key,fetch).optJSONArray("results");JSONObject best=null;int score=-1;for(int i=0;videos!=null&&i<videos.length();i++){JSONObject video=videos.optJSONObject(i);if(video==null||!"YouTube".equals(video.optString("site"))||!video.optString("key").matches("[a-zA-Z0-9_-]{6,32}"))continue;int points=("it".equals(video.optString("iso_639_1"))?10:0)+("Trailer".equals(video.optString("type"))?4:0)+(video.optBoolean("official")?1:0);if(points>score){score=points;best=video;}}return best==null?"":"https://www.youtube.com/embed/"+best.getString("key")+"?autoplay=1&playsinline=1";}
 static void credits(Activity a){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(24,12,24,12);ImageView logo=new ImageView(a);logo.setAdjustViewBounds(true);logo.setMaxHeight(60);try(java.io.InputStream in=a.getAssets().open("tmdb-logo.png")){logo.setImageDrawable(android.graphics.drawable.Drawable.createFromStream(in,"TMDB"));box.addView(logo);}catch(Exception ignored){}TextView t=new TextView(a);t.setText("This product uses the TMDB API but is not endorsed or certified by TMDB.\n\nDati e immagini: The Movie Database (TMDB).\nhttps://www.themoviedb.org");t.setTextColor(UiTheme.TEXT);box.addView(t);new AlertDialog.Builder(a).setTitle("Crediti TMDB").setView(box).setPositiveButton("Chiudi",null).show();}
}
