package it.carmine.streamplayer;
import android.app.*;import android.content.*;import android.os.*;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;
public class TvSearchActivity extends Activity {
 private EditText query;private TextView status;private ListView results;private JSONArray channels=new JSONArray();private final List<Object> entries=new ArrayList<>();
 @Override public void onCreate(Bundle state){super.onCreate(state);try{channels=new JSONArray(getIntent().getStringExtra("channels"));}catch(Exception ignored){}LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(24,16,24,12);root.setBackgroundColor(0xff151619);setContentView(root);Button back=new Button(this);back.setAllCaps(false);back.setText("‹ TV · Ricerca canali");UiTheme.navigation(back);root.addView(back);back.setOnClickListener(v->finish());query=VodSettings.input(this,getIntent().getStringExtra("query"),"Cerca canali");query.setTag("tvSearchQuery");root.addView(query);status=new TextView(this);status.setTextColor(UiTheme.TEXT);root.addView(status);results=new ListView(this);results.setTag("tvSearchResults");root.addView(results,new LinearLayout.LayoutParams(-1,0,1));query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int n,int after){}public void onTextChanged(CharSequence s,int st,int before,int n){filter();}public void afterTextChanged(Editable e){}});query.setOnEditorActionListener((v,a,e)->{results.requestFocus();return true;});results.setOnItemClickListener((p,v,n,id)->{Object entry=entries.get(n);if(entry instanceof JSONObject){setResult(RESULT_OK,new Intent().putExtra("channelKey",((JSONObject)entry).optString("key")));finish();}});filter();}
 static boolean matches(String name,String needle){return key(name).contains(key(needle));}
 static String key(String s){return java.text.Normalizer.normalize(s,java.text.Normalizer.Form.NFD).replaceAll("\\p{M}","").toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]","");}
 private void filter(){entries.clear();List<String> labels=new ArrayList<>();String needle=query.getText().toString().trim();for(int i=0;i<channels.length();i++){JSONObject c=channels.optJSONObject(i);if(c!=null&&matches(c.optString("name"),needle)){entries.add(c);labels.add("CANALE · "+DisplayNames.channel(c.optString("name")));}}results.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,labels){@Override public View getView(int n,View old,ViewGroup parent){TextView row=(TextView)super.getView(n,old,parent);row.setTextColor(UiTheme.TEXT);row.setTypeface(getResources().getFont(R.font.inter));row.setTextSize(17);return row;}});status.setText(entries.size()+" risultati · canali della fonte selezionata");}
}
