package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.os.*;import android.graphics.Color;import android.graphics.drawable.*;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;
import org.json.*;import java.util.*;import java.util.concurrent.*;

/** TV-first catalogue; network requests never run on the UI thread. */
public class VodCatalogueActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());
 private Future<?> task;private Runnable catalogDeadline;private int generation,detailGeneration,mode,page=1,visibleLimit=20,providerId;private long launchTmdbId;private boolean appendNext,recentFirst=true,searchPage,directDetail,detailOpen;private String sectionKind="",sectionTitle="";private FrameLayout rootFrame;private VodDrawer.Controller drawer;private Button trailer;private List<VodSource.Title> catalogue=new ArrayList<>();private String nextPath="",genreFilter="",yearFilter="",providerName="";private Button more;private final ExecutorService providerWorkers=Executors.newFixedThreadPool(4);private final ExecutorService metadataWorkers=Executors.newFixedThreadPool(2);private boolean destroyed,paused;private VodSettings.Source source;
 private List<VodSource.Title> items=new ArrayList<>();private VodSource.Title selected;private JSONObject details;
 private TextView status,name,meta,plot,resumeLabel;private LinearLayout castStrip;private ProgressBar detailProgress;private EditText search;private GridView grid;private LinearLayout catalogueColumn;private ScrollView seasonScroll;private LinearLayout seasonGrid;private ProgrammeArtwork image;private Button play,favorite,seasons,sourceButton,watchlist,nextEpisode;private int returnPosition,returnTop,themeAtCreate;private String returnId="",returnFocus="";private long resumeOverride=-1;private int resumeSeason,resumeEpisode;private VodSource.Title lastWanted;private final Map<String,VodProviders.Match> matchCache=new ConcurrentHashMap<>();private ArtworkStore artwork;private android.content.SharedPreferences libraryPrefs;private final Runnable libraryRefresh=()->{if(paused||destroyed)return;if(mode>=3){rememberGrid();load(false);}else if(selected!=null){updateFavorite();updateProgress();}};private final android.content.SharedPreferences.OnSharedPreferenceChangeListener libraryListener=(prefs,key)->{if(!paused&&!destroyed){ui.removeCallbacks(libraryRefresh);ui.postDelayed(libraryRefresh,300);}};
 protected VodSource.Fetcher fetcher(){return VodSource.HTTP;}protected boolean imagesEnabled(){return true;}
 private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(UiTheme.TEXT);return t;}
 private Button button(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setMinWidth(0);b.setMinimumWidth(0);b.setTextSize(14);UiTheme.navigation(b);return b;}
 private StateListDrawable focus(){StateListDrawable d=new StateListDrawable();GradientDrawable a=new GradientDrawable();a.setColor(0x334f3c20);a.setStroke(dp(2),UiTheme.accent(this));a.setCornerRadius(dp(8));d.addState(new int[]{android.R.attr.state_focused},a);d.addState(new int[]{android.R.attr.state_pressed},a);d.addState(new int[]{},new ColorDrawable(Color.TRANSPARENT));return d;}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);themeAtCreate=UiTheme.selected(this);VodNetwork.initialize(this);getWindow().getDecorView().setSystemUiVisibility(5894);artwork=new ArtworkStore(this,imagesEnabled());Intent launch=getIntent();searchPage=launch.getBooleanExtra("searchPage",false);directDetail=launch.getBooleanExtra("directDetail",false);sectionKind=launch.getStringExtra("sectionKind")==null?"":launch.getStringExtra("sectionKind");sectionTitle=launch.getStringExtra("sectionTitle")==null?"Catalogo":launch.getStringExtra("sectionTitle");mode=launch.getIntExtra("startMode",0);launchTmdbId=launch.getLongExtra("openTmdbId",0);providerId=launch.getIntExtra("providerId",0);providerName=launch.getStringExtra("providerName")==null?"":launch.getStringExtra("providerName");
  rootFrame=new FrameLayout(this);rootFrame.setBackgroundColor(UiTheme.background(this));setContentView(rootFrame);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setPadding(dp(16),dp(10),dp(16),dp(8));root.setBackgroundColor(UiTheme.background(this));rootFrame.addView(root,new FrameLayout.LayoutParams(-1,-1));TextView heading=text(sectionTitle,24);heading.setTypeface(UiTheme.medium(this));heading.setTextColor(UiTheme.accent(this));root.addView(heading,new LinearLayout.LayoutParams(-1,dp(42)));
  LinearLayout nav=new LinearLayout(this);nav.setTag("vodTypeFilters");nav.setVisibility((sectionKind.equals("novita")||sectionKind.equals("releases")||sectionKind.equals("platform"))?View.VISIBLE:View.GONE);root.addView(nav,new LinearLayout.LayoutParams(-1,dp(44)));Button movies=button("Film");Button series=button("Serie TV");nav.addView(movies,new LinearLayout.LayoutParams(0,-1,1));nav.addView(series,new LinearLayout.LayoutParams(0,-1,1));movies.setOnClickListener(v->{mode=1;reloadSection();});series.setOnClickListener(v->{mode=2;reloadSection();});
  LinearLayout query=new LinearLayout(this);query.setTag("vodSearchBar");query.setVisibility(searchPage||providerId>0||sectionKind.equals("film")||sectionKind.equals("series")?View.VISIBLE:View.GONE);root.addView(query,new LinearLayout.LayoutParams(-1,dp(44)));search=new EditText(this);search.setTag("vodSearch");search.setSingleLine(true);search.setHint(providerId>0?"Cerca su "+providerName:"Cerca in tutto TMDB");search.setTextColor(UiTheme.TEXT);search.setHintTextColor(0xffa6a6aa);search.setTextSize(15);search.setImeOptions(EditorInfo.IME_ACTION_SEARCH);query.addView(search,new LinearLayout.LayoutParams(0,-1,1));Button go=button("Cerca");query.addView(go,new LinearLayout.LayoutParams(dp(95),-1));if(searchPage||sectionKind.equals("film")||sectionKind.equals("series")){Button year=button("Anno ▾");query.addView(year,new LinearLayout.LayoutParams(dp(104),-1));year.setOnClickListener(v->selectYear());Button genre=button("Generi ▾");query.addView(genre,new LinearLayout.LayoutParams(dp(116),-1));genre.setOnClickListener(v->selectGenre());}go.setOnClickListener(v->{visibleLimit=20;reloadSection();});search.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_SEARCH){visibleLimit=20;reloadSection();return true;}return false;});
  status=text("VOD · caricamento…",12);status.setTag("vodStatus");status.setTextColor(0xffa6a6aa);root.addView(status,new LinearLayout.LayoutParams(-1,dp(30)));
  LinearLayout body=new LinearLayout(this);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));catalogueColumn=new LinearLayout(this);catalogueColumn.setOrientation(LinearLayout.VERTICAL);body.addView(catalogueColumn,new LinearLayout.LayoutParams(0,-1,.59f));grid=new GridView(this);grid.setTag("vodGrid");grid.setId(View.generateViewId());grid.setNumColumns(getResources().getDisplayMetrics().widthPixels>=dp(700)?3:2);grid.setHorizontalSpacing(dp(10));grid.setVerticalSpacing(dp(10));grid.setPadding(0,0,dp(12),0);grid.setSelector(focus());grid.setDrawSelectorOnTop(true);grid.setStretchMode(GridView.STRETCH_COLUMN_WIDTH);catalogueColumn.addView(grid,new LinearLayout.LayoutParams(-1,0,1));seasonScroll=new ScrollView(this);seasonScroll.setFillViewport(true);seasonScroll.setVisibility(View.GONE);
  seasonGrid=new LinearLayout(this);seasonGrid.setOrientation(LinearLayout.VERTICAL);seasonGrid.setPadding(dp(12),dp(6),dp(12),dp(6));
  seasonScroll.addView(seasonGrid);catalogueColumn.addView(seasonScroll,new LinearLayout.LayoutParams(-1,0,1));more=button("Altri 20 ›");more.setTag("vodMore");more.setId(View.generateViewId());catalogueColumn.addView(more,new LinearLayout.LayoutParams(-1,dp(44)));more.setVisibility(View.GONE);more.setOnClickListener(v->showMore());more.setNextFocusUpId(grid.getId());
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);body.addView(scroll,new LinearLayout.LayoutParams(0,-1,.41f));LinearLayout info=new LinearLayout(this);info.setOrientation(1);info.setPadding(dp(10),0,0,dp(12));scroll.addView(info);image=new ProgrammeArtwork(this);image.setScaleType(directDetail?ImageView.ScaleType.CENTER_CROP:ImageView.ScaleType.FIT_CENTER);info.addView(image,new LinearLayout.LayoutParams(-1,dp(directDetail?235:178)));name=text("Scegli un titolo",22);name.setTypeface(UiTheme.medium(this));info.addView(name);meta=text("",12);meta.setTextColor(UiTheme.accent(this));info.addView(meta);play=button("▶ Guarda");play.setTag("vodPlay");play.setId(View.generateViewId());info.addView(play,new LinearLayout.LayoutParams(-1,dp(48)));play.setOnClickListener(v->watch());play.setOnLongClickListener(v->{if(selected!=null)findSources(selected,false);return true;});seasons=button("▶ Episodi");info.addView(seasons,new LinearLayout.LayoutParams(-1,dp(44)));seasons.setOnClickListener(v->{if(selected!=null){if(selected.json.optBoolean("_tmdb"))showSeasonPicker(selected);else chooseSeason(selected,catalogueSource());}});trailer=button("▷ Trailer");trailer.setTag("vodTrailer");info.addView(trailer,new LinearLayout.LayoutParams(-1,dp(44)));trailer.setOnClickListener(v->trailer());Button alternatives=button("Altre fonti ▾");alternatives.setTag("vodAlternatives");info.addView(alternatives,new LinearLayout.LayoutParams(-1,dp(44)));alternatives.setOnClickListener(v->{if(selected!=null)findSources(selected,false);});favorite=button("☆ Aggiungi ai preferiti");info.addView(favorite,new LinearLayout.LayoutParams(-1,dp(44)));favorite.setOnClickListener(v->{if(selected!=null){VodLibrary.favorite(this,TmdbClient.scope(selected,source),selected);updateFavorite();if(mode==3)load(false);}});watchlist=button("＋ Da vedere");watchlist.setTag("vodWatchlist");info.addView(watchlist,new LinearLayout.LayoutParams(-1,dp(44)));watchlist.setOnClickListener(v->{if(selected!=null){VodLibrary.watchlist(this,TmdbClient.scope(selected,source),selected);updateFavorite();if(mode==5)load(false);}});nextEpisode=button("▶ Episodio successivo");nextEpisode.setTag("vodNextEpisode");info.addView(nextEpisode,new LinearLayout.LayoutParams(-1,dp(44)));nextEpisode.setVisibility(View.GONE);nextEpisode.setOnClickListener(v->resumeNext());plot=text("",15);plot.setPadding(0,dp(16),0,dp(16));info.addView(plot);
  TextView castHeading=text("Cast",19);castHeading.setTextColor(UiTheme.accent(this));info.addView(castHeading);HorizontalScrollView castScroll=new HorizontalScrollView(this);info.addView(castScroll,new LinearLayout.LayoutParams(-1,dp(134)));castStrip=new LinearLayout(this);castStrip.setOrientation(LinearLayout.HORIZONTAL);castScroll.addView(castStrip);
  TextView footer=text("OK: scheda · BACK: menu VOD · pressione lunga: preferiti e cronologia",11);footer.setTextColor(0xffa6a6aa);root.addView(footer,new LinearLayout.LayoutParams(-1,dp(24)));
  grid.setNextFocusRightId(play.getId());play.setNextFocusLeftId(grid.getId());favorite.setNextFocusLeftId(grid.getId());seasons.setNextFocusLeftId(grid.getId());grid.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int n,long id){if(n<items.size())show(items.get(n));}});grid.setOnItemClickListener((p,v,n,id)->{detailOpen=true;loadDetails(items.get(n),true);});
  grid.setOnItemLongClickListener((p,v,n,id)->{titleMenu(items.get(n));return true;});play.setEnabled(false);favorite.setEnabled(false);watchlist.setEnabled(false);seasons.setVisibility(View.GONE);if(saved!=null){mode=saved.getInt("mode",mode);search.setText(saved.getString("query",""));returnPosition=saved.getInt("position");returnTop=saved.getInt("top");returnId=saved.getString("title","");returnFocus=saved.getString("focus","");providerId=saved.getInt("providerId",providerId);providerName=saved.getString("providerName",providerName);sectionKind=saved.getString("sectionKind",sectionKind);sectionTitle=saved.getString("sectionTitle",sectionTitle);searchPage=saved.getBoolean("searchPage",searchPage);directDetail=saved.getBoolean("directDetail",directDetail);detailOpen=saved.getBoolean("detailOpen",false);}else search.setText(launch.getStringExtra("startQuery")==null?"":launch.getStringExtra("startQuery"));if(!searchPage&&providerId==0&&search.length()==0&&(sectionKind.equals("novita")||sectionKind.equals("releases")))search.setText("@@"+sectionKind);if(directDetail){catalogueColumn.setVisibility(View.GONE);heading.setText("Dettaglio · "+sectionTitle);}// No persistent VOD sidebar on subpages.
  drawer=null;load(true);if(searchPage||getIntent().getBooleanExtra("focusSearch",false))search.postDelayed(()->search.requestFocus(),350);
 }
 protected void load(boolean refreshSources){if(catalogDeadline!=null)ui.removeCallbacks(catalogDeadline);final int request=++generation;++detailGeneration;if(task!=null)task.cancel(true);final boolean append=appendNext;appendNext=false;if(!append)page=1;final int requestedPage=page;final String q=search.getText().toString().trim();final int selectedMode=mode;final long requestedTmdbId=launchTmdbId;final String requestedPath=append?nextPath:"";final boolean tmdb=TmdbClient.enabled(this);final String apiKey=TmdbClient.key(this);final int wanted=append?items.size()+20:visibleLimit;source=catalogueSource();if(!append)nextPath="";final String cacheQuery=(providerId>0?q+"#provider="+providerId:q)+"#year="+yearFilter+"#genre="+genreFilter;final String cacheKey=VodCache.key(source.tmdb(),source,selectedMode,cacheQuery,requestedPage);if(!append&&selectedMode<3&&requestedTmdbId<=0){List<VodSource.Title> cached=VodCache.read(this,cacheKey);if(!cached.isEmpty()){catalogue=cached;visibleLimit=Math.max(20,Math.min(visibleLimit,filteredCatalogue().size()));items=new ArrayList<>(filteredCatalogue().subList(0,Math.min(visibleLimit,filteredCatalogue().size())));selected=null;render();restoreGrid();}}status.setText(items.isEmpty()?"Aggiornamento catalogo "+source.name+"…":"Catalogo "+source.name+" salvato · aggiornamento in corso…");
  if(refreshSources)providerWorkers.submit(()->{try{VodSettings.refresh(this,fetcher());}catch(Exception ignored){}});
  long deadlineMs=source.vixsrc()?90000:genreFilter.isEmpty()&&yearFilter.isEmpty()?25000:60000;
  catalogDeadline=()->{if(destroyed||request!=generation)return;++generation;if(task!=null)task.cancel(true);status.setText("Catalogo: tempo di attesa scaduto · premi ↻ o controlla la rete");};ui.postDelayed(catalogDeadline,deadlineMs);

  task=worker.submit(()->{try{final VodSettings.Source s=catalogueSource();List<VodSource.Title> result;String next="";
   if(selectedMode>=3){VodSettings.Source scope=tmdb?new VodSettings.Source("tmdb","TMDB",s.url):s;result=selectedMode==5?VodLibrary.watchlistTitles(this,scope):VodLibrary.titles(this,scope,selectedMode==4);if(selectedMode==4)result.removeIf(t->{JSONObject h=VodLibrary.latest(this,scope.id,TmdbClient.identity(t));return h!=null&&h.optBoolean("completed")&&!hasNext(h);});}else{List<VodSource.Title> gathered=append?new ArrayList<>(catalogue):new ArrayList<>();Set<String> ids=new HashSet<>();for(VodSource.Title title:gathered)ids.add(title.id);int scanned=0;if(s.tmdb()&&requestedTmdbId>0&&!append){gathered.add(TmdbClient.details(requestedTmdbId,selectedMode==2?"tv":"movie",apiKey,fetcher()));}else if(s.tmdb()){int current=pageFrom(requestedPath,requestedPage);do{List<VodSource.Title> batch=(searchPage&&selectedMode==1&&q.isEmpty()&&(!yearFilter.isEmpty()||!genreFilter.isEmpty())?TmdbClient.discoverMovies(yearFilter,genreFilter,current++,apiKey,fetcher()):TmdbClient.catalog(selectedMode,q,current++,apiKey,fetcher(),providerId));for(VodSource.Title title:batch)if(ids.add(title.id))gathered.add(title);next=batch.isEmpty()?"":"page:"+current;scanned++;}while(!next.isEmpty()&&VodCatalogue.filter(gathered,genreFilter,yearFilter,recentFirst).size()<wanted&&scanned<25&&!Thread.currentThread().isInterrupted());}else if(s.cinesearch()){for(VodSource.Title title:CineSearch.catalog(s,selectedMode,q,fetcher()))if(ids.add(title.id))gathered.add(title);}else if(s.vixsrc()){int current=pageFrom(requestedPath,requestedPage);do{VixCatalog.Page batch=VixCatalog.catalog(s.url,selectedMode,q,current++,apiKey,fetcher());for(VodSource.Title title:batch.titles)if(ids.add(title.id))gathered.add(title);next=batch.more?"page:"+current:"";scanned++;}while(!next.isEmpty()&&VodCatalogue.filter(gathered,genreFilter,yearFilter,recentFirst).size()<wanted&&scanned<25&&!Thread.currentThread().isInterrupted());}else{String path=!requestedPath.isEmpty()?requestedPath:!q.isEmpty()?"/it/search?q="+VodSource.encode(q):selectedMode==1?"/it/movies":selectedMode==2?"/it/shows":"/";do{JSONObject response=VodSource.page(s.url,path,fetcher());List<VodSource.Title> batch=VodSource.catalog(response,s.url);if(selectedMode==1)batch.removeIf(VodSource.Title::series);if(selectedMode==2)batch.removeIf(t->!t.series());if(tmdb&&(!genreFilter.isEmpty()||!yearFilter.isEmpty()))batch=enrichForFilters(batch,apiKey);for(VodSource.Title title:batch)if(ids.add(title.id))gathered.add(title);next=VodCatalogue.next(response,s.url,path);path=next;scanned++;}while(!next.isEmpty()&&VodCatalogue.filter(gathered,genreFilter,yearFilter,recentFirst).size()<wanted&&scanned<25&&!Thread.currentThread().isInterrupted());}result=gathered;}
   if(selectedMode<3&&requestedTmdbId<=0)VodCache.save(this,cacheKey,result);final String followingPath=next;runOnUiThread(()->{if(destroyed||request!=generation)return;ui.removeCallbacks(catalogDeadline);source=s;int previous=items.size();catalogue=new ArrayList<>(result);nextPath=followingPath;selected=null;details=null;int restoreLimit=visibleLimit;for(int k=0;k<filteredCatalogue().size();k++)if(filteredCatalogue().get(k).id.equals(returnId))restoreLimit=((k/20)+1)*20;visibleLimit=append?previous+20:Math.max(20,restoreLimit);revealCatalogue(visibleLimit);if(!items.isEmpty()){int pos=append?Math.min(previous,items.size()-1):0;boolean openDirect=launchTmdbId>0&&!append;if(openDirect){for(int k=0;k<items.size();k++)if(items.get(k).json.optLong("tmdb_id")==launchTmdbId){pos=k;break;}launchTmdbId=0;}grid.setSelection(pos);show(items.get(pos));if(!append){if(!returnId.isEmpty()){rememberSelectionAfterLoad();restoreGrid();}else{final int chosen=pos;grid.post(()->{grid.setSelection(chosen);grid.requestFocus();if(openDirect)loadDetails(items.get(chosen),true);});}}}else{name.setText("Nessun titolo");plot.setText("Prova una ricerca oppure scegli un’altra sezione.");image.setImageDrawable(null);play.setEnabled(false);favorite.setEnabled(false);seasons.setVisibility(View.GONE);}});if(tmdb&&!s.tmdb()&&!s.vixsrc()&&!s.cinesearch()&&selectedMode<3&&!result.isEmpty()&&genreFilter.isEmpty()&&yearFilter.isEmpty())enrichCatalogue(request,new ArrayList<>(result),apiKey,cacheKey);
  }catch(Exception|LinkageError e){runOnUiThread(()->{if(destroyed||request!=generation)return;ui.removeCallbacks(catalogDeadline);status.setText("Catalogo non disponibile · "+VodNetwork.error(e)+" · premi Sito o ↻");if(http403(e))offerSite();});}});
 }
 private static int pageFrom(String path,int fallback){if(path!=null&&path.startsWith("page:"))try{return Math.max(1,Integer.parseInt(path.substring(5)));}catch(Exception ignored){}return Math.max(1,fallback);}
 private List<VodSource.Title> enrichForFilters(List<VodSource.Title> titles,String apiKey){if(apiKey==null||apiKey.isEmpty())return titles;List<Future<VodSource.Title>> futures=new ArrayList<>();for(VodSource.Title title:titles)futures.add(metadataWorkers.submit(()->{try{return TmdbClient.enrich(title,apiKey,fetcher());}catch(Exception ignored){return title;}}));List<VodSource.Title> result=new ArrayList<>();for(int i=0;i<futures.size();i++)try{result.add(futures.get(i).get(8,TimeUnit.SECONDS));}catch(Exception ignored){result.add(titles.get(i));}return result;}
 private List<VodSource.Title> filteredCatalogue(){return VodCatalogue.filter(catalogue,genreFilter,yearFilter,recentFirst);}
 private void showMore(){if(filteredCatalogue().size()>items.size()){int previous=items.size();visibleLimit=items.size()+20;revealCatalogue(visibleLimit);grid.setSelection(previous);grid.requestFocus();}else if(!nextPath.isEmpty()){appendNext=true;page++;load(false);}}
 private void revealCatalogue(int limit){List<VodSource.Title> filtered=filteredCatalogue();visibleLimit=Math.max(20,limit);items=new ArrayList<>(filtered.subList(0,Math.min(visibleLimit,filtered.size())));render();boolean available=items.size()<filtered.size()||!nextPath.isEmpty();more.setVisibility(available?View.VISIBLE:View.GONE);more.setText("Altri 20  ›");catalogueStatus();}
 private void catalogueStatus(){status.setText((source==null?catalogueSource().name:source.name)+" · "+items.size()+" / "+filteredCatalogue().size()+" titoli"+(providerName.isEmpty()?"":" · "+providerName+" (Italia)")+(!genreFilter.isEmpty()?" · "+genreFilter:"")+(!yearFilter.isEmpty()?" · "+yearFilter:"")+(recentFirst?" · aggiunti di recente":" · A–Z"));}
 private void applyFilters(){visibleLimit=20;if(filteredCatalogue().size()<20&&!nextPath.isEmpty()){appendNext=true;page++;load(false);return;}revealCatalogue(20);if(!items.isEmpty()){selected=null;show(items.get(0));grid.setSelection(0);grid.requestFocus();}}
 private void selectYear(){ArrayList<String> years=new ArrayList<>();years.add("Tutti gli anni");int latest=java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);for(int i=latest;i>=1900;i--)years.add(String.valueOf(i));new AlertDialog.Builder(this).setTitle("Film per anno").setItems(years.toArray(new String[0]),(d,n)->{yearFilter=n==0?"":years.get(n);genreFilter="";mode=sectionKind.equals("series")?2:1;search.setText("");catalogue.clear();items.clear();returnId="";load(false);}).show();}
 private void selectGenre(){String[] names={"Tutti i generi","Azione","Avventura","Animazione","Commedia","Crime","Documentario","Drammatico","Famiglia","Fantasy","Storia","Horror","Musica","Mistero","Romantico","Fantascienza","Thriller","Guerra","Western"};new AlertDialog.Builder(this).setTitle("Film per genere").setItems(names,(d,n)->{genreFilter=n==0?"":names[n];yearFilter="";mode=sectionKind.equals("series")?2:1;search.setText("");catalogue.clear();items.clear();returnId="";load(false);}).show();}
 private void filters(){LinearLayout box=new LinearLayout(this);box.setOrientation(1);box.setPadding(dp(16),dp(8),dp(16),dp(8));TextView help=text("L’app continua a leggere TMDB finché trova almeno 20 titoli compatibili. Le piattaforme indicano la disponibilità del catalogo in Italia.",14);box.addView(help);Spinner genres=new Spinner(this);List<String> labels=new ArrayList<>();labels.add("Tutti i generi");labels.addAll(VodCatalogue.genres(catalogue));if(!genreFilter.isEmpty()&&!labels.contains(genreFilter))labels.add(genreFilter);genres.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels));genres.setSelection(Math.max(0,labels.indexOf(genreFilter)));box.addView(genres);EditText year=VodSettings.input(this,yearFilter,"Anno · lascia vuoto per tutti");year.setInputType(android.text.InputType.TYPE_CLASS_NUMBER);box.addView(year);Spinner platforms=new Spinner(this);List<String> platformLabels=new ArrayList<>();List<Integer> platformIds=new ArrayList<>();platformLabels.add("Tutte le piattaforme");platformIds.add(0);for(Map.Entry<Integer,String> entry:TmdbClient.PROVIDERS.entrySet()){platformIds.add(entry.getKey());platformLabels.add(entry.getValue());}platforms.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,platformLabels));platforms.setSelection(Math.max(0,platformIds.indexOf(providerId)));box.addView(platforms);Spinner order=new Spinner(this);String[] orders={"Aggiunti di recente","Titolo A–Z"};order.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,orders));order.setSelection(recentFirst?0:1);box.addView(order);new AlertDialog.Builder(this).setTitle("Genere, anno, piattaforma").setView(box).setPositiveButton("Applica",(d,n)->{genreFilter=genres.getSelectedItemPosition()==0?"":labels.get(genres.getSelectedItemPosition());yearFilter=year.getText().toString().trim();recentFirst=order.getSelectedItemPosition()==0;int chosen=platformIds.get(platforms.getSelectedItemPosition());boolean reload=chosen!=providerId;providerId=chosen;providerName=providerId==0?"":platformLabels.get(platforms.getSelectedItemPosition());if(reload){catalogue.clear();items.clear();returnId="";load(false);}else applyFilters();}).setNeutralButton("Azzera",(d,n)->{boolean reload=providerId!=0;genreFilter="";yearFilter="";providerId=0;providerName="";recentFirst=true;if(reload)load(false);else applyFilters();}).setNegativeButton("Chiudi",null).show();}
 private void trailer(){if(selected==null)return;final VodSource.Title wanted=selected;final int request=++detailGeneration;status.setText("Ricerca trailer · "+wanted.name);worker.submit(()->{try{VodSource.Title enriched=TmdbClient.enrich(wanted,TmdbClient.key(this),fetcher());String url=TmdbClient.trailer(enriched,TmdbClient.key(this),fetcher());runOnUiThread(()->{if(destroyed||request!=detailGeneration)return;status.setText(wanted.name);if(url.isEmpty()){Toast.makeText(this,"Trailer non disponibile",Toast.LENGTH_SHORT).show();return;}startActivity(new Intent(this,VodBrowserActivity.class).putExtra("url",url).putExtra("title","Trailer · "+wanted.name));});}catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("Trailer non disponibile · "+VodNetwork.error(e));});}});}
 private boolean siteDialogShown;
 private static boolean http403(Throwable e){for(Throwable t=e;t!=null;t=t.getCause())if(t instanceof VodNetwork.HttpError&&((VodNetwork.HttpError)t).status==403)return true;return false;}
 private void offerSite(){if(siteDialogShown||isFinishing())return;siteDialogShown=true;new AlertDialog.Builder(this).setTitle(catalogueSource().name).setMessage("Il catalogo ha risposto HTTP 403 su questa rete. Vuoi provare il sito nel browser Android interno?").setPositiveButton("Apri sito",(d,n)->openSite()).setNegativeButton("Non ora",null).setOnDismissListener(d->siteDialogShown=false).show();}
 private void openSite(){VodSettings.Source s=catalogueSource();if(s.cinesearch()&&s.url.isEmpty()){VodSettings.editCineSearch(this,()->load(true));return;}startActivity(new Intent(this,VodBrowserActivity.class).putExtra("url",s.url).putExtra("title",s.name));}
 private VodSettings.Source catalogueSource(){if(directDetail||providerId>0)return new VodSettings.Source("tmdb","TMDB","https://www.themoviedb.org","tmdb");return VodSession.catalogue(this);}
 private void reloadSection(){returnId="";returnPosition=0;returnTop=0;catalogue.clear();items.clear();visibleLimit=20;load(false);}
 private VodSettings.Source communitySource(){for(VodSettings.Source candidate:VodSettings.sources(this))if("streamingcommunity".equals(candidate.id))return candidate;return VodSettings.sources(this).get(0);}
 private void enrichCatalogue(int request,List<VodSource.Title> catalogue,String apiKey,String cacheKey){final java.util.concurrent.atomic.AtomicInteger remaining=new java.util.concurrent.atomic.AtomicInteger(catalogue.size());for(int index=0;index<catalogue.size();index++){final int position=index;metadataWorkers.submit(()->{try{if(destroyed||request!=generation)return;VodSource.Title enriched=TmdbClient.enrich(catalogue.get(position),apiKey,fetcher());synchronized(catalogue){catalogue.set(position,enriched);}runOnUiThread(()->{if(destroyed||request!=generation)return;for(int k=0;k<this.catalogue.size();k++)if(this.catalogue.get(k).id.equals(enriched.id))this.catalogue.set(k,enriched);for(int k=0;k<items.size();k++)if(items.get(k).id.equals(enriched.id))items.set(k,enriched);if(!genreFilter.isEmpty()||!yearFilter.isEmpty()){String focusId=selected==null?"":selected.id;int offset=grid.getSelectedView()==null?0:grid.getSelectedView().getTop();revealCatalogue(Math.max(20,items.size()));for(int k=0;k<items.size();k++)if(items.get(k).id.equals(focusId)){grid.setSelectionFromTop(k,offset);break;}}else if(grid.getAdapter() instanceof BaseAdapter)((BaseAdapter)grid.getAdapter()).notifyDataSetChanged();if(selected!=null&&selected.id.equals(enriched.id)){selected=enriched;plot.setText(enriched.plot.isEmpty()?"Premi OK per trama e dettagli.":enriched.plot);artwork.bind(image,enriched.poster,new ColorDrawable(0xff202125));updateFavorite();}});}catch(Exception ignored){}finally{if(remaining.decrementAndGet()==0){runOnUiThread(()->{if(!destroyed&&request==generation){VodCache.save(this,cacheKey,new ArrayList<>(this.catalogue));catalogueStatus();}});}}});}}
 private void render(){grid.setAdapter(new BaseAdapter(){public int getCount(){return items.size();}public Object getItem(int n){return items.get(n);}public long getItemId(int n){return Long.parseLong(items.get(n).id);}public View getView(int n,View recycled,ViewGroup parent){VodSource.Title t=items.get(n);LinearLayout card;ImageView cover;TextView label;if(recycled instanceof LinearLayout){card=(LinearLayout)recycled;cover=(ImageView)card.getChildAt(0);label=(TextView)card.getChildAt(1);}else{card=new LinearLayout(VodCatalogueActivity.this);card.setOrientation(1);card.setPadding(dp(5),dp(5),dp(5),dp(6));cover=new ProgrammeArtwork(VodCatalogueActivity.this);cover.setScaleType(ImageView.ScaleType.FIT_CENTER);card.addView(cover,new LinearLayout.LayoutParams(-1,dp(240)));label=text("",15);label.setMaxLines(2);label.setMinHeight(dp(38));card.addView(label);}card.setBackgroundColor(0xff202125);label.setText(t.name);while(card.getChildCount()>2)card.removeViewAt(2);if(VodCatalogue.newEpisode(VodCatalogueActivity.this,t,source)){TextView badge=text("NUOVA PUNTATA",11);badge.setTextColor(UiTheme.accent(VodCatalogueActivity.this));card.addView(badge);}if(mode==4){JSONObject h=VodLibrary.latest(VodCatalogueActivity.this,TmdbClient.scope(t,source),TmdbClient.identity(t));ProgressBar progress=new ProgressBar(VodCatalogueActivity.this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);progress.setProgress(VodLibrary.percent(h));progress.setProgressTintList(android.content.res.ColorStateList.valueOf(UiTheme.accent(VodCatalogueActivity.this)));card.addView(progress,new LinearLayout.LayoutParams(-1,dp(4)));TextView resume=text(h==null?"":h.optBoolean("completed")?"Terminato · prossimo episodio":VodLibrary.clock(h.optLong("position"))+" / "+VodLibrary.clock(h.optLong("duration"))+" · "+h.optString("label"),11);resume.setMaxLines(2);resume.setTextColor(0xffa6a6aa);card.addView(resume);}artwork.bind(cover,t.poster,new ColorDrawable(0xff292a2e));return card;}});}
 private void hideSeasonPosters(){seasonScroll.setVisibility(View.GONE);grid.setVisibility(View.VISIBLE);more.setVisibility(View.GONE);}
 private void showSeasonPicker(VodSource.Title t){
  JSONArray raw=t.json.optJSONArray("seasons");if(raw==null||raw.length()==0){status.setText("Stagioni in caricamento");loadDetails(t,false);return;}
  ScrollView scroll=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(12),dp(10),dp(12),dp(10));list.setBackgroundColor(UiTheme.background(this));scroll.addView(list);
  AlertDialog dialog=new AlertDialog.Builder(this).setTitle(t.name+" · Stagioni").setView(scroll).setNegativeButton("Indietro",null).create();
  LinearLayout row=null;int count=0;
  for(int i=0;i<raw.length();i++){JSONObject season=raw.optJSONObject(i);if(season==null)continue;int n=season.optInt("season_number",season.optInt("number"));if(n<=0)continue;
   if(count++%2==0){row=new LinearLayout(this);list.addView(row,new LinearLayout.LayoutParams(-1,-2));}
   LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.HORIZONTAL);card.setFocusable(true);card.setClickable(true);card.setBackground(focus());card.setPadding(dp(7),dp(8),dp(7),dp(8));row.addView(card,new LinearLayout.LayoutParams(0,dp(208),1));
   ProgrammeArtwork poster=new ProgrammeArtwork(this);poster.setScaleType(ImageView.ScaleType.CENTER_CROP);card.addView(poster,new LinearLayout.LayoutParams(dp(105),-1));String path=season.optString("poster_path");artwork.bind(poster,path.startsWith("/")?"https://image.tmdb.org/t/p/w342"+path:t.poster,new ColorDrawable(UiTheme.panel(this)));
   LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(8),dp(4),dp(3),0);card.addView(words,new LinearLayout.LayoutParams(0,-1,1));TextView headline=text("Stagione "+n,17);headline.setTextColor(UiTheme.accent(this));words.addView(headline);String year=season.optString("air_date");TextView facts=text((year.length()>=4?year.substring(0,4)+" · ":"")+season.optInt("episode_count")+" episodi · ★ "+String.format(java.util.Locale.ITALY,"%.1f",season.optDouble("vote_average")),12);words.addView(facts);TextView summary=text(season.optString("overview"),12);summary.setMaxLines(6);words.addView(summary);final int number=n;card.setOnClickListener(v->{dialog.dismiss();chooseVixEpisode(t,number);});
  }
  dialog.show();if(dialog.getWindow()!=null)dialog.getWindow().setLayout(Math.min(getResources().getDisplayMetrics().widthPixels-dp(40),dp(1150)),Math.min(getResources().getDisplayMetrics().heightPixels-dp(40),dp(660)));
 }
 private void loadCast(VodSource.Title t,int request){long id=t.json.optLong("tmdb_id");if(id<=0)return;worker.submit(()->{try{JSONObject data=TmdbClient.request("/"+(t.series()?"tv":"movie")+"/"+id+"/credits",TmdbClient.key(this),fetcher());JSONArray people=data.optJSONArray("cast");runOnUiThread(()->{if(destroyed||request!=detailGeneration||castStrip==null)return;castStrip.removeAllViews();for(int i=0;people!=null&&i<Math.min(people.length(),16);i++){JSONObject person=people.optJSONObject(i);if(person==null)continue;int personId=person.optInt("id");LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(3),dp(3),dp(3),dp(3));card.setFocusable(true);card.setClickable(true);card.setBackground(focus());castStrip.addView(card,new LinearLayout.LayoutParams(dp(104),dp(125)));ProgrammeArtwork picture=new ProgrammeArtwork(this);picture.setScaleType(ImageView.ScaleType.CENTER_CROP);card.addView(picture,new LinearLayout.LayoutParams(-1,dp(78)));String path=person.optString("profile_path");artwork.bind(picture,path.startsWith("/")?"https://image.tmdb.org/t/p/w185"+path:"",new ColorDrawable(UiTheme.panel(this)));TextView who=text(person.optString("name"),12);who.setMaxLines(1);card.addView(who);TextView role=text(person.optString("character"),10);role.setMaxLines(1);role.setTextColor(UiTheme.accent(this));card.addView(role);card.setOnClickListener(v->showFilmography(personId,person.optString("name")));}});}catch(Exception ignored){}});}
 private void showFilmography(int personId,String actor){worker.submit(()->{try{JSONObject data=TmdbClient.request("/person/"+personId+"/combined_credits",TmdbClient.key(this),fetcher());JSONArray cast=data.optJSONArray("cast");ArrayList<VodSource.Title> films=new ArrayList<>();HashSet<String> seen=new HashSet<>();for(int i=0;cast!=null&&i<cast.length();i++){JSONObject item=cast.optJSONObject(i);if(item==null)continue;String type=item.optString("media_type");if(!type.equals("movie")&&!type.equals("tv"))continue;String id=type+":"+item.optLong("id");if(!seen.add(id))continue;VodSource.Title t=TmdbClient.convert(item,type);if(t!=null)films.add(t);}films.sort((a,b)->b.year.compareTo(a.year));runOnUiThread(()->{String[] names=new String[Math.min(films.size(),120)];for(int i=0;i<names.length;i++){VodSource.Title t=films.get(i);names[i]=t.name+(t.year.isEmpty()?"":" ("+t.year+")");}new AlertDialog.Builder(this).setTitle("Filmografia · "+actor).setItems(names,(d,n)->{VodSource.Title t=films.get(n);startActivity(new Intent(this,VodCatalogueActivity.class).putExtra("startMode",t.series()?2:1).putExtra("openTmdbId",t.json.optLong("tmdb_id")).putExtra("directDetail",true).putExtra("sectionTitle",t.name));}).setNegativeButton("Chiudi",null).show();});}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Filmografia non disponibile",Toast.LENGTH_SHORT).show());}});}
 private void renderSeasonPosters(VodSource.Title t){
  JSONArray seasonsData=t.json.optJSONArray("seasons");
  if(seasonsData==null||seasonsData.length()==0){
    seasonScroll.setVisibility(View.VISIBLE);grid.setVisibility(View.GONE);more.setVisibility(View.GONE);
    seasonGrid.removeAllViews();TextView hint=text("Caricamento locandine delle stagioni…",16);seasonGrid.addView(hint);return;
  }
  seasonGrid.removeAllViews();grid.setVisibility(View.GONE);more.setVisibility(View.GONE);seasonScroll.setVisibility(View.VISIBLE);
  TextView title=text("Scegli una stagione",20);title.setTextColor(UiTheme.accent(this));seasonGrid.addView(title);
  int columns=3;LinearLayout row=null;int count=0;
  for(int i=0;i<seasonsData.length();i++){
    JSONObject season=seasonsData.optJSONObject(i);if(season==null)continue;
    int number=season.optInt("season_number",season.optInt("number",-1));if(number<=0)continue;
    if(count%columns==0){row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);seasonGrid.addView(row);}
    LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(4),dp(6),dp(4),dp(6));
    card.setFocusable(true);card.setClickable(true);card.setBackground(focus());
    ProgrammeArtwork poster=new ProgrammeArtwork(this);poster.setScaleType(ImageView.ScaleType.FIT_CENTER);
    card.addView(poster,new LinearLayout.LayoutParams(-1,dp(152)));
    TextView label=text("Stagione "+number,14);label.setGravity(Gravity.CENTER);card.addView(label);
    row.addView(card,new LinearLayout.LayoutParams(0,dp(195),1f));
    String path=season.optString("poster_path","");
    String posterUrl=path.startsWith("/")?"https://image.tmdb.org/t/p/w342"+path:t.poster;
    artwork.bind(poster,posterUrl,new ColorDrawable(UiTheme.panel(this)));
    final int chosen=number;card.setOnClickListener(v->{
      if(selected==null)return;
      if(selected.json.optBoolean("_tmdb"))chooseVixEpisode(selected,chosen);
      else episodes(selected,catalogueSource(),chosen);
    });
    count++;
  }
  if(count==0){TextView hint=text("Nessuna stagione disponibile",16);seasonGrid.addView(hint);}
 }
 private void show(VodSource.Title t){if(selected!=null&&selected.id.equals(t.id))return;selected=t;details=null;++detailGeneration;if(castStrip!=null)castStrip.removeAllViews();name.setText(t.name);meta.setText((t.series()?"Serie TV":"Film")+(t.year.isEmpty()?"":" · "+t.year));plot.setText(t.plot.isEmpty()?"Premi OK per trama e dettagli.":t.plot);artwork.bind(image,directDetail?t.json.optString("_backdrop_url",t.poster):t.poster,new ColorDrawable(0xff202125));play.setText(t.series()?"▶ Guarda":mode==4?"▶ Riprendi":"▶ Guarda");play.setEnabled(true);favorite.setEnabled(true);seasons.setVisibility(t.series()?View.VISIBLE:View.GONE);if(directDetail){image.setVisibility(View.VISIBLE);hideSeasonPosters();}updateFavorite();updateProgress();JSONObject h=VodLibrary.latest(this,TmdbClient.scope(t,source),TmdbClient.identity(t));nextEpisode.setVisibility(h!=null&&hasNext(h)?View.VISIBLE:View.GONE);}
 private void updateProgress(){if(detailProgress==null){detailProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);detailProgress.setTag("vodDetailProgress");detailProgress.setMax(100);detailProgress.setProgressTintList(android.content.res.ColorStateList.valueOf(UiTheme.accent(this)));resumeLabel=text("",11);resumeLabel.setTextColor(0xffa6a6aa);ViewGroup parent=(ViewGroup)meta.getParent();int at=parent.indexOfChild(meta)+1;parent.addView(detailProgress,at,new LinearLayout.LayoutParams(-1,dp(5)));parent.addView(resumeLabel,at+1);}JSONObject h=selected==null||source==null?null:VodLibrary.latest(this,TmdbClient.scope(selected,source),TmdbClient.identity(selected));int percent=VodLibrary.percent(h);detailProgress.setProgress(percent);detailProgress.setVisibility(h!=null&&percent>0?View.VISIBLE:View.GONE);resumeLabel.setVisibility(h!=null&&percent>0?View.VISIBLE:View.GONE);resumeLabel.setText(h==null?"":(h.optBoolean("completed")?"Terminato":VodLibrary.clock(h.optLong("position"))+" / "+VodLibrary.clock(h.optLong("duration")))+(h.optString("label").isEmpty()?"":" · "+h.optString("label")));}
 private void updateFavorite(){if(watchlist!=null){watchlist.setEnabled(selected!=null);watchlist.setText(selected!=null&&VodLibrary.watchlisted(this,TmdbClient.scope(selected,source),TmdbClient.identity(selected))?"✓ Rimuovi da Da vedere":"＋ Da vedere");}favorite.setText(selected!=null&&VodLibrary.favorite(this,TmdbClient.scope(selected,source),TmdbClient.identity(selected))?"★ Rimuovi dai preferiti":"☆ Aggiungi ai preferiti");}
 private void loadDetails(VodSource.Title t,boolean focusPlay){show(t);final int request=++detailGeneration;final String sid=source.id,home=source.url;status.setText("Caricamento dettagli · "+t.name);worker.submit(()->{try{VodSource.Title full;JSONObject p;if(source.cinesearch()){full=CineSearch.details(source,t,fetcher());p=new JSONObject().put("title",full.json);}else if(t.json.optBoolean("_tmdb")){full=TmdbClient.details(t,TmdbClient.key(this),fetcher());p=new JSONObject().put("title",full.json);}else{p=VodSource.page(home,t.path(),fetcher());full=TmdbClient.merge(VodSource.title(p,home),t);}if(t.series()&&!t.json.optBoolean("_tmdb")){JSONObject history=VodLibrary.latest(this,TmdbClient.scope(t,source),TmdbClient.identity(t));int season=history==null?0:history.optInt("seasonNumber");if(season>0)try{JSONObject seasonPage=VodSource.page(home,t.path()+"/season-"+season,fetcher());full.json.put("_availableSeason",season).put("_availableEpisodes",seasonPage.getJSONObject("loadedSeason").getJSONArray("episodes"));}catch(Exception ignored){}}runOnUiThread(()->{if(destroyed||request!=detailGeneration||source==null||!sid.equals(source.id)||selected==null||!t.id.equals(selected.id))return;selected=full;for(int k=0;k<catalogue.size();k++)if(catalogue.get(k).id.equals(full.id))catalogue.set(k,full);for(int k=0;k<items.size();k++)if(items.get(k).id.equals(full.id))items.set(k,full);if(grid.getAdapter() instanceof BaseAdapter)((BaseAdapter)grid.getAdapter()).notifyDataSetChanged();details=p;name.setText(full.name);plot.setText(full.plot);meta.setText((full.series()?"Serie TV":"Film")+" · "+full.year+" · "+full.json.optString("quality",""));artwork.bind(image,directDetail?full.json.optString("_backdrop_url",full.poster):full.poster,new ColorDrawable(0xff202125));status.setText(source.name+" · "+full.name);updateFavorite();loadCast(full,request);if(focusPlay)play.requestFocus();});}catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("Dettagli non disponibili · "+VodNetwork.error(e));});}});}
 private void watch(){if(source==null||selected==null)return;JSONObject latest=VodLibrary.latest(this,TmdbClient.scope(selected,source),TmdbClient.identity(selected));if(latest!=null){resumeSeason=latest.optInt("seasonNumber");resumeEpisode=latest.optInt("episodeNumber");if(resumeSeason==0||resumeEpisode==0)try{VodSource.Title previous=new VodSource.Title(latest.getJSONObject("providerTitle"),"");VodLibrary.inferEpisode(previous,latest.optString("label"));resumeSeason=previous.json.optInt("_seasonNumber");resumeEpisode=previous.json.optInt("_episodeNumber");}catch(Exception ignored){}}else{resumeSeason=0;resumeEpisode=0;}if(latest!=null&&latest.optLong("position")>0){new AlertDialog.Builder(this).setTitle(selected.name).setItems(new String[]{"Riprendi da "+VodLibrary.clock(latest.optLong("position")),"Inizia dall’inizio","Scegli un’altra fonte"},(d,n)->{if(n==2){resumeOverride=latest.optLong("position");findSources(selected,false);}else resumeHistory(latest,n==1?0:latest.optLong("position"),false);}).setNegativeButton("Chiudi",null).show();}else if(latest!=null&&latest.optBoolean("completed")&&hasNext(latest))resumeHistory(latest,0,true);else{resumeOverride=-1;primaryWatch(selected);}}
 private static boolean hasNext(JSONObject h){JSONArray q=h.optJSONArray("queue");if(q!=null)for(int i=0;i<q.length();i++)if(h.optString("episode").equals(q.optJSONObject(i).optString("id"))&&i+1<q.length())return true;JSONObject title=h.optJSONObject("providerTitle");JSONArray seasons=title==null?null:title.optJSONArray("seasons");for(int i=0;seasons!=null&&i<seasons.length();i++)if(seasons.optJSONObject(i).optInt("number")>h.optInt("seasonNumber"))return true;return false;}
 private void resumeNext(){if(selected==null)return;JSONObject h=VodLibrary.latest(this,TmdbClient.scope(selected,source),TmdbClient.identity(selected));if(h!=null)resumeHistory(h,0,true);}
 private void resumeHistory(JSONObject h,long position,boolean next){try{JSONObject p=h.getJSONObject("provider");VodSettings.Source provider=null;for(VodSettings.Source s:VodSettings.sources(this))if(s.id.equals(p.getString("id")))provider=s;if(provider==null){resumeOverride=position;findSources(selected,false);return;}VodSource.Title t=new VodSource.Title(h.getJSONObject("providerTitle"),provider.url);JSONArray q=h.optJSONArray("queue");if(q==null)q=new JSONArray();int n=-1;String episode=h.optString("episode"),label=h.optString("label",t.name);VodLibrary.inferEpisode(t,label);for(int i=0;i<q.length();i++)if(episode.equals(q.getJSONObject(i).optString("id"))||h.optInt("episodeNumber")==q.getJSONObject(i).optInt("number"))n=i;if(next&&n>=0&&n+1<q.length()){JSONObject e=q.getJSONObject(++n);episode=e.optString("id",String.valueOf(e.optInt("number")));label="S"+Math.max(1,h.optInt("seasonNumber"))+" · E"+e.optInt("number")+" · "+e.optString("name");t.json.put("_episodeNumber",e.optInt("number"));}if(provider.vixsrc()){if(next&&n<0){resumeOverride=0;chooseVix(t);return;}resumeOverride=position;openVix(t,Math.max(1,t.json.optInt("_seasonNumber",h.optInt("seasonNumber"))),Math.max(0,t.json.optInt("_episodeNumber",h.optInt("episodeNumber"))),label,q);return;}if(next&&(n<0||n>=q.length()||!episode.equals(q.getJSONObject(n).optString("id"))))return;boolean changedEpisode=!episode.equals(h.optString("episode"));if(next&&!changedEpisode){JSONArray seasons=t.json.optJSONArray("seasons");int nextSeason=Integer.MAX_VALUE;for(int i=0;seasons!=null&&i<seasons.length();i++){int value=seasons.optJSONObject(i).optInt("number");if(value>h.optInt("seasonNumber"))nextSeason=Math.min(nextSeason,value);}if(nextSeason<Integer.MAX_VALUE){resumeOverride=0;resumeAcrossSource(t,provider,nextSeason,1);return;}}resumeOverride=position;if(position==0&&!next)VodLibrary.restart(this,provider.id,t,episode);open(t,episode,label,q,n,provider);}catch(Exception e){resumeOverride=position;findSources(selected,false);}}
 private void primaryWatch(VodSource.Title wanted){VodSettings.Source main=VodSettings.primary(this);if(main.vixsrc()){chooseVix(wanted);return;}if(!main.nativeCatalog()){final int request=++detailGeneration;status.setText("Ricerca in "+main.name+" · "+wanted.name);providerWorkers.submit(()->{VodProviders.Match match=VodProviders.search(main,wanted,fetcher());runOnUiThread(()->{if(destroyed||request!=detailGeneration)return;if(match.title==null){status.setText(main.name+" · "+match.note+" · scegli Altre fonti");return;}if(match.nativeVideo&&!match.title.series())open(match.title,"",match.title.name,new JSONArray(),-1,main);else openWebMovie(match);});});return;}if(wanted.json.optBoolean("_tmdb")||!main.id.equals(catalogueSource().id)){final int request=++detailGeneration;status.setText("Ricerca in "+main.name+" · "+wanted.name);providerWorkers.submit(()->{VodProviders.Match match=VodProviders.search(main,wanted,fetcher());runOnUiThread(()->{if(destroyed||request!=detailGeneration)return;if(match.title==null){status.setText(main.name+" · "+match.note+" · scegli Altre fonti");return;}if(match.title.series()){if(resumeSeason>0&&resumeEpisode>0)resumeAcrossSource(match.title,main,resumeSeason,resumeEpisode);else chooseSeason(match.title,main);}else open(match.title,"",match.title.name,new JSONArray(),-1,main);});});return;}if(wanted.series()){if(resumeSeason>0&&resumeEpisode>0)resumeAcrossSource(wanted,main,resumeSeason,resumeEpisode);else chooseSeason(wanted,main);}else open(wanted,"",wanted.name,new JSONArray(),-1,main);}
 private void openWebMovie(VodProviders.Match match){
  boolean nativeAttempt=!match.title.series()&&WebMovieLinks.supported(match.source.url);
  Intent intent=new Intent(this,VodBrowserActivity.class).putExtra("url",match.page).putExtra("title",match.title.name);
  if(nativeAttempt||match.title.json.optBoolean("_web_search")){intent.putExtra("nativeAttempt",nativeAttempt).putExtra("source",match.source.json().toString()).putExtra("titleJson",match.title.json.toString()).putExtra("episode", "").putExtra("label",match.title.name).putExtra("startPosition",resumeOverride);lastWanted=selected;rememberGrid();startActivityForResult(intent,101);resumeOverride=-1;}
  else startActivity(intent);
 }
 private void findSources(VodSource.Title wanted,boolean chooseEpisodes){final int request=++detailGeneration;lastWanted=wanted;List<VodSettings.Source> sources=new ArrayList<>(VodSettings.sources(this));String preferred=VodSettings.primary(this).id;sources.sort((a,b)->Boolean.compare(!a.id.equals(preferred),!b.id.equals(preferred)));String[] labels=new String[sources.size()];VodProviders.Match[] matches=new VodProviders.Match[sources.size()];for(int i=0;i<labels.length;i++)labels[i]=sources.get(i).name+" · ricerca…";ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,labels){public boolean areAllItemsEnabled(){return false;}public boolean isEnabled(int n){return matches[n]!=null;}};AlertDialog dialog=new AlertDialog.Builder(this).setTitle(wanted.name+" · Fonti").setAdapter(adapter,(d,n)->{VodProviders.Match m=matches[n];if(m!=null&&m.source.vixsrc()){chooseVix(wanted);return;}if(m!=null&&m.title!=null&&!m.nativeVideo){openWebMovie(m);return;}if(m==null||m.title==null){VodSettings.openSite(this,sources.get(n));return;}if(m.title.series()&&m.source.nativeCatalog()){if(!chooseEpisodes&&resumeSeason>0&&resumeEpisode>0)resumeAcrossSource(m.title,m.source,resumeSeason,resumeEpisode);else{resumeOverride=-1;chooseSeason(m.title,m.source);}}else open(m.title,"",m.title.name,new JSONArray(),-1,m.source);}).setNegativeButton("Chiudi",null).create();dialog.show();List<Integer> order=new ArrayList<>();for(int i=0;i<sources.size();i++)order.add(i);order.sort((a,b)->Boolean.compare(!sources.get(a).nativeCatalog()&&!sources.get(a).vixsrc(),!sources.get(b).nativeCatalog()&&!sources.get(b).vixsrc()));for(int i:order){final int n=i;VodSettings.Source s=sources.get(i);providerWorkers.submit(()->{String cacheKey=wanted.id+":"+s.id+":"+s.url;VodProviders.Match m=matchCache.get(cacheKey);if(m==null){m=VodProviders.search(s,wanted,fetcher());if(m.title!=null&&!m.title.json.optBoolean("_web_search"))matchCache.put(cacheKey,m);}final VodProviders.Match found=m;runOnUiThread(()->{if(destroyed||request!=detailGeneration||!dialog.isShowing())return;matches[n]=found;labels[n]=s.name+" · "+found.note;adapter.notifyDataSetChanged();});});}}
 private void chooseVix(VodSource.Title wanted){final int request=++detailGeneration;status.setText("Preparazione VixSrc · "+wanted.name);providerWorkers.submit(()->{try{String key=TmdbClient.key(this);VodSource.Title enriched=TmdbClient.enrich(wanted,key,fetcher());if(VixSrc.tmdbId(enriched)<=0)throw new Exception("ID TMDB non disponibile");JSONObject metadata=TmdbClient.metadata(enriched);VodSource.Title tmdb=metadata==null?enriched:new VodSource.Title(metadata,"");if(!tmdb.series()){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)openVix(tmdb,0,0,tmdb.name,new JSONArray());});return;}if(resumeSeason>0&&resumeEpisode>0){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)openVix(tmdb,resumeSeason,resumeEpisode,"S"+resumeSeason+" · E"+resumeEpisode,new JSONArray());});return;}VodSource.Title full=TmdbClient.details(tmdb,key,fetcher());runOnUiThread(()->{if(!destroyed&&request==detailGeneration)chooseVixSeason(full);});}catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("VixSrc non disponibile · "+e.getMessage());});}});}
 private void chooseVixSeason(VodSource.Title metadata){JSONArray raw=metadata.json.optJSONArray("seasons"),seasons=new JSONArray();for(int i=0;raw!=null&&i<raw.length();i++){JSONObject season=raw.optJSONObject(i);if(season!=null&&season.optInt("season_number",season.optInt("number"))>0)seasons.put(season);}if(seasons.length()==0){status.setText("VixSrc · stagioni non disponibili");return;}String[] labels=new String[seasons.length()];for(int i=0;i<seasons.length();i++)labels[i]="Stagione "+seasons.optJSONObject(i).optInt("season_number",seasons.optJSONObject(i).optInt("number"));new AlertDialog.Builder(this).setTitle(metadata.name+" · VixSrc").setItems(labels,(d,n)->{JSONObject season=seasons.optJSONObject(n);if(season!=null)chooseVixEpisode(metadata,season.optInt("season_number",season.optInt("number")));}).setNegativeButton("Chiudi",null).show();}
 private void chooseVixEpisode(VodSource.Title metadata,int season){
  final int request=++detailGeneration;
  status.setText("Caricamento episodi · stagione "+season);
  worker.submit(()->{try{
   JSONArray episodes=TmdbClient.episodes(metadata,season,TmdbClient.key(this),fetcher());
   if(episodes.length()==0)throw new Exception("Nessun episodio disponibile");
   runOnUiThread(()->{if(!destroyed&&request==detailGeneration)showEpisodeScreen(metadata,season,episodes,null);});
  }catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("Episodi non disponibili · "+VodNetwork.error(e));});}});
 }
 /** Dedicated remote-friendly season page, with one checkpoint per episode. */
 private void showEpisodeScreen(VodSource.Title title,int season,JSONArray episodes,VodSettings.Source provider){
  LinearLayout content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);
  content.setPadding(dp(16),dp(10),dp(16),dp(10));content.setBackgroundColor(UiTheme.background(this));
  TextView heading=text(title.name+"  ·  Stagione "+season,22);heading.setTextColor(UiTheme.accent(this));
  content.addView(heading,new LinearLayout.LayoutParams(-1,dp(50)));
  ScrollView scroll=new ScrollView(this);content.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);scroll.addView(list);
  final AlertDialog dialog=new AlertDialog.Builder(this).setView(content).create();
  final String tmdbId=TmdbClient.identity(title);
  LinearLayout episodeRow=null;
  for(int i=0;i<episodes.length();i++){
   JSONObject item=episodes.optJSONObject(i);if(item==null)continue;
   final int index=i,number=item.optInt("number",item.optInt("episode_number",i+1));
   final String label="S"+season+" · E"+number+" · "+item.optString("name", "Episodio "+number);
   JSONObject record=VodLibrary.episodeProgress(this,tmdbId,season,number);
   LinearLayout card=new LinearLayout(this);card.setFocusable(true);card.setClickable(true);
   card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(9),dp(7),dp(9),dp(7));card.setBackground(focus());
   LinearLayout detail=new LinearLayout(this);card.addView(detail,new LinearLayout.LayoutParams(-1,0,1));ProgrammeArtwork still=new ProgrammeArtwork(this);still.setScaleType(ImageView.ScaleType.CENTER_CROP);detail.addView(still,new LinearLayout.LayoutParams(dp(145),-1));String stillPath=item.optString("still_path");artwork.bind(still,stillPath.startsWith("/")?"https://image.tmdb.org/t/p/w300"+stillPath:"",new ColorDrawable(UiTheme.panel(this)));
   LinearLayout textColumn=new LinearLayout(this);textColumn.setOrientation(LinearLayout.VERTICAL);textColumn.setPadding(dp(8),0,0,0);detail.addView(textColumn,new LinearLayout.LayoutParams(0,-1,1));TextView name=text(label,16);name.setMaxLines(2);textColumn.addView(name);TextView overview=text(item.optString("overview"),12);overview.setMaxLines(3);textColumn.addView(overview);
   ProgressBar progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);
   progress.setMax(100);progress.setProgressTintList(android.content.res.ColorStateList.valueOf(UiTheme.accent(this)));
   int percent=record!=null&&record.optBoolean("completed")?100:VodLibrary.percent(record);
   progress.setProgress(percent);card.addView(progress,new LinearLayout.LayoutParams(-1,dp(6)));
   TextView watched=text(record==null?"Da vedere":record.optBoolean("completed")?"Completato":percent+"% · riprendi da "+VodLibrary.clock(record.optLong("position")),12);
   watched.setTextColor(UiTheme.accent(this));card.addView(watched);
   if(i%2==0){episodeRow=new LinearLayout(this);list.addView(episodeRow,new LinearLayout.LayoutParams(-1,dp(160)));}
   if(episodeRow!=null)episodeRow.addView(card,new LinearLayout.LayoutParams(0,-1,1));
   card.setOnClickListener(v->{dialog.dismiss();resumeOverride=record!=null&&!record.optBoolean("completed")?record.optLong("position"):-1;
     if(provider==null)openVix(title,season,number,label,episodes);
     else{try{title.json.put("_seasonNumber",season);open(title,item.optString("id",String.valueOf(number)),label,episodes,index,provider);}catch(Exception ignored){}}
   });
  }
  dialog.show();android.view.Window window=dialog.getWindow();if(window!=null)window.setLayout(Math.min(getResources().getDisplayMetrics().widthPixels,dp(850)),Math.min(getResources().getDisplayMetrics().heightPixels-dp(60),dp(680)));
 }
 private void openVix(VodSource.Title title,int season,int episodeNumber,String episodeLabel,JSONArray queue){try{JSONObject json=new JSONObject(title.json.toString());JSONObject metadata=TmdbClient.metadata(title);if(metadata==null)throw new Exception("ID TMDB non disponibile");json.put("_metadata",metadata);json.put("tmdb_id",metadata.optLong("tmdb_id"));if(season>0)json.put("_seasonNumber",season);if(episodeNumber>0)json.put("_episodeNumber",episodeNumber);json.put("_queue",queue);VodSettings.Source vix=null;for(VodSettings.Source s:VodSettings.sources(this))if(s.vixsrc())vix=s;if(vix==null)throw new Exception("Fonte VixSrc non configurata");int index=-1;for(int i=0;i<queue.length();i++)if(queue.optJSONObject(i).optInt("number")==episodeNumber){index=i;break;}lastWanted=selected;rememberGrid();startActivityForResult(new Intent(this,VodPlayerActivity.class).putExtra("source",vix.json().toString()).putExtra("titleJson",json.toString()).putExtra("episode",episodeNumber>0?String.valueOf(episodeNumber):"").putExtra("label",episodeLabel).putExtra("episodes",queue.toString()).putExtra("index",index).putExtra("startPosition",Math.max(0,resumeOverride)),101);resumeOverride=-1;}catch(Exception e){status.setText("VixSrc non disponibile · "+e.getMessage());}}
 private void resumeAcrossSource(VodSource.Title t,VodSettings.Source s,int season,int number){final int request=++detailGeneration;status.setText("Caricamento episodio · S"+season+" E"+number);worker.submit(()->{try{JSONObject p=VodSource.page(s.url,t.path()+"/season-"+season,fetcher());JSONArray queue=p.getJSONObject("loadedSeason").getJSONArray("episodes");int found=-1;for(int i=0;i<queue.length();i++)if(queue.getJSONObject(i).optInt("number")==number)found=i;if(found<0)throw new Exception("Episodio non presente nella fonte");final int n=found;t.json.put("_seasonNumber",season);runOnUiThread(()->{if(destroyed||request!=detailGeneration)return;try{JSONObject e=queue.getJSONObject(n);open(t,e.getString("id"),"S"+season+" · E"+number+" · "+e.optString("name"),queue,n,s);}catch(Exception ignored){}});}catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration){status.setText("Episodio non disponibile in questa fonte");chooseSeason(t,s);}});}});}
 private void chooseSeason(VodSource.Title t,VodSettings.Source s){final int request=++detailGeneration;status.setText("Caricamento stagioni…");worker.submit(()->{try{JSONObject p=VodSource.page(s.url,t.path(),fetcher());JSONArray a=p.getJSONObject("title").optJSONArray("seasons");t.json.put("seasons",a);if(a==null||a.length()==0)throw new Exception("Nessuna stagione disponibile");String[] labels=new String[a.length()];for(int i=0;i<a.length();i++)labels[i]="Stagione "+a.getJSONObject(i).optInt("number");runOnUiThread(()->{if(destroyed||request!=detailGeneration)return;new AlertDialog.Builder(this).setTitle(t.name).setItems(labels,(d,n)->{try{episodes(t,s,a.getJSONObject(n).getInt("number"));}catch(Exception ignored){}}).setNegativeButton("Chiudi",null).show();status.setText(s.name+" · "+t.name);});}catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("Stagioni non disponibili · "+e.getMessage());});}});}
 private void episodes(VodSource.Title t,VodSettings.Source s,int season){
  final int request=++detailGeneration;status.setText("Caricamento episodi…");
  worker.submit(()->{try{
   JSONObject page=VodSource.page(s.url,t.path()+"/season-"+season,fetcher());
   JSONArray episodes=page.getJSONObject("loadedSeason").getJSONArray("episodes");
   if(episodes.length()==0)throw new Exception("Nessun episodio disponibile");
   runOnUiThread(()->{if(!destroyed&&request==detailGeneration)showEpisodeScreen(t,season,episodes,s);});
  }catch(Exception e){runOnUiThread(()->{if(!destroyed&&request==detailGeneration)status.setText("Episodi non disponibili · "+VodNetwork.error(e));});}});
 }
 private void open(VodSource.Title t,String episode,String label,JSONArray queue,int index,VodSettings.Source playbackSource){lastWanted=selected;try{if(index>=0&&index<queue.length())t.json.put("_episodeNumber",queue.getJSONObject(index).optInt("number"));t.json.put("_queue",queue);}catch(Exception ignored){}rememberGrid();startActivityForResult(new Intent(this,VodPlayerActivity.class).putExtra("source",playbackSource.json().toString()).putExtra("titleJson",t.json.toString()).putExtra("episode",episode).putExtra("label",label).putExtra("episodes",queue.toString()).putExtra("index",index).putExtra("startPosition",resumeOverride),101);resumeOverride=-1;}
 @Override public void onBackPressed(){if(drawer!=null&&drawer.open()){drawer.hide();return;}if(directDetail){finish();return;}if(detailOpen){detailOpen=false;details=null;grid.requestFocus();return;}if(searchPage){finish();return;}finish();}
 @Override public boolean dispatchKeyEvent(KeyEvent e){if(e.getAction()==KeyEvent.ACTION_DOWN&&grid.hasFocus()){int selectedPosition=grid.getSelectedItemPosition();if(e.getKeyCode()==KeyEvent.KEYCODE_DPAD_RIGHT&&selectedPosition%grid.getNumColumns()==grid.getNumColumns()-1){play.requestFocus();return true;}if(e.getKeyCode()==KeyEvent.KEYCODE_DPAD_DOWN&&more.getVisibility()==View.VISIBLE&&selectedPosition>=Math.max(0,items.size()-grid.getNumColumns())){more.requestFocus();return true;}}return super.dispatchKeyEvent(e);}
 private void options(){startActivity(new Intent(this,VodSettingsActivity.class));}
 private void titleMenu(VodSource.Title t){new AlertDialog.Builder(this).setTitle(t.name).setItems(new String[]{"Preferiti · aggiungi/rimuovi","Da vedere · aggiungi/rimuovi","Rimuovi da Continua a guardare"},(d,n)->{String scope=TmdbClient.scope(t,source);if(n==0)VodLibrary.favorite(this,scope,t);else if(n==1)VodLibrary.watchlist(this,scope,t);else {VodLibrary.removeHistory(this,scope,TmdbClient.identity(t));if(!"tmdb".equals(scope))VodLibrary.removeHistory(this,"tmdb",TmdbClient.identity(t));}if(mode>=3)load(false);else updateFavorite();}).setNegativeButton("Chiudi",null).show();}
 private void rememberSelectionAfterLoad(){if(returnId.isEmpty())return;boolean found=false;for(VodSource.Title t:items)if(t.id.equals(returnId))found=true;if(!found){returnPosition=0;returnTop=0;}}
 private void rememberGrid(){returnPosition=grid.getFirstVisiblePosition();returnTop=grid.getSelectedView()!=null?grid.getSelectedView().getTop():0;returnId=selected==null?"":selected.id;View focus=getCurrentFocus();returnFocus=focus==null?"":String.valueOf(focus.getTag());}
 private void restoreGrid(){int n=0;for(int i=0;i<items.size();i++)if(items.get(i).id.equals(returnId)){n=i;break;}if(!items.isEmpty())show(items.get(n));final int selectedIndex=n;grid.post(()->{if(destroyed)return;grid.setSelectionFromTop(selectedIndex,returnTop);if(!returnFocus.equals("vodPlay"))grid.requestFocus();else play.requestFocus();});}
 @Override protected void onSaveInstanceState(Bundle state){rememberGrid();state.putInt("mode",mode);state.putString("query",search.getText().toString());state.putInt("position",returnPosition);state.putInt("top",returnTop);state.putString("title",returnId);state.putString("focus",returnFocus);state.putInt("providerId",providerId);state.putString("providerName",providerName);state.putString("sectionKind",sectionKind);state.putString("sectionTitle",sectionTitle);state.putBoolean("searchPage",searchPage);state.putBoolean("directDetail",directDetail);state.putBoolean("detailOpen",detailOpen);super.onSaveInstanceState(state);}
 @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==101&&result==RESULT_FIRST_USER&&lastWanted!=null){resumeOverride=data==null?-1:data.getLongExtra("position",-1);grid.post(()->findSources(lastWanted,false));}}
 @Override protected void onResume(){super.onResume();if(themeAtCreate!=UiTheme.selected(this)){recreate();return;}if(paused){paused=false;if(mode>=3)load(false);else{selected=null;restoreGrid();}}if(libraryPrefs!=null)libraryPrefs.unregisterOnSharedPreferenceChangeListener(libraryListener);libraryPrefs=VodLibrary.prefs(this);libraryPrefs.registerOnSharedPreferenceChangeListener(libraryListener);updateFavorite();CloudSync.flush(this,false);}
 @Override protected void onPause(){rememberGrid();paused=true;ui.removeCallbacks(libraryRefresh);if(libraryPrefs!=null)libraryPrefs.unregisterOnSharedPreferenceChangeListener(libraryListener);super.onPause();}
 @Override protected void onDestroy(){destroyed=true;++generation;++detailGeneration;ui.removeCallbacksAndMessages(null);if(task!=null)task.cancel(true);worker.shutdownNow();providerWorkers.shutdownNow();metadataWorkers.shutdownNow();if(artwork!=null)artwork.close();super.onDestroy();}
}
