package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.content.res.ColorStateList;import android.graphics.*;import android.graphics.drawable.*;import android.text.*;import android.text.style.ForegroundColorSpan;import android.view.*;import android.widget.*;

/** Shared hidden VOD drawer, overlaid without consuming content space. */
final class VodDrawer {
 static final class Controller {final LinearLayout view;final Button[] buttons;final View previous;final LinearLayout rail;View returnFocus;Controller(LinearLayout v,Button[] b,View p,LinearLayout r){view=v;buttons=b;previous=p;rail=r;}boolean open(){return view.getVisibility()==View.VISIBLE;}void show(){View focused=view.getRootView().findFocus();if(focused!=null&&!inside(view,focused)&&!inside(rail,focused))returnFocus=focused;view.setVisibility(View.VISIBLE);view.bringToFront();buttons[0].requestFocus();}void hide(){view.setVisibility(View.GONE);View target=returnFocus!=null&&!inside(rail,returnFocus)?returnFocus:previous;if(target!=null)target.requestFocus();}static boolean inside(ViewGroup parent,View child){for(View node=child;node!=null;){if(node==parent)return true;android.view.ViewParent p=node.getParent();node=p instanceof View?(View)p:null;}return false;}}
 static Controller attach(Activity a,FrameLayout root,View previous){int d=Math.round(a.getResources().getDisplayMetrics().density);LinearLayout drawer=new LinearLayout(a);drawer.setTag("vodSidebar");drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(14*d,18*d,14*d,14*d);GradientDrawable bg=new GradientDrawable();bg.setColor(0xf8202125);bg.setCornerRadii(new float[]{0,0,14*d,14*d,14*d,14*d,0,0});drawer.setBackground(bg);TextView logo=new TextView(a);SpannableString mark=new SpannableString("R. ITA VOD");mark.setSpan(new ForegroundColorSpan(UiTheme.TEXT),0,3,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);mark.setSpan(new ForegroundColorSpan(UiTheme.accent(a)),3,6,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);mark.setSpan(new ForegroundColorSpan(UiTheme.TEXT),6,10,Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);logo.setText(mark);logo.setTextSize(25);logo.setTypeface(UiTheme.medium(a));logo.setGravity(Gravity.CENTER);drawer.addView(logo,new LinearLayout.LayoutParams(-1,60*d));String[] labels={"TV Live","Novità","Nuove uscite","Film","Serie TV","Continua a guardare","Da vedere","Preferiti","Impostazioni","Esci"};ScrollView menuScroll=new ScrollView(a);menuScroll.setFillViewport(false);drawer.addView(menuScroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout entries=new LinearLayout(a);entries.setOrientation(LinearLayout.VERTICAL);menuScroll.addView(entries);Button[] buttons=new Button[labels.length];final Controller[] holder=new Controller[1];for(int i=0;i<labels.length;i++){final int action=i;Button b=new Button(a);b.setText(labels[i]);b.setAllCaps(false);b.setTextSize(15);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);b.setTypeface(UiTheme.medium(a));b.setTextColor(new ColorStateList(new int[][]{new int[]{android.R.attr.state_focused},new int[]{}},new int[]{UiTheme.accent(a),UiTheme.TEXT}));b.setBackground(premiumBackground(a));b.setPadding(10*d,0,8*d,0);VodMenuIcon icon=new VodMenuIcon(i,UiTheme.TEXT);icon.setBounds(0,0,26*d,26*d);b.setCompoundDrawablePadding(12*d);b.setCompoundDrawables(icon,null,null,null);b.setOnFocusChangeListener((v,f)->{icon.color(f?UiTheme.accent(a):UiTheme.TEXT);b.setElevation(f?5*d:0);});b.setOnClickListener(v->navigate(a,action));buttons[i]=b;entries.addView(b,new LinearLayout.LayoutParams(-1,50*d));b.setOnKeyListener((v,key,event)->{if(event.getAction()==KeyEvent.ACTION_DOWN&&key==KeyEvent.KEYCODE_DPAD_RIGHT){if(holder[0]!=null)holder[0].hide();return true;}return false;});}drawer.setVisibility(View.GONE);root.addView(drawer,new FrameLayout.LayoutParams(285*d,-1,Gravity.START));// Always-visible compact icon rail; expanding preserves the existing app menu entries.
 LinearLayout rail=new LinearLayout(a);rail.setOrientation(LinearLayout.VERTICAL);rail.setTag("vodCompactSidebar");rail.setBackgroundColor(0xe8202125);rail.setPadding(4*d,6*d,4*d,6*d);
 ScrollView railScroll=new ScrollView(a);railScroll.setFillViewport(false);rail.addView(railScroll,new LinearLayout.LayoutParams(-1,0,1));LinearLayout icons=new LinearLayout(a);icons.setOrientation(LinearLayout.VERTICAL);railScroll.addView(icons);
 for(int i=0;i<labels.length;i++){Button b=new Button(a);b.setText("");b.setContentDescription(labels[i]);b.setPadding(0,0,0,0);b.setMinWidth(0);b.setMinimumWidth(0);b.setBackground(premiumBackground(a));VodMenuIcon icon=new VodMenuIcon(i,UiTheme.TEXT);icon.setBounds(0,0,25*d,25*d);b.setCompoundDrawables(icon,null,null,null);icons.addView(b,new LinearLayout.LayoutParams(-1,44*d));b.setOnClickListener(v->holder[0].show());b.setOnFocusChangeListener((v,hasFocus)->{icon.color(hasFocus?UiTheme.accent(a):UiTheme.TEXT);if(hasFocus&&holder[0]!=null&&!holder[0].open())holder[0].show();});}
 root.addView(rail,new FrameLayout.LayoutParams(56*d,-1,Gravity.START));drawer.bringToFront();Controller controller=new Controller(drawer,buttons,previous,rail);holder[0]=controller;return controller;}
 private static Drawable premiumBackground(Activity a){float d=a.getResources().getDisplayMetrics().density;StateListDrawable states=new StateListDrawable();GradientDrawable focus=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{UiTheme.softFocus(a),0x00202125});focus.setCornerRadius(9*d);focus.setStroke(Math.max(2,Math.round(2*d)),UiTheme.accent(a));states.addState(new int[]{android.R.attr.state_focused},focus);states.addState(new int[]{android.R.attr.state_pressed},focus);states.addState(new int[]{},new ColorDrawable(Color.TRANSPARENT));return states;}
 private static void navigate(Activity a,int action){
  if(action==0){a.startActivity(new Intent(a,MainActivity.class).putExtra("openLive",true));return;}
  if(action==1)section(a,0,"novita","Novità",0,"");
  else if(action==2)section(a,0,"releases","Nuove uscite",0,"");
  else if(action==3)section(a,1,"film","Film",0,"");
  else if(action==4)section(a,2,"series","Serie TV",0,"");
  else if(action==5)section(a,4,"continue","Continua a guardare",0,"");
  else if(action==6)section(a,5,"watchlist","Da vedere",0,"");
  else if(action==7)section(a,3,"favorites","Preferiti",0,"");
  else if(action==8)a.startActivity(new Intent(a,VodSettingsActivity.class));
  else new AlertDialog.Builder(a).setTitle("Uscire da R. ITA TV?").setMessage("Interrompere la riproduzione e tornare al menu del TIM Box?")
    .setPositiveButton("Esci",(d,w)->{a.finishAffinity();}).setNegativeButton("Annulla",null).show();
 }
 static void section(Activity a,int mode,String kind,String title,int provider,String providerName){a.startActivity(new Intent(a,VodCatalogueActivity.class).putExtra("startMode",mode).putExtra("sectionKind",kind).putExtra("sectionTitle",title).putExtra("providerId",provider).putExtra("providerName",providerName));}
}
