package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;

/** Shared hidden VOD drawer, overlaid without consuming content space. */
final class VodDrawer {
 static final class Controller {final LinearLayout view;final Button[] buttons;final View previous;Controller(LinearLayout v,Button[] b,View p){view=v;buttons=b;previous=p;}boolean open(){return view.getVisibility()==View.VISIBLE;}void show(){view.setVisibility(View.VISIBLE);view.bringToFront();buttons[0].requestFocus();}void hide(){view.setVisibility(View.GONE);if(previous!=null)previous.requestFocus();}}
 static Controller attach(Activity a,FrameLayout root,View previous){int d=Math.round(a.getResources().getDisplayMetrics().density);LinearLayout drawer=new LinearLayout(a);drawer.setTag("vodSidebar");drawer.setOrientation(LinearLayout.VERTICAL);drawer.setPadding(18*d,20*d,18*d,14*d);GradientDrawable bg=new GradientDrawable();bg.setColor(0xf5101113);bg.setStroke(Math.max(1,d),0x66f2b245);bg.setCornerRadii(new float[]{0,0,12*d,12*d,12*d,12*d,0,0});drawer.setBackground(bg);TextView logo=new TextView(a);logo.setText("R. ITA VOD");logo.setTextColor(UiTheme.AMBER);logo.setTextSize(25);logo.setTypeface(UiTheme.medium(a));logo.setGravity(Gravity.CENTER);drawer.addView(logo,new LinearLayout.LayoutParams(-1,58*d));String[] labels={"⌂  Home","▣  TV Live","◷  Novità","◷  Nuove uscite","▤  Film","▤  Serie TV","▶  Continua a guardare","★  Preferiti","⌕  Cerca","⚙  Impostazioni"};Button[] buttons=new Button[labels.length];for(int i=0;i<labels.length;i++){final int action=i;Button b=new Button(a);b.setText(labels[i]);b.setAllCaps(false);b.setTextSize(15);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);UiTheme.navigation(b);b.setOnClickListener(v->navigate(a,action));buttons[i]=b;drawer.addView(b,new LinearLayout.LayoutParams(-1,48*d));}drawer.setVisibility(View.GONE);root.addView(drawer,new FrameLayout.LayoutParams(285*d,-1,Gravity.START));return new Controller(drawer,buttons,previous);}
 private static void navigate(Activity a,int action){if(action==0){if(a instanceof VodActivity){((VodActivity)a).closeDrawer();return;}a.startActivity(new Intent(a,VodActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));return;}if(action==1){a.startActivity(new Intent(a,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP|Intent.FLAG_ACTIVITY_SINGLE_TOP));a.finish();return;}if(action==2)section(a,0,"novita","Novità",0,"");else if(action==3)section(a,0,"releases","Nuove uscite",0,"");else if(action==4)section(a,1,"film","Film",0,"");else if(action==5)section(a,2,"series","Serie TV",0,"");else if(action==6)section(a,4,"continue","Continua a guardare",0,"");else if(action==7)section(a,3,"favorites","Preferiti",0,"");else if(action==8)a.startActivity(new Intent(a,VodCatalogueActivity.class).putExtra("searchPage",true).putExtra("sectionTitle","Cerca").putExtra("startMode",0));else a.startActivity(new Intent(a,VodSettingsActivity.class));}
 static void section(Activity a,int mode,String kind,String title,int provider,String providerName){a.startActivity(new Intent(a,VodCatalogueActivity.class).putExtra("startMode",mode).putExtra("sectionKind",kind).putExtra("sectionTitle",title).putExtra("providerId",provider).putExtra("providerName",providerName));}
}
