package it.carmine.streamplayer;

import android.content.*;import org.json.*;import java.util.*;

/** Local favourites and resume markers, without storing any video. */
final class VodLibrary {
 static String key(String source,String title,String episode){return source+":"+title+":"+episode;}
 static SharedPreferences prefs(Context c){String uid=CloudSync.uid(c);return c.getSharedPreferences(uid.isEmpty()?"vodLibrary":"vodLibrary_"+VodCache.digest(uid),0);}
 static boolean favorite(Context c,String source,String id){return prefs(c).contains("fav:"+source+":"+id);}
 static void favorite(Context c,String source,VodSource.Title t){String k="fav:"+source+":"+TmdbClient.identity(t);SharedPreferences.Editor e=prefs(c).edit();if(prefs(c).contains(k))e.remove(k);else e.putString(k,t.json.toString());e.apply();CloudSync.changed(c,k,prefs(c).getString(k,null));}
 static List<VodSource.Title> titles(Context c,VodSettings.Source source,boolean history){LinkedHashMap<String,VodSource.Title> list=new LinkedHashMap<>();List<Map.Entry<String,?>> entries=new ArrayList<>(prefs(c).getAll().entrySet());entries.sort((a,b)->Long.compare(stamp(b.getValue()),stamp(a.getValue())));for(Map.Entry<String,?> e:entries)if(e.getKey().startsWith((history?"history:":"fav:")+source.id+":")){try{JSONObject j=new JSONObject(String.valueOf(e.getValue()));JSONObject title=history?j.getJSONObject("title"):j;VodSource.Title t=new VodSource.Title(title,source.url.replace("https://","https://cdn."));if(!list.containsKey(t.id))list.put(t.id,t);}catch(Exception ignored){}}return new ArrayList<>(list.values());}
 static long stamp(Object s){try{return new JSONObject(String.valueOf(s)).optLong("time");}catch(Exception e){return 0;}}
 static long position(Context c,String source,String id,String episode){try{return new JSONObject(prefs(c).getString("history:"+key(source,id,episode),"{}")).optLong("position");}catch(Exception e){return 0;}}
 static JSONObject latest(Context c,String source,String id){JSONObject best=null;for(Map.Entry<String,?> e:prefs(c).getAll().entrySet())if(e.getKey().startsWith("history:"+source+":"+id+":"))try{JSONObject j=new JSONObject(String.valueOf(e.getValue()));if(best==null||j.optLong("time")>best.optLong("time"))best=j;}catch(Exception ignored){}return best;}
 static void progress(Context c,String source,VodSource.Title title,String episode,String label,long position,long duration){if(position<1000)return;JSONObject j=new JSONObject();try{j.put("title",title.json);j.put("episode",episode);j.put("label",label);j.put("position",duration>0&&position>=duration-Math.min(30000,duration/20)?0:position);j.put("duration",duration);j.put("completed",duration>0&&position>=duration-Math.min(30000,duration/20));j.put("time",System.currentTimeMillis());}catch(Exception ignored){}prefs(c).edit().putString("history:"+key(source,title.id,episode),j.toString()).apply();}
 static void linkedProgress(Context c,VodSettings.Source source,VodSource.Title title,String episode,String label,long position,long duration){inferEpisode(title,label);JSONObject metadata=title.json.optJSONObject("_metadata");if(metadata==null||position<1000)return;try{VodSource.Title t=new VodSource.Title(metadata,"");JSONObject j=new JSONObject();j.put("title",metadata);j.put("provider",source.json());j.put("providerTitle",title.json);j.put("episode",episode);j.put("label",label);j.put("position",duration>0&&position>=duration-Math.min(30000,duration/20)?0:position);j.put("duration",duration);j.put("completed",duration>0&&position>=duration-Math.min(30000,duration/20));j.put("time",System.currentTimeMillis());j.put("seasonNumber",title.json.optInt("_seasonNumber"));j.put("episodeNumber",title.json.optInt("_episodeNumber"));j.put("queue",title.json.optJSONArray("_queue"));String record="history:"+key("tmdb",t.id,CloudRecords.episodeKey(title.json.optInt("_seasonNumber"),title.json.optInt("_episodeNumber"),episode));prefs(c).edit().putString(record,j.toString()).apply();CloudSync.changed(c,record,j.toString());}catch(Exception ignored){}}
 static void inferEpisode(VodSource.Title title,String label){if(title.json.optInt("_seasonNumber")>0&&title.json.optInt("_episodeNumber")>0)return;java.util.regex.Matcher m=java.util.regex.Pattern.compile("S(\\d+).*?E(\\d+)").matcher(label==null?"":label);if(m.find())try{title.json.put("_seasonNumber",Integer.parseInt(m.group(1)));title.json.put("_episodeNumber",Integer.parseInt(m.group(2)));}catch(Exception ignored){}}
 static boolean watchlisted(Context c,String scope,String id){return prefs(c).contains("watch:"+scope+":"+id);}
 static void watchlist(Context c,String scope,VodSource.Title title){String id=TmdbClient.identity(title),key="watch:"+scope+":"+id;String value=watchlisted(c,scope,id)?null:title.json.toString();put(c,key,value);}
 static void put(Context c,String key,String value){SharedPreferences.Editor edit=prefs(c).edit();if(value==null)edit.remove(key);else edit.putString(key,value);edit.apply();CloudSync.changed(c,key,value);}
 static void removeHistory(Context c,String scope,String id){Set<String> remove=new HashSet<>();Map<String,?> entries=prefs(c).getAll();for(String key:entries.keySet())if(key.startsWith("history:"+scope+":"+id+":")){remove.add(key);try{JSONObject h=new JSONObject(String.valueOf(entries.get(key))),provider=h.optJSONObject("provider"),title=h.optJSONObject("providerTitle");if(provider!=null&&title!=null)for(String local:entries.keySet())if(local.startsWith("history:"+provider.optString("id")+":"+title.optString("id")+":"))remove.add(local);}catch(Exception ignored){}}for(String key:remove)put(c,key,null);}
 static List<VodSource.Title> watchlistTitles(Context c,VodSettings.Source source){List<VodSource.Title> out=new ArrayList<>();for(Map.Entry<String,?> e:prefs(c).getAll().entrySet())if(e.getKey().startsWith("watch:"+source.id+":"))try{out.add(new VodSource.Title(new JSONObject(e.getValue().toString()),""));}catch(Exception ignored){}out.sort(Comparator.comparing(t->t.name));return out;}
 static String clock(long position){long seconds=Math.max(0,position)/1000;return seconds>=3600?String.format(Locale.ITALIAN,"%d:%02d:%02d",seconds/3600,seconds/60%60,seconds%60):String.format(Locale.ITALIAN,"%d:%02d",seconds/60,seconds%60);}
 static int percent(JSONObject history){long duration=history==null?0:history.optLong("duration");return duration<=0?0:(int)Math.max(0,Math.min(100,history.optLong("position")*100/duration));}
 static void restart(Context c,String source,VodSource.Title title,String episode){try{JSONObject local=latest(c,source,title.id);if(local!=null){local.put("position",0);local.put("completed",false);local.put("time",System.currentTimeMillis());put(c,"history:"+key(source,title.id,episode),local.toString());}JSONObject metadata=title.json.optJSONObject("_metadata");if(metadata!=null){VodSource.Title tmdb=new VodSource.Title(metadata,"");JSONObject latest=latest(c,"tmdb",tmdb.id);if(latest!=null){latest.put("position",0);latest.put("completed",false);latest.put("time",System.currentTimeMillis());put(c,"history:"+key("tmdb",tmdb.id,CloudRecords.episodeKey(title.json.optInt("_seasonNumber"),title.json.optInt("_episodeNumber"),episode)),latest.toString());}}}catch(Exception ignored){}}
}
