package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;
import androidx.media3.common.*;import androidx.media3.datasource.*;import androidx.media3.exoplayer.*;import androidx.media3.exoplayer.hls.HlsMediaSource;import androidx.media3.ui.*;
import org.json.*;import java.util.concurrent.*;import java.util.*;

public class VodPlayerActivity extends Activity {
 private final ExecutorService worker=Executors.newSingleThreadExecutor();private final Handler ui=new Handler(Looper.getMainLooper());private Future<?> task;private int generation,index=-1;private boolean destroyed,active,resumePlayback,consumeOk;
 private AudioDelay audioDelay;private String resolvedWebUrl="";private Map<String,String> resolvedWebHeaders=new HashMap<>();
 private long initialPosition=-1;private Button nextButton;private ExoPlayer player;private PlayerView video;private LinearLayout menu;private TextView status;private ProgressBar loading;private VodSettings.Source source;private VodSource.Title title;private String episode="",label="";private JSONArray episodes=new JSONArray();
 private final Runnable hideMenu=()->{if(menu!=null&&menu.getVisibility()==View.VISIBLE){menu.setVisibility(View.GONE);if(video!=null)video.requestFocus();}};
 protected boolean engineEnabled(){return true;}protected VodSource.Fetcher fetcher(){return VodSource.HTTP;}
 private int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 private Button button(String s){Button b=new Button(this);b.setAllCaps(false);b.setText(s);b.setTextSize(14);b.setMinWidth(0);b.setMinimumWidth(0);UiTheme.navigation(b);return b;}
 @Override public void onCreate(Bundle saved){super.onCreate(saved);VodNetwork.initialize(this);try{JSONObject s=new JSONObject(getIntent().getStringExtra("source"));source=new VodSettings.Source(s.getString("id"),s.getString("name"),VodSource.base(s.getString("url")),s.optString("type","streamingcommunity"));title=new VodSource.Title(new JSONObject(getIntent().getStringExtra("titleJson")),source.url.replace("https://","https://cdn."));episode=getIntent().getStringExtra("episode");if(episode==null)episode="";label=getIntent().getStringExtra("label");if(label==null)label=title.name;episodes=new JSONArray(getIntent().getStringExtra("episodes"));index=getIntent().getIntExtra("index",-1);initialPosition=getIntent().getLongExtra("startPosition",-1);}catch(Exception e){finish();return;}
  String detected=getIntent().getStringExtra("resolvedWebUrl");if(title.json.has("_web_page")&&WebMovieLinks.supported(source.url)&&WebMovieLinks.media(detected)){resolvedWebUrl=detected;try{JSONObject headers=new JSONObject(getIntent().getStringExtra("resolvedWebHeaders"));for(String key:new String[]{"Referer","Origin","Cookie","User-Agent"})if(headers.has(key))resolvedWebHeaders.put(key,headers.getString(key));}catch(Exception ignored){}}
  getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(5894);FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);setContentView(root);video=new PlayerView(this);video.setTag("vodVideo");video.setKeepScreenOn(true);video.setShowBuffering(PlayerView.SHOW_BUFFERING_NEVER);video.setControllerShowTimeoutMs(4500);video.setShowRewindButton(true);video.setShowFastForwardButton(true);video.setControllerAutoShow(false);video.setShowSubtitleButton(true);root.addView(video,new FrameLayout.LayoutParams(-1,-1));loading=new ProgressBar(this);root.addView(loading,new FrameLayout.LayoutParams(dp(52),dp(52),Gravity.CENTER));
  menu=new LinearLayout(this);menu.setOrientation(1);menu.setPadding(dp(16),dp(10),dp(16),dp(8));menu.setBackgroundColor(0xee151619);menu.setTag("vodPlayerMenu");root.addView(menu,new FrameLayout.LayoutParams(-1,-2,Gravity.TOP));status=new TextView(this);status.setTextColor(UiTheme.TEXT);status.setTextSize(17);status.setTypeface(UiTheme.medium(this));menu.addView(status);LinearLayout row=new LinearLayout(this);menu.addView(row,new LinearLayout.LayoutParams(-1,dp(48)));Button retry=button("Riprova"),tracks=button("Audio / sottotitoli"),next=button("Episodio successivo"),other=button("Altra fonte"),close=button("‹ Catalogo");for(Button b:new Button[]{retry,tracks,next,other,close})row.addView(b,new LinearLayout.LayoutParams(0,-1,1));retry.setOnClickListener(v->{if(!resolvedWebUrl.isEmpty())retryWebMovie();else resolve();});tracks.setOnClickListener(v->tracks());nextButton=next;next.setEnabled(canNext());other.setOnClickListener(v->{saveProgress();setResult(RESULT_FIRST_USER,new Intent().putExtra("position",player==null?initialPosition:player.getCurrentPosition()));finish();});next.setOnClickListener(v->next());close.setOnClickListener(v->finish());
  menu.setVisibility(View.GONE);video.requestFocus();if(!engineEnabled()){loading.setVisibility(View.GONE);return;}audioDelay=AudioDelay.create(this,"vod:"+TmdbClient.identity(title));player=new ExoPlayer.Builder(this,AudioDelay.renderers(this,audioDelay)).setSeekBackIncrementMs(15000).setSeekForwardIncrementMs(15000).build();restoreTracks();video.setPlayer(player);player.addListener(new Player.Listener(){public void onPlaybackStateChanged(int state){if(state==Player.STATE_READY)loading.setVisibility(View.GONE);if(state==Player.STATE_BUFFERING)loading.setVisibility(View.VISIBLE);if(state==Player.STATE_ENDED){saveProgress();CloudSync.flush(VodPlayerActivity.this,true);if(canNext()){new AlertDialog.Builder(VodPlayerActivity.this).setTitle("Episodio terminato").setPositiveButton("Episodio successivo",(d,n)->next()).setNegativeButton("Catalogo",(d,n)->finish()).show();}}}public void onIsPlayingChanged(boolean playing){if(!playing&&player!=null&&player.getPlaybackState()==Player.STATE_READY){saveProgress();CloudSync.flush(VodPlayerActivity.this,true);}}public void onPlayerError(PlaybackException error){saveProgress();loading.setVisibility(View.GONE);status.setText(title.name+" · video non disponibile · Riprova o cambia fonte");showMenu(false);}});resolve();ui.postDelayed(checkpoint,10000);
 }
 private final Runnable checkpoint=new Runnable(){public void run(){if(destroyed)return;if(active)saveProgress();ui.postDelayed(this,10000);}};
 private void resolve(){if(player==null||destroyed)return;saveProgress();final int request=++generation;final String currentEpisode=episode;final long position=initialPosition>=0?initialPosition:VodLibrary.position(this,source.id,title.id,currentEpisode);initialPosition=-1;if(task!=null)task.cancel(true);player.stop();loading.setVisibility(View.VISIBLE);menu.setVisibility(View.GONE);status.setText(title.name+" · "+label+" · apertura…");
  task=worker.submit(()->{try{VodSource.Stream stream=!resolvedWebUrl.isEmpty()?new VodSource.Stream(resolvedWebUrl,resolvedWebHeaders.getOrDefault("Referer",source.url+"/")):source.vixsrc()?VixSrc.resolve(source,title,currentEpisode,fetcher()):title.json.has("_web_page")?VodWebSource.resolve(title.json.getString("_web_page"),fetcher()):VodSource.resolve(source.url,title.id,currentEpisode,fetcher());runOnUiThread(()->{if(destroyed||request!=generation)return;Map<String,String> headers=new HashMap<>();headers.put("Referer",stream.referer);if(stream.url.equals(resolvedWebUrl))headers.putAll(resolvedWebHeaders);if(source.vixsrc())headers.put("Origin",source.url);androidx.media3.datasource.okhttp.OkHttpDataSource.Factory http=new androidx.media3.datasource.okhttp.OkHttpDataSource.Factory(VodNetwork.client().newBuilder().callTimeout(0,java.util.concurrent.TimeUnit.SECONDS).build()).setUserAgent(headers.containsKey("User-Agent")?headers.remove("User-Agent"):VodSource.USER_AGENT).setDefaultRequestProperties(headers);MediaItem item=new MediaItem.Builder().setUri(stream.url).setMimeType(MimeTypes.APPLICATION_M3U8).setMediaId(VodLibrary.key(source.id,title.id,currentEpisode)).build();if(stream.url.matches("(?i).*\\.mp4(?:\\?.*)?"))player.setMediaSource(new androidx.media3.exoplayer.source.ProgressiveMediaSource.Factory(http).createMediaSource(new MediaItem.Builder().setUri(stream.url).setMimeType(MimeTypes.VIDEO_MP4).build()),position);else player.setMediaSource(new HlsMediaSource.Factory(http).createMediaSource(item),position);player.prepare();player.setPlayWhenReady(active);resumePlayback=!active;video.requestFocus();});}catch(Exception e){runOnUiThread(()->{if(destroyed||request!=generation)return;loading.setVisibility(View.GONE);status.setText(title.name+" · "+e.getMessage());showMenu(false);});}});
 }
 private void retryWebMovie(){
  saveProgress();long resume=player==null?0:Math.max(0,player.getCurrentPosition());
  Intent resolver=new Intent(this,VodSettings.cb01(source)?CbCatalogueActivity.class:VodBrowserActivity.class).putExtra("moviePage",title.json.optString("_web_page")).putExtra("url",title.json.optString("_web_page")).putExtra("title",title.name).putExtra("nativeAttempt",true).putExtra("source",source.json().toString()).putExtra("titleJson",title.json.toString()).putExtra("episode", "").putExtra("label",title.name).putExtra("startPosition",resume);
  resolver.addFlags(Intent.FLAG_ACTIVITY_FORWARD_RESULT);startActivity(resolver);finish();
 }
 private void saveProgress(){try{title.json.put("_queue",episodes);if(index>=0&&index<episodes.length())title.json.put("_episodeNumber",episodes.getJSONObject(index).optInt("number"));}catch(Exception ignored){}if(player!=null&&player.getCurrentPosition()>1000){VodLibrary.progress(this,source.id,title,episode,label,player.getCurrentPosition(),player.getDuration());VodLibrary.linkedProgress(this,source,title,episode,label,player.getCurrentPosition(),player.getDuration());}}
 private static int seasonNumber(JSONObject s){return s==null?0:s.optInt("number",s.optInt("season_number"));}
 private boolean canNext(){if(index>=0&&index+1<episodes.length())return true;JSONArray seasons=title.json.optJSONArray("seasons");if(seasons!=null)for(int i=0;i<seasons.length();i++)if(seasonNumber(seasons.optJSONObject(i))>title.json.optInt("_seasonNumber"))return true;return false;}
 private void next(){if(player==null||!canNext())return;saveProgress();CloudSync.flush(this,true);if(index>=0&&index+1<episodes.length()){try{JSONObject e=episodes.getJSONObject(++index);episode=source.vixsrc()?String.valueOf(e.optInt("number")):e.getString("id");label="S"+title.json.optInt("_seasonNumber")+" · E"+e.optInt("number")+" · "+e.optString("name");title.json.put("_episodeNumber",e.optInt("number"));nextButton.setEnabled(canNext());initialPosition=0;player.clearMediaItems();resolve();}catch(Exception ignored){}return;}JSONArray seasons=title.json.optJSONArray("seasons");int number=Integer.MAX_VALUE;for(int i=0;seasons!=null&&i<seasons.length();i++){int value=seasonNumber(seasons.optJSONObject(i));if(value>title.json.optInt("_seasonNumber"))number=Math.min(number,value);}if(number==Integer.MAX_VALUE)return;final int season=number,request=++generation;loading.setVisibility(View.VISIBLE);worker.submit(()->{try{JSONArray q;if(source.vixsrc())q=TmdbClient.episodes(title,season,TmdbClient.key(this),fetcher());else q=VodSource.page(source.url,title.path()+"/season-"+season,fetcher()).getJSONObject("loadedSeason").getJSONArray("episodes");if(q.length()==0)throw new Exception("Stagione senza episodi");runOnUiThread(()->{if(destroyed||request!=generation)return;try{episodes=q;index=0;JSONObject e=q.getJSONObject(0);episode=source.vixsrc()?String.valueOf(e.optInt("number")):e.getString("id");label="S"+season+" · E"+e.optInt("number")+" · "+e.optString("name");title.json.put("_seasonNumber",season);title.json.put("_episodeNumber",e.optInt("number"));nextButton.setEnabled(canNext());initialPosition=0;player.clearMediaItems();resolve();}catch(Exception ignored){}});}catch(Exception e){runOnUiThread(()->{if(destroyed||request!=generation)return;loading.setVisibility(View.GONE);status.setText("Episodio successivo non disponibile · scegli una fonte");showMenu(false);});}});}
 private void restoreTracks(){android.content.SharedPreferences prefs=getSharedPreferences("vodPlayback",0);player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setPreferredAudioLanguages(prefs.getString("audioLanguage","it"),"ita").setPreferredTextLanguage(prefs.getString("subtitleLanguage","it")).setTrackTypeDisabled(C.TRACK_TYPE_TEXT,prefs.getBoolean("subtitlesDisabled",true)).build());}
 private void showMenu(){showMenu(true);}private void showMenu(boolean timed){menu.setVisibility(View.VISIBLE);video.hideController();menu.getChildAt(1).requestFocus();ui.removeCallbacks(hideMenu);if(timed)ui.postDelayed(hideMenu,6500);}
 private void dismissMenu(){ui.removeCallbacks(hideMenu);menu.setVisibility(View.GONE);video.requestFocus();}
 private void tracks(){if(player==null)return;java.util.List<String> labels=new java.util.ArrayList<>();java.util.List<Runnable> actions=new java.util.ArrayList<>();labels.add("Sincronizzazione audio · "+audioDelay.get()+" ms");actions.add(()->AudioDelay.menu(this,"vod:"+TmdbClient.identity(title),audioDelay,player));labels.add("Sottotitoli: disattivati");actions.add(()->{getSharedPreferences("vodPlayback",0).edit().putBoolean("subtitlesDisabled",true).apply();player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setTrackTypeDisabled(C.TRACK_TYPE_TEXT,true).build());});labels.add("Audio: automatico (preferenza italiano)");actions.add(()->{getSharedPreferences("vodPlayback",0).edit().putString("audioLanguage","it").apply();player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().clearOverridesOfType(C.TRACK_TYPE_AUDIO).setPreferredAudioLanguages("it","ita").build());});for(Tracks.Group group:player.getCurrentTracks().getGroups()){int type=group.getType();if(type!=C.TRACK_TYPE_AUDIO&&type!=C.TRACK_TYPE_TEXT)continue;for(int i=0;i<group.length;i++){if(!group.isTrackSupported(i))continue;final int track=i;Format f=group.getTrackFormat(i);String name=f.label!=null?f.label:f.language!=null?f.language:"Traccia "+(i+1);labels.add((type==C.TRACK_TYPE_AUDIO?"Audio: ":"Sottotitoli: ")+name+(group.isTrackSelected(i)?" ✓":""));actions.add(()->{android.content.SharedPreferences.Editor edit=getSharedPreferences("vodPlayback",0).edit();if(type==C.TRACK_TYPE_AUDIO)edit.putString("audioLanguage",f.language==null?"it":f.language);else edit.putString("subtitleLanguage",f.language==null?"it":f.language).putBoolean("subtitlesDisabled",false);edit.apply();player.setTrackSelectionParameters(player.getTrackSelectionParameters().buildUpon().setTrackTypeDisabled(type,false).setOverrideForType(new TrackSelectionOverride(group.getMediaTrackGroup(),track)).build());});}}new AlertDialog.Builder(this).setTitle("Audio e sottotitoli").setItems(labels.toArray(new String[0]),(d,n)->actions.get(n).run()).setNegativeButton("Chiudi",null).show();}
 @Override public void onBackPressed(){if(menu.getVisibility()==View.VISIBLE){saveProgress();finish();return;}video.hideController();showMenu(false);}
 @Override public boolean dispatchKeyEvent(KeyEvent e){int key=e.getKeyCode();if(consumeOk&&(key==KeyEvent.KEYCODE_DPAD_CENTER||key==KeyEvent.KEYCODE_ENTER)){if(e.getAction()==KeyEvent.ACTION_UP)consumeOk=false;return true;}if(key==KeyEvent.KEYCODE_MENU){if(e.getAction()==KeyEvent.ACTION_DOWN&&e.getRepeatCount()==0){if(menu.getVisibility()==View.VISIBLE)dismissMenu();else showMenu();}return true;}if(menu.getVisibility()==View.VISIBLE&&e.getAction()==KeyEvent.ACTION_DOWN){ui.removeCallbacks(hideMenu);ui.postDelayed(hideMenu,6500);}if(menu.getVisibility()!=View.VISIBLE&&e.getAction()==KeyEvent.ACTION_DOWN){if((key==KeyEvent.KEYCODE_DPAD_CENTER||key==KeyEvent.KEYCODE_ENTER)&&!video.isControllerFullyVisible()){video.showController();consumeOk=true;return true;}if(player!=null&&(key==KeyEvent.KEYCODE_DPAD_LEFT||key==KeyEvent.KEYCODE_DPAD_RIGHT)&&!video.isControllerFullyVisible()){long duration=player.getDuration();long pos=Math.max(0,player.getCurrentPosition()+(key==KeyEvent.KEYCODE_DPAD_RIGHT?15000:-15000));player.seekTo(duration>0?Math.min(pos,duration):pos);return true;}}return super.dispatchKeyEvent(e);}
 @Override protected void onResume(){super.onResume();active=true;if(player!=null&&resumePlayback){player.play();resumePlayback=false;}}
 @Override protected void onPause(){active=false;saveProgress();CloudSync.flush(this,true);if(player!=null){resumePlayback=player.getPlayWhenReady();player.pause();}super.onPause();}
 @Override protected void onDestroy(){destroyed=true;++generation;ui.removeCallbacksAndMessages(null);if(task!=null)task.cancel(true);worker.shutdownNow();if(player!=null){video.setPlayer(null);player.release();player=null;}super.onDestroy();}
}
