package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;

/** Dedicated settings page in the current graphite/amber VOD language. */
public class VodSettingsActivity extends Activity {
 private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 private Button item(String label){Button b=new Button(this);b.setText(label);b.setAllCaps(false);b.setTextSize(16);b.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);UiTheme.navigation(b);return b;}
 @Override public void onCreate(Bundle state){super.onCreate(state);getWindow().getDecorView().setSystemUiVisibility(5894);ScrollView scroll=new ScrollView(this);scroll.setTag("vodSettingsPage");scroll.setBackgroundColor(0xff151619);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(42),dp(28),dp(42),dp(28));scroll.addView(root);setContentView(scroll);TextView title=new TextView(this);title.setText("Impostazioni R. ITA TV");title.setTextSize(28);title.setTextColor(UiTheme.AMBER);title.setTypeface(UiTheme.medium(this));root.addView(title,new LinearLayout.LayoutParams(-1,dp(58)));TextView note=new TextView(this);note.setText("Catalogo predefinito TMDB · riproduzione predefinita VixSrc\nLe modifiche manuali sono temporanee e vengono azzerate al riavvio o all'aggiornamento.");note.setTextColor(UiTheme.TEXT);note.setTextSize(14);root.addView(note,new LinearLayout.LayoutParams(-1,dp(66)));
  Button account=item("Account e sincronizzazione Firebase");account.setOnClickListener(v->startActivity(new Intent(this,CloudActivity.class)));root.addView(account,new LinearLayout.LayoutParams(-1,dp(54)));Button catalogue=item("Catalogo temporaneo · "+VodSession.catalogue(this).name);catalogue.setOnClickListener(v->VodSession.catalogueMenu(this,()->catalogue.setText("Catalogo temporaneo · "+VodSession.catalogue(this).name)));root.addView(catalogue,new LinearLayout.LayoutParams(-1,dp(54)));Button source=item("Fonte video temporanea · "+VodSession.video(this).name);source.setOnClickListener(v->VodSession.videoMenu(this,()->source.setText("Fonte video temporanea · "+VodSession.video(this).name)));root.addView(source,new LinearLayout.LayoutParams(-1,dp(54)));Button update=item("Controlla aggiornamenti app");update.setOnClickListener(v->AppUpdater.check(this,true));root.addView(update,new LinearLayout.LayoutParams(-1,dp(54)));Button downloaded=item("Installa aggiornamento scaricato");downloaded.setOnClickListener(v->AppUpdater.manage(this));root.addView(downloaded,new LinearLayout.LayoutParams(-1,dp(54)));Button backup=item("Backup e ripristino");backup.setOnClickListener(v->startActivity(new Intent(this,BackupActivity.class)));root.addView(backup,new LinearLayout.LayoutParams(-1,dp(54)));Button vodSources=item("Gestisci tutte le fonti VOD");vodSources.setOnClickListener(v->VodSettings.manage(this,()->{}));root.addView(vodSources,new LinearLayout.LayoutParams(-1,dp(54)));
  Button network=item("DNS VOD e rete");network.setOnClickListener(v->VodNetwork.settings(this,()->{}));root.addView(network,new LinearLayout.LayoutParams(-1,dp(54)));
  Button liveSources=item("Fonti TV Live (Vavoo / Gomstream / DNS)");liveSources.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Fonti Live TV").setItems(new String[]{"Vavoo","Gomstream","DNS Live"},(d,n)->{if(n==0)VavooSettings.edit(this,()->{});else if(n==1)GomstreamSettings.edit(this,()->{});else LiveNetwork.settings(this,()->{});}).show());root.addView(liveSources,new LinearLayout.LayoutParams(-1,dp(54)));
  Button reset=item("Ripristina TMDB + VixSrc");reset.setOnClickListener(v->{VodSession.reset();catalogue.setText("Catalogo temporaneo · "+VodSession.catalogue(this).name);source.setText("Fonte video temporanea · "+VodSession.video(this).name);Toast.makeText(this,"Predefiniti ripristinati",Toast.LENGTH_SHORT).show();});root.addView(reset,new LinearLayout.LayoutParams(-1,dp(54)));Button about=item("Versione dell’app · "+BuildConfig.VERSION_NAME);about.setOnClickListener(v->TmdbClient.credits(this));root.addView(about,new LinearLayout.LayoutParams(-1,dp(54)));account.requestFocus();}
 @Override public void onBackPressed(){finish();}
}
