package it.carmine.streamplayer;

import android.app.*;import android.content.*;import android.widget.*;import android.text.InputType;
import org.json.*;import java.net.URI;import java.util.*;

/** Sources have stable identifiers, so changing a domain preserves local progress. */
final class VodSettings {
 static final String DEFAULT="https://streamingcommunityz.promo";
 static final String VIXSRC="https://vixsrc.to";
 static final String DEFAULT_UNITY="https://streamingunity.fun";
 static final String DEFAULT_FEED="https://pastebin.com/raw/KgQ4jTy6";
 static final class Source {
  final String id,name,url,type;Source(String i,String n,String u){this(i,n,u,"streamingcommunity");}Source(String i,String n,String u,String t){id=i;name=n;url=u;type=t;}
  boolean nativeCatalog(){return "streamingcommunity".equals(type)||scuapi();}boolean vixsrc(){return "vixsrc".equals(type)||"vixsrc".equals(id);}boolean scuapi(){return "scuapi".equals(type)||"scuapi".equals(id);}boolean tmdb(){return "tmdb".equals(type)||"tmdb".equals(id);}boolean cinesearch(){return "cinesearch".equals(type)||"cinesearch".equals(id);}
  JSONObject json(){JSONObject j=new JSONObject();try{j.put("id",id);j.put("name",name);j.put("url",url);j.put("type",type);}catch(Exception ignored){}return j;}
 }
 static android.content.SharedPreferences prefs(Context c){return c.getSharedPreferences("vod",0);}
 static boolean startsWithVod(Context c){return prefs(c).getBoolean("startWithVod",false);}
 static void startup(Activity a){String[] choices={"Canali TV","VOD"};new AlertDialog.Builder(a).setTitle("Schermata iniziale").setSingleChoiceItems(choices,startsWithVod(a)?1:0,(d,n)->{prefs(a).edit().putBoolean("startWithVod",n==1).apply();d.dismiss();Toast.makeText(a,"Avvio app: "+choices[n],Toast.LENGTH_SHORT).show();}).setNegativeButton("Annulla",null).show();}
 static boolean unity(String url){try{String h=new URI(url).getHost().replaceFirst("^www\\.","");return h.startsWith("streamingunity.");}catch(Exception e){return false;}}
 static List<Source> retained(List<Source> saved){Source community=null,vix=null,api=null;LinkedHashMap<String,Source> others=new LinkedHashMap<>();for(Source x:saved){if(x.id.equals("streamingcommunity"))community=x;else if(x.vixsrc())vix=x;else if(x.scuapi())api=x;else if(!x.cinesearch())try{if(!torrent(new URI(x.url).getHost()))others.put(x.id,x);}catch(Exception ignored){}}if(community==null)community=new Source("streamingcommunity","Streaming Community",DEFAULT);if(vix==null)vix=new Source("vixsrc","VixSrc",VIXSRC,"vixsrc");if(api==null)api=new Source("scuapi","SC API · Blu-Tiger",community.url,"scuapi");List<Source> result=new ArrayList<>();result.add(new Source(community.id,"Streaming Community",community.url));result.add(new Source("vixsrc","VixSrc",vix.url,"vixsrc"));result.add(new Source("scuapi","SC API · Blu-Tiger",api.url,"scuapi"));result.addAll(others.values());if(saved.isEmpty())result.add(new Source("list_streamingunity_fun","StreamingUnity",DEFAULT_UNITY));return result;}
 static List<Source> sources(Context c){List<Source> saved;try{saved=parse(prefs(c).getString("sources",""));}catch(Exception ignored){saved=new ArrayList<>();}List<Source> list=retained(saved);String normalized=serialized(list);if(!normalized.equals(prefs(c).getString("sources","")))prefs(c).edit().putString("sources",normalized).apply();return list;}
 static boolean torrent(String host){return host!=null&&(host.toLowerCase(Locale.ROOT).contains("torrent")||host.matches("(?i)(?:www\\.)?(?:1337x|rargb|rarbg|thepiratebay|limetorrents|yts)\\..*"));}
 static List<Source> parse(String json)throws Exception{
  JSONArray a; if(json.trim().startsWith("{")){a=new JSONObject(json).getJSONArray("sources");}else{a=new JSONArray();for(String line:json.split("\\R")){String raw=line.trim();if(raw.isEmpty()||raw.startsWith("#"))continue;String url=VodSource.base(raw);String host=new URI(url).getHost().replaceFirst("^www\\.","");if(torrent(host))continue;String type=host.startsWith("streamingcommunity")||host.startsWith("streamingunity.")?"streamingcommunity":"web";String id=host.startsWith("streamingcommunity")?"streamingcommunity":unity(url)?"list_streamingunity_fun":host.replaceAll("[^a-zA-Z0-9_-]","_");String name=host;JSONObject j=new JSONObject();j.put("id",id);j.put("name",name);j.put("url",url);j.put("type",type);a.put(j);}}LinkedHashMap<String,Source> result=new LinkedHashMap<>();if(a.length()>40)throw new IllegalArgumentException("Massimo 40 fonti");
  for(int i=0;i<a.length();i++){JSONObject j=a.getJSONObject(i);String type=j.optString("type","streamingcommunity");if(!type.equals("streamingcommunity")&&!type.equals("web")&&!type.equals("vixsrc")&&!type.equals("scuapi")&&!type.equals("cinesearch"))continue;if(torrent(new URI(VodSource.base(j.getString("url"))).getHost()))continue;String id=j.optString("id"),name=j.optString("name").trim();if(!id.matches("[a-zA-Z0-9_-]{1,64}")||name.isEmpty()||name.length()>80)throw new IllegalArgumentException("Nome o ID della fonte non valido");result.put(id,new Source(id,name,VodSource.base(j.getString("url")),type));}
  if(result.isEmpty())throw new IllegalArgumentException("Nessuna fonte compatibile nella lista");return new ArrayList<>(result.values());
 }
 static String serialized(List<Source> list){JSONArray a=new JSONArray();for(Source source:list)a.put(source.json());JSONObject j=new JSONObject();try{j.put("sources",a);}catch(Exception ignored){}return j.toString();}
 static void save(Context c,List<Source> list){prefs(c).edit().putString("sources",serialized(retained(list))).apply();}
 static Source active(Context c){List<Source> s=sources(c);String id=prefs(c).getString("active","streamingcommunity");for(Source x:s)if(x.id.equals(id))return x;return s.get(0);}
 static Source primary(Context c){return VodSession.video(c);}
 static void choose(Context c,Source s){prefs(c).edit().putString("active",s.id).putString("primarySource",s.id).apply();}
 static String cineSearchUrl(Context c){return prefs(c).getString("cineSearchUrl","");}
 static boolean cb01(Source s){return s!=null&&(s.id.equals("cb01")||s.name.toLowerCase(Locale.ROOT).matches(".*(?:cb01|cineblog).*" )||s.url.matches("(?i)https://(?:www\\.)?(?:cb01|cineblog).*"));}
 static Source cb01(Context c){for(Source s:sources(c))if(cb01(s))return s;return new Source("cb01","CB01","https://cb01uno.wiki","web");}
 static List<Source> catalogues(Context c){List<Source> out=new ArrayList<>();for(Source s:sources(c))if(s.id.equals("streamingcommunity")){out.add(s);break;}out.add(new Source("tmdb","TMDB","https://www.themoviedb.org","tmdb"));for(Source s:sources(c))if(s.vixsrc())out.add(s);out.add(new Source("cinesearch","CineSearch API",cineSearchUrl(c),"cinesearch"));for(Source s:sources(c))if(s.nativeCatalog()&&!s.id.equals("streamingcommunity")&&!s.scuapi())out.add(s);out.add(cb01(c));return out;}
 static Source catalogue(Context c){return VodSession.catalogue(c);}
 static void catalogueMenu(Activity a,Runnable changed){List<Source> list=catalogues(a);Source selected=catalogue(a);String[] labels=new String[list.size()];for(int i=0;i<list.size();i++)labels[i]=(list.get(i).id.equals(selected.id)?"✓ ":"")+list.get(i).name+(list.get(i).tmdb()?" · catalogo generale":list.get(i).vixsrc()?" · solo titoli disponibili su VixSrc":list.get(i).cinesearch()?(list.get(i).url.isEmpty()?" · configura server":" · server configurato"):" · catalogo della fonte");new AlertDialog.Builder(a).setTitle("Catalogo visualizzato").setItems(labels,(d,n)->{Source chosen=list.get(n);if(chosen.cinesearch()&&chosen.url.isEmpty()){editCineSearch(a,()->{prefs(a).edit().putString("catalogSource","cinesearch").apply();changed.run();});return;}prefs(a).edit().putString("catalogSource",chosen.id).apply();d.dismiss();changed.run();}).setNegativeButton("Chiudi",null).show();}
 static String feed(Context c){return prefs(c).getString("feed",DEFAULT_FEED);}
 static boolean refresh(Context c,VodSource.Fetcher fetch)throws Exception{
  String url=feed(c);if(url.isEmpty())return false;List<Source> remote=parse(fetch.get(VodSource.fresh(url),""));List<Source> list=sources(c);Set<String> removed=new HashSet<>(prefs(c).getStringSet("removedSources",Collections.emptySet()));for(Source candidate:remote){if(candidate.cinesearch()){if(!prefs(c).getBoolean("manual_cinesearch",false))prefs(c).edit().putString("cineSearchUrl",candidate.url).apply();continue;}if(candidate.id.equals("streamingcommunity")){if(!prefs(c).getBoolean("manual_scuapi",false))replace(list,"scuapi",candidate.url);continue;}if(removed.contains(candidate.id))continue;int old=-1;for(int i=0;i<list.size();i++)if(list.get(i).id.equals(candidate.id)||unity(candidate.url)&&(unity(list.get(i).url)||list.get(i).name.equals("StreamingUnity")||list.get(i).id.equals("list_streamingunity_fun")))old=i;if(old<0&&list.size()<40)list.add(candidate);else if(old>=0&&!prefs(c).getBoolean("manual_"+list.get(old).id,false)&&!(unity(candidate.url)&&prefs(c).getBoolean("unityManual",false))){Source previous=list.get(old);list.set(old,new Source(previous.id,previous.name,candidate.url,candidate.type));}}save(c,list);return true;
 }
 static void replace(List<Source> list,String id,String url){for(int i=0;i<list.size();i++)if(list.get(i).id.equals(id)){Source old=list.get(i);list.set(i,new Source(old.id,old.name,url,old.type));return;}}
 static void menu(Activity a,Runnable changed){List<Source> list=sources(a);String[] labels=new String[list.size()+3];Source active=primary(a);for(int i=0;i<list.size();i++)labels[i]=(list.get(i).id.equals(active.id)?"✓ PRINCIPALE · ":"")+list.get(i).name+(list.get(i).nativeCatalog()?" · player interno":list.get(i).vixsrc()?" · player VixSrc":" · ricerca web");labels[list.size()]="Gestisci fonti · aggiungi / modifica / rimuovi";labels[list.size()+1]="Lista automatica · URL";labels[list.size()+2]="DNS · "+VodNetwork.provider(a);
  new AlertDialog.Builder(a).setTitle("Fonti VOD").setItems(labels,(d,n)->{if(n<list.size()){choose(a,list.get(n));changed.run();}else if(n==list.size())manage(a,changed);else if(n==list.size()+1)editFeed(a,changed);else VodNetwork.settings(a,changed);}).setNegativeButton("Chiudi",null).show();
 }
 static void manage(Activity a,Runnable changed){List<Source> list=sources(a);String[] labels=new String[list.size()+2];for(int i=0;i<list.size();i++)labels[i]=list.get(i).name+" · "+list.get(i).url;labels[list.size()]="CineSearch API · "+(cineSearchUrl(a).isEmpty()?"configura URL":cineSearchUrl(a));labels[list.size()+1]="＋ Aggiungi fonte";new AlertDialog.Builder(a).setTitle("Gestisci fonti").setItems(labels,(d,n)->{if(n==list.size()){editCineSearch(a,changed);return;}if(n==list.size()+1){addSource(a,changed);return;}Source old=list.get(n);boolean fixed=old.id.equals("streamingcommunity")||old.vixsrc()||old.scuapi();new AlertDialog.Builder(a).setTitle(old.name).setItems(fixed?new String[]{"Modifica URL","Apri sito / accedi"}:new String[]{"Modifica URL","Apri sito / accedi","Rimuovi"},(dialog,action)->{if(action==0)edit(a,old,changed);else if(action==1)openSite(a,old);else{List<Source> current=sources(a);current.removeIf(x->x.id.equals(old.id));Set<String> removed=new HashSet<>(prefs(a).getStringSet("removedSources",Collections.emptySet()));removed.add(old.id);if(unity(old.url)||old.name.equals("StreamingUnity"))removed.add("list_streamingunity_fun");prefs(a).edit().putStringSet("removedSources",removed).apply();save(a,current);changed.run();}}).setNegativeButton("Chiudi",null).show();}).setNegativeButton("Chiudi",null).show();}
 static void openSite(Activity a,Source s){a.startActivity(new Intent(a,VodBrowserActivity.class).putExtra("url",s.url).putExtra("title",s.name));}
 static void addSource(Activity a,Runnable changed){LinearLayout box=new LinearLayout(a);box.setOrientation(1);EditText name=input(a,"","Nome della fonte"),url=input(a,"","https://dominio");box.addView(name);box.addView(url);AlertDialog d=new AlertDialog.Builder(a).setTitle("Aggiungi fonte").setView(box).setPositiveButton("Aggiungi",null).setNegativeButton("Annulla",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{String base=VodSource.base(url.getText().toString()),host=new URI(base).getHost();if(torrent(host))throw new IllegalArgumentException("Fonti torrent escluse");String label=name.getText().toString().trim();if(label.isEmpty()||label.length()>80)throw new IllegalArgumentException("Inserisci un nome valido");List<Source> list=sources(a);if(list.size()>=40)throw new IllegalArgumentException("Massimo 40 fonti");String id="manual_"+UUID.randomUUID().toString().replace("-","");list.add(new Source(id,label,base,host.startsWith("streamingcommunity")||unity(base)?"streamingcommunity":"web"));prefs(a).edit().putBoolean("manual_"+id,true).apply();save(a,list);d.dismiss();changed.run();}catch(Exception e){url.setError(e.getMessage());}}));d.show();}
 static EditText input(Activity a,String value,String hint){EditText e=new EditText(a);e.setSingleLine(true);e.setText(value);e.setHint(hint);e.setTextColor(UiTheme.TEXT);e.setHintTextColor(0xffa6a6aa);return e;}
 static void edit(Activity a,Source old,Runnable changed){if(old==null)return;LinearLayout box=new LinearLayout(a);box.setPadding(24,12,24,12);box.setOrientation(1);EditText url=input(a,old.url,"Dominio HTTPS");url.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_URI);box.addView(url);
  AlertDialog d=new AlertDialog.Builder(a).setTitle(old.name+" · URL").setView(box).setPositiveButton("Salva",null).setNegativeButton("Annulla",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{Source source=new Source(old.id,old.name,VodSource.base(url.getText().toString()),old.type);if(torrent(new URI(source.url).getHost()))throw new IllegalArgumentException("Fonti torrent escluse");prefs(a).edit().putBoolean("manual_"+old.id,true).apply();List<Source> list=sources(a);for(int i=0;i<list.size();i++)if(list.get(i).id.equals(old.id))list.set(i,source);if(old.id.equals("streamingcommunity")&&!prefs(a).getBoolean("manual_scuapi",false))replace(list,"scuapi",source.url);if(unity(old.url)||old.name.equals("StreamingUnity")||old.id.equals("list_streamingunity_fun"))prefs(a).edit().putBoolean("unityManual",true).apply();save(a,list);choose(a,source);d.dismiss();changed.run();}catch(Exception e){url.setError(e.getMessage());}}));d.show();
 }
 static void editCineSearch(Activity a,Runnable changed){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(24,12,24,12);TextView help=new TextView(a);help.setText("Inserisci l’URL HTTPS del backend CineSearch avviato da te. CineSearch fornisce catalogo e metadati; la riproduzione usa la fonte principale scelta nell’app.");help.setTextColor(UiTheme.TEXT);box.addView(help);EditText url=input(a,cineSearchUrl(a),"https://mio-server-cinesearch.example");box.addView(url);AlertDialog d=new AlertDialog.Builder(a).setTitle("CineSearch API · server").setView(box).setPositiveButton("Salva",null).setNeutralButton("Rimuovi",(x,n)->{prefs(a).edit().remove("cineSearchUrl").putString("catalogSource","streamingcommunity").apply();changed.run();}).setNegativeButton("Annulla",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{String base=VodSource.base(url.getText().toString());prefs(a).edit().putString("cineSearchUrl",base).putBoolean("manual_cinesearch",true).apply();d.dismiss();changed.run();}catch(Exception e){url.setError(e.getMessage());}}));d.show();}
 static void editFeed(Activity a,Runnable changed){LinearLayout box=new LinearLayout(a);box.setOrientation(1);box.setPadding(24,12,24,12);TextView help=new TextView(a);help.setText("La lista aggiunge le fonti alternative ed aggiorna gli URL non modificati manualmente. Streaming Community conserva il tuo link principale. I torrent e le fonti rimosse vengono ignorati. Lascia vuoto per disattivare gli aggiornamenti della lista.");help.setTextColor(UiTheme.TEXT);box.addView(help);EditText e=input(a,feed(a),"https://…/fonti-vod.json");box.addView(e);AlertDialog d=new AlertDialog.Builder(a).setTitle("Lista fonti automatica").setView(box).setPositiveButton("Salva",null).setNegativeButton("Annulla",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{try{String s=e.getText().toString().trim();if(!s.isEmpty()){URI u=new URI(s);if(!"https".equals(u.getScheme())||u.getHost()==null||u.getUserInfo()!=null)throw new IllegalArgumentException("Inserisci un URL HTTPS valido");}prefs(a).edit().putString("feed",s).apply();d.dismiss();changed.run();}catch(Exception ex){e.setError(ex.getMessage());}}));d.show();}
}
