package it.carmine.streamplayer;
import android.text.Html;import java.net.*;import java.util.*;import java.util.regex.*;import org.json.*;

/** Public HTML searches, with verified HLS and ordinary video element support. */
final class VodWebSource {
 static String decode(String s){return Html.fromHtml(s,Html.FROM_HTML_MODE_LEGACY).toString().trim();}
 static String attribute(String html,String key){Matcher m=Pattern.compile("\\b"+key+"\\s*=\\s*([\"'])(.*?)\\1",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);return m.find()?decode(m.group(2)):"";}
 static String canonical(String html,String fallback){Matcher tags=Pattern.compile("<(?:link|meta)\\b[^>]*>",Pattern.CASE_INSENSITIVE).matcher(html);while(tags.find()){String tag=tags.group();String u=attribute(tag,"rel").equalsIgnoreCase("canonical")?attribute(tag,"href"):attribute(tag,"property").equalsIgnoreCase("og:url")?attribute(tag,"content"):"";try{URI x=new URI(u);if("https".equals(x.getScheme())&&x.getHost()!=null)return u;}catch(Exception ignored){}}return fallback;}
 static boolean labelMatches(String text,VodSource.Title wanted){String n=VodProviders.normal(text.replaceAll("(?i)\\s+(?:streaming|HD|ITA|SUB ITA).*?$",""));String a=VodProviders.normal(wanted.name),b=VodProviders.normal(wanted.json.optString("original_name"));return n.equals(a)||(!wanted.year.isEmpty()&&n.equals(a+wanted.year))||(!b.isEmpty()&&n.equals(b));}
 static String searchUrl(String home,String html,String query)throws Exception{
  Matcher forms=Pattern.compile("<form\\b([^>]*)>(.*?)</form>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);while(forms.find()){String action=attribute(forms.group(1),"action");String inputs=forms.group(2);Matcher fields=Pattern.compile("<input\\b[^>]*>",Pattern.CASE_INSENSITIVE).matcher(inputs);String key="";LinkedHashMap<String,String> parameters=new LinkedHashMap<>();while(fields.find()){String name=attribute(fields.group(),"name"),value=attribute(fields.group(),"value");if(Arrays.asList("q","s","key","keyword","search","story").contains(name))key=name;else if(attribute(fields.group(),"type").equalsIgnoreCase("hidden")&&!name.isEmpty()&&!name.toLowerCase(Locale.ROOT).contains("token"))parameters.put(name,value);}if(key.isEmpty())continue;parameters.put(key,query);String target=new URI(home+"/").resolve(action.isEmpty()?"/":action).toString();StringBuilder url=new StringBuilder(target);for(Map.Entry<String,String> e:parameters.entrySet())url.append(url.indexOf("?")<0?'?':'&').append(VodSource.encode(e.getKey())).append('=').append(VodSource.encode(e.getValue()));return url.toString();}
  return home+"/?s="+VodSource.encode(query);
 }
 static String titlePage(String html,String root,VodSource.Title wanted)throws Exception{
  Matcher links=Pattern.compile("<a\\b([^>]*)>(.*?)</a>",Pattern.CASE_INSENSITIVE|Pattern.DOTALL).matcher(html);String name=VodProviders.normal(wanted.name);while(links.find()){String href=attribute(links.group(1),"href"),title=attribute(links.group(1),"title"),label=decode(links.group(2));Matcher img=Pattern.compile("<img\\b[^>]*>",Pattern.CASE_INSENSITIVE).matcher(links.group(2));boolean imageMatch=false;while(img.find())imageMatch|=labelMatches(attribute(img.group(),"alt"),wanted);if(!labelMatches(label,wanted)&&!labelMatches(title,wanted)&&!imageMatch)continue;URI u=new URI(root).resolve(href);String host=u.getHost();if(!"https".equals(u.getScheme())||host==null||href.isEmpty()||u.getPath()==null||u.getPath().length()<3)continue;String rootHost=new URI(root).getHost().replaceFirst("^www\\.","");if(!host.replaceFirst("^www\\.","").equals(rootHost))continue;if(u.getPath().matches(".*(?:login|register|search|category|tag|feed).*"))continue;return u.toString();}return "";
 }
 static VodProviders.Match search(VodSettings.Source source,VodSource.Title wanted,VodSource.Fetcher f){try{String root=f.get(VodSource.fresh(source.url+"/"),"");if(root.contains("Site Unavailable"))return new VodProviders.Match(source,null,"Il sito mostra Site Unavailable");if(root.length()<400)return new VodProviders.Match(source,null,"Il sito restituisce una pagina vuota o di errore");
   if(root.contains("data-page")){try{JSONObject p=VodSource.props(root);if(p.has("scws_url"))return VodProviders.search(new VodSettings.Source(source.id,source.name,source.url,"streamingcommunity"),wanted,f);}catch(Exception ignored){}}
   String effective=new URI(canonical(root,source.url+"/")).resolve("/").toString();effective=VodSource.base(effective);String search=searchUrl(effective,root,wanted.name);String html=f.get(VodSource.fresh(search),effective+"/");String page=titlePage(html,canonical(html,search),wanted);if(page.isEmpty())return new VodProviders.Match(source,null,"Titolo non trovato");JSONObject j=new JSONObject(wanted.json.toString());j.put("_web_page",page);JSONObject metadata=TmdbClient.metadata(wanted);if(metadata!=null)j.put("_metadata",metadata);VodSource.Title title=new VodSource.Title(j,"");if(!wanted.series())try{resolve(page,f);return new VodProviders.Match(source,title,"Disponibile · player interno",page,true);}catch(Exception ignored){}return new VodProviders.Match(source,title,!wanted.series()&&WebMovieLinks.supported(source.url)?"Pagina trovata · prova player interno":"Pagina trovata · Gecko",page,false);
  }catch(Exception e){return new VodProviders.Match(source,null,VodNetwork.error(e));}}
 static VodSource.Stream resolve(String page,VodSource.Fetcher f)throws Exception{
  List<String> queue=new ArrayList<>();Map<String,String> parents=new HashMap<>();Set<String> seen=new HashSet<>();queue.add(page);parents.put(page,page);for(int n=0;n<queue.size()&&n<5;n++){String url=queue.get(n);if(!seen.add(url))continue;String html;try{html=f.get(VodSource.fresh(url),parents.get(url));}catch(Exception e){if(n==0)throw e;else continue;}String normalized=html.replace("\\/","/").replace("\\u0026","&").replace("&amp;","&");
   if(n==0&&WebMovieLinks.supported(page)){List<String> players=WebMovieLinks.players(normalized,url);if(!players.isEmpty()){for(String frame:players)if(queue.size()<8&&!queue.contains(frame)){queue.add(frame);parents.put(frame,url);}continue;}}
   if(normalized.contains("window.masterPlaylist")){String manifest;try{manifest=VodSource.playlist(normalized);}catch(Exception e){manifest="";}try{if(f.get(manifest,url).trim().startsWith("#EXTM3U"))return new VodSource.Stream(manifest,url);}catch(Exception ignored){}}
   Matcher hls=Pattern.compile("https://[^\\s\"'<>]+\\.m3u8(?:\\?[^\\s\"'<>]*)?",Pattern.CASE_INSENSITIVE).matcher(normalized);while(hls.find()){String manifest=hls.group();try{if(f.get(manifest,url).trim().startsWith("#EXTM3U"))return new VodSource.Stream(manifest,url);}catch(Exception ignored){}}
   Matcher videos=Pattern.compile("<(?:video|source)\\b[^>]*>",Pattern.CASE_INSENSITIVE).matcher(normalized);while(videos.find()){String src=attribute(videos.group(),"src");if(src.isEmpty())continue;String video=new URI(url).resolve(src).toString();if(video.startsWith("https://")&&video.matches("(?i).*\\.mp4(?:\\?.*)?"))return new VodSource.Stream(video,url);}
   for(String frame:WebMovieLinks.players(normalized,url))if(queue.size()<8&&!queue.contains(frame)){queue.add(frame);parents.put(frame,url);}

  }throw new Exception("Flusso diretto non disponibile · usa Gecko");
 }
}
